# ruff: noqa: BLE001
"""
Edge Export — Export WhiteMagic capabilities to other platforms.

Export formats:
1. JavaScript (for browsers, Node.js)
2. JSON (universal data exchange)
3. ONNX (for edge ML runtimes)
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from whitemagic.config.paths import get_state_root

logger = logging.getLogger(__name__)


class EdgeExporter:
    """Export WhiteMagic capabilities for edge deployment."""

    def __init__(self, export_dir: Path | None = None) -> None:
        if export_dir is None:
            export_dir = get_state_root() / "edge" / "exports"
        self.export_dir = Path(export_dir)
        self.export_dir.mkdir(parents=True, exist_ok=True)

    def export_json(self, data: dict[str, Any], filename: str) -> Path:
        """Export data as JSON."""
        path = self.export_dir / f"{filename}.json"
        path.write_text(json.dumps(data, indent=2))
        return path

    def export_config(self) -> dict[str, Any]:
        """Export system configuration for edge deployment."""
        config: dict[str, Any] = {
            "version": "23.3.1",
            "capabilities": [],
            "tools": [],
            "gardens": [],
        }
        try:
            from whitemagic.tools.dispatch_table import DISPATCH_TABLE

            config["tools"] = list(DISPATCH_TABLE.keys())[:50]
        except Exception:
            pass
        return config

    def export_javascript_module(self, data: dict[str, Any], module_name: str) -> Path:
        """Export data as a JavaScript module."""
        path = self.export_dir / f"{module_name}.js"
        js_content = "// Auto-generated by WhiteMagic Edge Export\n"
        js_content += f"export const {module_name} = {json.dumps(data, indent=2)};\n"
        path.write_text(js_content)
        return path

    def list_exports(self) -> list[Path]:
        """List all exported files."""
        return sorted(self.export_dir.iterdir())

    def summary(self) -> dict[str, Any]:
        exports = self.list_exports()
        return {
            "total_exports": len(exports),
            "export_dir": str(self.export_dir),
        }


_exporter: EdgeExporter | None = None


def get_edge_exporter() -> EdgeExporter:
    global _exporter
    if _exporter is None:
        _exporter = EdgeExporter()
    return _exporter
