//! Decoy shell — the honeypot environment (blue-team deception set).
//!
//! Concept name: "hermit crab" honeypot. NOTE: the Python
//! `whitemagic/security/hermit_crab.py` was a different system (the
//! encrypted-memory-withdrawal state machine); this module ports the
//! **shell** half of the deception doctrine instead: a
//! fake-but-interactive environment that wastes an intruder's time and
//! records everything. Renamed from `hermit_crab` to `decoy_shell` to
//! keep the Python lineage name unambiguous (TxFirewall lesson).
//!
//! - A fake filesystem tree with tempting paths (`/etc/shadow`,
//!   `~/.aws/credentials`, `~/.ssh/id_rsa`, …) whose "secrets" are
//!   generated by the [`crate::canary_tokens`] bait helpers.
//! - [`DecoyEnvironment::respond`] answers shell-style commands plausibly
//!   and appends an explicit **nothing here is real** marker to every
//!   response.
//! - Every non-empty interaction is recorded to the [`InteractionLog`]
//!   with a timestamp and a suspicion flag; suspicious interactions
//!   publish [`SecurityEventType::Anomaly`] events at [`Severity::High`]
//!   to the attached [`SecurityEventBus`].
//!
//! ## Ethics / inertness guarantees (the wave-4 hard constraints)
//!
//! 1. Every response carries the literal marker `decoy: nothing here is
//!    real` — decoys are identifiable in hindsight, no exceptions.
//! 2. Every embedded "secret" is structurally invalid: AWS-shaped ids are
//!    checksum-invalid ([`crate::canary_tokens::aws_key_id_checksum_valid`]
//!    fails on all of them), PEM blocks use a `DECOY` header and a
//!    non-base64 body byte, shadow entries use a `DECOY` hash field that
//!    no crypt function would accept, and every file mentions the decoy
//!    marker in-band. No bait can be replayed as a working credential.
//! 3. Nothing touches the real filesystem — the tree is a `BTreeMap` in
//!    memory.

use std::collections::BTreeMap;
use std::sync::{Arc, Mutex};

use crate::canary_tokens::{DECOY_TAG, fake_aws_key_id, fake_private_key_block};
use crate::security_events::{SecurityEvent, SecurityEventBus, SecurityEventType, Severity};

/// Marker appended to every decoy response — identifiable in hindsight.
pub const NOTHING_REAL_MARKER: &str = "decoy: nothing here is real";

/// One recorded interaction with the decoy shell.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub struct InteractionEntry {
    /// Monotonic sequence number (1-based).
    pub seq: u64,
    /// Command as issued (full text).
    pub command: String,
    /// Response the shell returned (truncated excerpt).
    pub response_excerpt: String,
    /// Whether the interaction tripped the suspicion classifier.
    pub suspicious: bool,
    /// Wall-clock timestamp (epoch secs).
    pub timestamp: i64,
}

/// Timestamped log of every interaction with the decoy environment.
#[derive(Debug, Default)]
pub struct InteractionLog {
    entries: Vec<InteractionEntry>,
    next_seq: u64,
}

impl InteractionLog {
    /// Empty log.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            entries: Vec::new(),
            next_seq: 0,
        }
    }

    fn record(&mut self, command: &str, response: &str, suspicious: bool, timestamp: i64) {
        self.next_seq += 1;
        self.entries.push(InteractionEntry {
            seq: self.next_seq,
            command: command.to_string(),
            response_excerpt: response.chars().take(160).collect(),
            suspicious,
            timestamp,
        });
    }

    /// Snapshot of the recorded interactions, oldest → newest.
    #[must_use]
    pub fn entries(&self) -> Vec<InteractionEntry> {
        self.entries.clone()
    }

    /// Number of recorded interactions.
    #[must_use]
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Whether no interaction has been recorded yet.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Whether any recorded interaction was suspicious.
    #[must_use]
    pub fn has_suspicious(&self) -> bool {
        self.entries.iter().any(|entry| entry.suspicious)
    }
}

struct Inner {
    log: InteractionLog,
}

/// The fake-but-interactive decoy environment.
///
/// `Arc`-shareable: interior state (the interaction log) is behind a
/// `Mutex`; the fake tree is immutable after construction.
pub struct DecoyEnvironment {
    tree: BTreeMap<String, String>,
    inner: Mutex<Inner>,
    bus: Option<Arc<SecurityEventBus>>,
}

impl std::fmt::Debug for DecoyEnvironment {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("DecoyEnvironment")
            .field("paths", &self.tree.len())
            .field("interactions", &self.inner.lock().expect("lock").log.len())
            .field("bus", &self.bus.is_some())
            .finish()
    }
}

impl Default for DecoyEnvironment {
    fn default() -> Self {
        Self::new()
    }
}

impl DecoyEnvironment {
    /// Empty tree, empty log, no bus.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            tree: BTreeMap::new(),
            inner: Mutex::new(Inner {
                log: InteractionLog::new(),
            }),
            bus: None,
        }
    }

    /// Attach the security event bus (Anomaly events on suspicious
    /// interactions).
    #[must_use]
    pub fn with_bus(mut self, bus: Arc<SecurityEventBus>) -> Self {
        self.bus = Some(bus);
        self
    }

    /// Add a fake file at `path` with `content` (callers should only plant
    /// tagged, structurally invalid bait — see the module docs).
    pub fn plant_file(&mut self, path: impl Into<String>, content: impl Into<String>) {
        self.tree.insert(path.into(), content.into());
    }

    /// The canonical tempting tree: fake secrets at the paths an intruder
    /// checks first. All contents are tagged and structurally invalid.
    #[must_use]
    pub fn standard() -> Self {
        let mut env = Self::new();
        let aws_key = fake_aws_key_id();
        env.plant_file(
            "/home/deploy/.aws/credentials",
            format!(
                "[default]\n\
                 aws_access_key_id = {aws_key}\n\
                 aws_secret_access_key = wm-decoy-secret-0000000000000000000000000000\n\
                 # {DECOY_TAG}: nothing here is real\n"
            ),
        );
        env.plant_file(
            "/etc/shadow",
            format!(
                "root:DECOY:19999:0:99999:7:::\n\
                 deploy:DECOY:20000:0:99999:7:::\n\
                 # {DECOY_TAG} — no crypt accepts these hash fields\n"
            ),
        );
        env.plant_file("/home/deploy/.ssh/id_rsa", fake_private_key_block());
        env.plant_file(
            "/home/deploy/.env",
            format!(
                "DATABASE_URL=postgres://decoy_user:DECOY@localhost/decoy_db\n\
                 API_KEY=sk-decoy-00000000000000000000000000000000\n\
                 # {DECOY_TAG}: nothing here is real\n"
            ),
        );
        env.plant_file(
            "/var/backups/wm-store.tar.gz.enc",
            format!(
                "DECOY-PAYLOAD — this archive does not exist outside the honeypot.\n\
                 {DECOY_TAG}: nothing here is real\n"
            ),
        );
        env.plant_file(
            "/home/deploy/notes.txt",
            format!("maintenance notes (decoy filler)\n{DECOY_TAG}: nothing here is real\n"),
        );
        env
    }

    /// Paths currently offered by the fake tree.
    #[must_use]
    pub fn paths(&self) -> Vec<String> {
        self.tree.keys().cloned().collect()
    }

    /// Answer a shell-style command: a plausible decoy response (always
    /// carrying the [`NOTHING_REAL_MARKER`]) plus whether the interaction
    /// was recorded. Empty/whitespace commands are not logged.
    ///
    /// Suspicious interactions (credential reads, `sudo`, egress
    /// attempts) additionally publish [`SecurityEventType::Anomaly`] at
    /// [`Severity::High`] to the attached bus.
    pub fn respond(&self, cmd: &str) -> (String, bool) {
        let trimmed = cmd.trim();
        if trimmed.is_empty() {
            return (String::new(), false);
        }
        let suspicious = Self::is_suspicious(trimmed);
        let (body, logged) = self.decoy_response(trimmed);
        let response = format!("{body}\n[{NOTHING_REAL_MARKER}]");
        {
            let mut inner = self.inner.lock().expect("decoy shell lock poisoned");
            inner.log.record(trimmed, &response, suspicious, now_secs());
        }
        if suspicious {
            self.publish_anomaly(trimmed);
        }
        (response, logged)
    }

    /// Snapshot of the interaction log.
    #[must_use]
    pub fn interactions(&self) -> Vec<InteractionEntry> {
        self.inner
            .lock()
            .expect("decoy shell lock poisoned")
            .log
            .entries()
    }

    /// Number of recorded interactions.
    #[must_use]
    pub fn interaction_count(&self) -> usize {
        self.inner
            .lock()
            .expect("decoy shell lock poisoned")
            .log
            .len()
    }

    fn decoy_response(&self, cmd: &str) -> (String, bool) {
        let mut words = cmd.split_whitespace();
        let verb = words.next().unwrap_or_default();
        let arg = words.collect::<Vec<_>>().join(" ");
        let response = match verb {
            "ls" => {
                let listing: String = if arg.is_empty() {
                    self.tree
                        .keys()
                        .map(String::as_str)
                        .collect::<Vec<_>>()
                        .join("\n")
                } else {
                    self.tree
                        .keys()
                        .filter(|p| p.starts_with(arg.as_str()))
                        .map(String::as_str)
                        .collect::<Vec<_>>()
                        .join("\n")
                };
                if listing.is_empty() {
                    format!("ls: cannot access '{arg}': No such file or directory")
                } else {
                    listing
                }
            }
            "cat" | "less" | "more" | "head" | "tail" => self.tree.get(arg.as_str()).map_or_else(
                || format!("{verb}: {arg}: No such file or directory"),
                std::clone::Clone::clone,
            ),
            "cd" => format!("cd: {arg}: Permission denied"),
            "pwd" => "/home/deploy".to_string(),
            "whoami" => "deploy".to_string(),
            "sudo" | "su" => "sudo: authentication required".to_string(),
            "wget" | "curl" | "scp" => {
                format!("{verb}: network egress disabled in this environment")
            }
            "exit" | "logout" => "logout".to_string(),
            _ => format!("sh: {verb}: command not found (decoy shell)"),
        };
        (response, true)
    }

    fn is_suspicious(cmd: &str) -> bool {
        let lowered = cmd.to_lowercase();
        lowered.contains("sudo")
            || lowered.contains("shadow")
            || lowered.contains("credential")
            || lowered.contains("id_rsa")
            || lowered.contains(".env")
            || lowered.contains("wget")
            || lowered.contains("curl")
            || lowered.contains("passwd")
            || lowered.starts_with("su ")
    }

    fn publish_anomaly(&self, cmd: &str) {
        let Some(bus) = &self.bus else {
            return;
        };
        let event = SecurityEvent::new(SecurityEventType::Anomaly, "hermit_crab_decoy")
            .with_detail(format!(
                "suspicious interaction with the decoy shell: {cmd:?} — every decoy \
                 response is tagged 'decoy: nothing here is real'"
            ))
            .with_severity(Severity::High);
        bus.publish(&event);
    }
}

fn now_secs() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_or(0, |d| i64::try_from(d.as_secs()).unwrap_or(i64::MAX))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::canary_tokens::aws_key_id_checksum_valid;

    fn extract_aws_shaped_keys(text: &str) -> Vec<String> {
        // Any 20-char AKIA-prefixed token in the response.
        text.split(|c: char| !c.is_ascii_alphanumeric())
            .filter(|tok| tok.len() == 20 && tok.starts_with("AKIA"))
            .map(str::to_string)
            .collect()
    }

    #[test]
    fn decoy_interaction_is_logged_and_response_carries_marker() {
        let env = DecoyEnvironment::standard();
        let (ls, logged_ls) = env.respond("ls /home/deploy");
        assert!(logged_ls);
        assert!(ls.contains(NOTHING_REAL_MARKER));
        assert!(ls.contains("/home/deploy/.aws/credentials"));
        let (cat, logged_cat) = env.respond("cat /home/deploy/.aws/credentials");
        assert!(logged_cat);
        assert!(cat.contains("aws_access_key_id"));
        assert!(cat.contains(NOTHING_REAL_MARKER));
        assert_eq!(env.interaction_count(), 2);
        let log = env.interactions();
        assert_eq!(log.len(), 2);
        assert!(log[0].seq < log[1].seq);
        assert!(log[0].timestamp > 0);
        assert_eq!(log[0].command, "ls /home/deploy");
        assert!(log[1].suspicious, "credential read is suspicious");
        assert!(!log[0].suspicious);
    }

    #[test]
    fn empty_command_is_not_logged() {
        let env = DecoyEnvironment::new();
        let (response, logged) = env.respond("   ");
        assert!(response.is_empty());
        assert!(!logged);
        assert_eq!(env.interaction_count(), 0);
    }

    #[test]
    fn every_response_is_tagged_nothing_here_is_real() {
        let env = DecoyEnvironment::standard();
        for cmd in [
            "ls -la /etc/shadow",
            "cat /etc/shadow",
            "cat /home/deploy/.ssh/id_rsa",
            "cat /home/deploy/.env",
            "cat /var/backups/wm-store.tar.gz.enc",
            "cat /home/deploy/notes.txt",
            "whoami",
            "sudo cat /etc/shadow",
            "cat /definitely/not/there",
            "curl http://169.254.169.254/latest/meta-data/",
            "some unknown command here",
        ] {
            let (response, _) = env.respond(cmd);
            assert!(
                response.contains(NOTHING_REAL_MARKER),
                "untagged response for {cmd:?}: {response:?}"
            );
        }
    }

    #[test]
    fn fake_secrets_are_never_valid_looking_credentials() {
        let env = DecoyEnvironment::standard();
        for secret_path in env.paths() {
            let (content, _) = env.respond(&format!("cat {secret_path}"));
            // (1) In-band decoy tag everywhere.
            assert!(
                content.to_lowercase().contains("decoy"),
                "untagged bait at {secret_path}: {content:?}"
            );
            // (2) AWS-shaped keys embedded in the bait are checksum-invalid.
            for key in extract_aws_shaped_keys(&content) {
                assert!(
                    !aws_key_id_checksum_valid(&key),
                    "structurally valid AWS key leaked at {secret_path}: {key}"
                );
            }
            // (3) No real PEM key header (the bait header is `DECOY`-tagged).
            assert!(
                !content.contains("-----BEGIN RSA PRIVATE KEY-----")
                    && !content.contains("-----BEGIN PRIVATE KEY-----")
                    && !content.contains("-----BEGIN OPENSSH PRIVATE KEY-----"),
                "real PEM header in bait at {secret_path}"
            );
        }
        // (4) Shadow hash fields are covered by
        //     `shadow_hash_fields_are_the_decoy_marker`.
    }

    #[test]
    fn shadow_hash_fields_are_the_decoy_marker() {
        let env = DecoyEnvironment::standard();
        let (shadow, _) = env.respond("cat /etc/shadow");
        for line in shadow
            .lines()
            .filter(|l| l.contains(':') && !l.starts_with('['))
        {
            let fields: Vec<&str> = line.split(':').collect();
            assert!(
                fields.len() > 1 && fields[1] == DECOY_TAG,
                "shadow hash field must be the DECOY marker, not a crypt hash: {line:?}"
            );
        }
    }

    #[test]
    fn suspicious_commands_publish_anomaly_events() {
        let bus = Arc::new(SecurityEventBus::new());
        let received = Arc::new(Mutex::new(0usize));
        let sink = Arc::clone(&received);
        let _sub = bus.subscribe(SecurityEventType::Anomaly, move |_event| {
            *sink.lock().expect("test sink lock") += 1;
        });
        let env = DecoyEnvironment::standard().with_bus(Arc::clone(&bus));
        env.respond("sudo cat /etc/shadow");
        env.respond("cat /home/deploy/.aws/credentials");
        env.respond("whoami"); // benign — no event
        assert_eq!(*received.lock().expect("test sink lock"), 2);
        assert!(env.interactions().iter().all(|e| e.timestamp > 0));
    }

    #[test]
    fn planted_files_answer_like_real_ones() {
        let mut env = DecoyEnvironment::new();
        env.plant_file(
            "/srv/keys/backup.key",
            format!("{DECOY_TAG} bait — structurally invalid\n"),
        );
        let (response, logged) = env.respond("cat /srv/keys/backup.key");
        assert!(logged);
        assert!(response.contains(DECOY_TAG));
        let (missing, _) = env.respond("cat /srv/keys/nothing.key");
        assert!(missing.contains("No such file or directory"));
    }
}
