/**
 * GET /api/prescience
 *
 * WhiteMagic prescience track record — validated predictions with
 * Brier scoring, calibration curves, and category breakdown.
 *
 * Static data generated by:
 *   python core/scripts/generate_prescience_json.py
 */

export const runtime = "nodejs";
export const revalidate = 300;

export async function GET() {
  // Static payload generated by core/scripts/generate_prescience_json.py
  const payload = {
    schema_version: "1.0.0",
    generated_at: new Date().toISOString(),
    system: {
      name: "WhiteMagic",
      version: "25.1.0",
      url: "https://whitemagic.dev",
    },
    note: "Full track record available at /api/prescience.json",
    counts: {
      claims: 38,
      validated: 38,
      total_points: 940,
      avg_lead_weeks: 24.9,
      brier_score: 0.0958,
      brier_skill_score: 0.6167,
    },
    categories: [
      "ai_governance",
      "ai_hardware",
      "ai_trends",
      "agent_architecture",
      "robotics",
      "energy",
      "geopolitics",
      "market_forecast",
    ],
  };

  return Response.json(payload, {
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": "public, max-age=300, s-maxage=300",
      "access-control-allow-origin": "*",
    },
  });
}
