/**
 * GET /api/prescience
 *
 * WhiteMagic prescience track record — validated predictions with
 * Brier scoring, calibration curves, and category breakdown.
 *
 * Static data generated by:
 *   python core/scripts/generate_prescience_json.py
 */

export const runtime = "nodejs";
export const revalidate = 300;

export async function GET() {
  // Static payload generated by core/scripts/generate_prescience_json.py
  const payload = {
    schema_version: "1.0.0",
    generated_at: new Date().toISOString(),
    system: {
      name: "WhiteMagic",
      version: "22.2.3",
      url: "https://whitemagic.dev",
    },
    note: "Full track record available at /api/prescience.json",
    counts: {
      claims: 15,
      validated: 15,
      total_points: 380,
      avg_lead_weeks: 25.4,
      brier_score: 0.0861,
      brier_skill_score: 0.6557,
    },
    categories: [
      "ai_governance",
      "ai_hardware",
      "ai_safety",
      "science",
      "infrastructure",
      "agentic_systems",
    ],
  };

  return Response.json(payload, {
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": "public, max-age=300, s-maxage=300",
      "access-control-allow-origin": "*",
    },
  });
}
