//! Local Copilot RPC Client — Asynchronous & HTTP client for local Qwen3-4B inference.
//!
//! Connects the WhiteMagic daemon watchdog, Kaizen friction monitors, and crash barriers
//! directly to the local copilot server (typically running on `http://127.0.0.1:18898`).
//! Provides automated diagnostic synthesis and actionable remediation when uncommitted
//! multi-step operations or friction bursts are detected.

#![forbid(unsafe_code)]

use serde::{Deserialize, Serialize};
use std::time::Duration;

/// Configuration for the local copilot RPC client.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CopilotConfig {
    /// Base URL of the local llama-server (e.g., `http://127.0.0.1:18898`).
    pub endpoint: String,
    /// Model identifier to report in requests.
    pub model: String,
    /// HTTP connection and read timeout.
    pub timeout: Duration,
    /// Maximum tokens for diagnostic synthesis.
    pub max_tokens: u32,
    /// Temperature (low for deterministic analysis).
    pub temperature: f32,
}

impl Default for CopilotConfig {
    fn default() -> Self {
        Self {
            endpoint: "http://127.0.0.1:18898".into(),
            model: "local-copilot".into(),
            timeout: Duration::from_secs(15),
            max_tokens: 384,
            temperature: 0.1,
        }
    }
}

impl CopilotConfig {
    /// Load configuration from environment variables with fallback defaults.
    #[must_use]
    pub fn from_env() -> Self {
        let endpoint = std::env::var("WM_COPILOT_ENDPOINT")
            .or_else(|_| std::env::var("WM_LLAMA_ENDPOINT"))
            .unwrap_or_else(|_| "http://127.0.0.1:18898".into());

        let model = std::env::var("WM_COPILOT_MODEL").unwrap_or_else(|_| "local-copilot".into());

        let timeout_secs = std::env::var("WM_COPILOT_TIMEOUT_SECS")
            .ok()
            .and_then(|s| s.parse::<u64>().ok())
            .unwrap_or(15);

        Self {
            endpoint,
            model,
            timeout: Duration::from_secs(timeout_secs),
            ..Default::default()
        }
    }
}

/// Structured diagnostic report generated by the local copilot or rule-based fallback.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiagnosticReport {
    /// Unix timestamp in seconds.
    pub timestamp: u64,
    /// Uncommitted operation IDs audited.
    pub uncommitted_ops: Vec<String>,
    /// Synthesized diagnosis explaining the root cause or anomaly.
    pub diagnosis: String,
    /// Proposed remediation or self-repair action.
    pub recommended_action: String,
    /// Anomaly severity ("low", "medium", "high", "critical").
    pub severity: String,
    /// Provenance source ("local_copilot" or "rule_based_fallback").
    pub source: String,
}

/// HTTP/RPC client for querying the local copilot.
pub struct CopilotClient {
    config: CopilotConfig,
    agent: ureq::Agent,
}

impl Default for CopilotClient {
    fn default() -> Self {
        Self::from_env()
    }
}

impl CopilotClient {
    /// Create a client with custom configuration.
    #[must_use]
    pub fn new(config: CopilotConfig) -> Self {
        let agent = ureq::config::Config::builder()
            .timeout_global(Some(config.timeout))
            .build()
            .new_agent();
        Self { config, agent }
    }

    /// Create a client using environment variables.
    #[must_use]
    pub fn from_env() -> Self {
        Self::new(CopilotConfig::from_env())
    }

    /// Check if the local copilot server is reachable and healthy.
    #[must_use]
    pub fn is_healthy(&self) -> bool {
        let url = format!("{}/health", self.config.endpoint.trim_end_matches('/'));
        match self.agent.get(&url).call() {
            Ok(resp) => resp.status().is_success(),
            Err(_) => false,
        }
    }

    /// Request a completion from the local copilot using `/completion` or `/v1/chat/completions`.
    pub fn complete(&self, prompt: &str, max_tokens: u32) -> Result<String, String> {
        let base = self.config.endpoint.trim_end_matches('/');
        let completion_url = format!("{base}/completion");

        let payload = serde_json::json!({
            "prompt": prompt,
            "n_predict": max_tokens,
            "temperature": self.config.temperature,
            "cache_prompt": true,
        });

        match self.agent.post(&completion_url).send_json(&payload) {
            Ok(resp) => {
                let body: serde_json::Value = resp
                    .into_body()
                    .read_json()
                    .map_err(|e| format!("Failed to parse copilot response: {e}"))?;
                if let Some(content) = body.get("content").and_then(|c| c.as_str()) {
                    return Ok(content.to_string());
                }
                Err("Missing 'content' field in copilot response".into())
            }
            Err(e) => Err(format!("Copilot request failed: {e}")),
        }
    }

    /// Synthesize an automated diagnostic report when uncommitted operations or friction events occur.
    ///
    /// If the local copilot is running, it queries the model with a structured prompt.
    /// If unreachable, it cleanly degrades to an analytical rule-based diagnostic.
    #[must_use]
    pub fn synthesize_diagnostic(
        &self,
        uncommitted_ops: &[String],
        recent_frictions: &[String],
    ) -> DiagnosticReport {
        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map_or(0, |d| d.as_secs());

        let severity = if !uncommitted_ops.is_empty() {
            "high"
        } else if !recent_frictions.is_empty() {
            "medium"
        } else {
            "low"
        };

        // If copilot is alive, invoke it
        if self.is_healthy() {
            let prompt = format!(
                "<|im_start|>system\n\
                 You are the WhiteMagic Diagnostic Copilot. Analyze the following system anomalies and provide a concise diagnosis and recommended action.\n\
                 <|im_end|>\n\
                 <|im_start|>user\n\
                 Uncommitted Crash-Barrier Operations: {uncommitted_ops:?}\n\
                 Recent Frictions: {recent_frictions:?}\n\n\
                 Provide diagnosis and recommended remediation:\n\
                 <|im_end|>\n\
                 <|im_start|>assistant\n"
            );

            if let Ok(analysis) = self.complete(&prompt, self.config.max_tokens) {
                return DiagnosticReport {
                    timestamp: now,
                    uncommitted_ops: uncommitted_ops.to_vec(),
                    diagnosis: analysis.trim().to_string(),
                    recommended_action: "Quarantine uncommitted operation records and execute rollback/reconciliation.".into(),
                    severity: severity.into(),
                    source: "local_copilot".into(),
                };
            }
        }

        // Rule-based graceful fallback
        let diagnosis = if uncommitted_ops.is_empty() {
            format!(
                "System friction recorded: {} events. No uncommitted operations.",
                recent_frictions.len()
            )
        } else {
            format!(
                "Detected {} uncommitted or unconfirmed multi-step operation(s): [{}]. Indicates aborted pipeline or crash barrier recovery point.",
                uncommitted_ops.len(),
                uncommitted_ops.join(", ")
            )
        };

        let action = if uncommitted_ops.is_empty() {
            "Monitor next cycle; investigate recurring errors if frequency escalates."
        } else {
            "Review write audit journal; discard or reconcile incomplete mutations."
        };

        DiagnosticReport {
            timestamp: now,
            uncommitted_ops: uncommitted_ops.to_vec(),
            diagnosis,
            recommended_action: action.into(),
            severity: severity.into(),
            source: "rule_based_fallback".into(),
        }
    }
}

// ── Tests ───────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_copilot_config_defaults() {
        let cfg = CopilotConfig::default();
        assert_eq!(cfg.endpoint, "http://127.0.0.1:18898");
        assert_eq!(cfg.max_tokens, 384);
    }

    #[test]
    fn test_diagnostic_fallback_when_offline() {
        let client = CopilotClient::new(CopilotConfig {
            endpoint: "http://127.0.0.1:59999".into(), // deliberate invalid port
            timeout: Duration::from_millis(50),
            ..Default::default()
        });

        assert!(!client.is_healthy());

        let report = client.synthesize_diagnostic(
            &["op-crash-001".to_string()],
            &["LMDB lock contention".to_string()],
        );

        assert_eq!(report.source, "rule_based_fallback");
        assert_eq!(report.severity, "high");
        assert!(report.diagnosis.contains("op-crash-001"));
        assert!(report.recommended_action.contains("write audit"));
    }
}
