"""Research Tools — Research DAG, Autoswarm, Warps, Mesh Experiment Sync."""

from whitemagic.tools.tool_types import ToolCategory, ToolDefinition, ToolSafety, ToolStability

TOOLS: list[ToolDefinition] = [
    # ── Research DAG ──
    ToolDefinition(
        name="research.dag.submit",
        description="Submit a hypothesis to the research DAG",
        category=ToolCategory.SYNTHESIS,
        safety=ToolSafety.WRITE,
        input_schema={
            "type": "object",
            "properties": {
                "hypothesis": {"type": "string", "description": "Hypothesis text"},
                "domain": {
                    "type": "string",
                    "enum": ["cognitive", "memory", "consciousness", "evolution", "synthesis", "governance", "inference", "custom"],
                    "default": "cognitive",
                },
                "parameters": {"type": "object", "description": "Experiment parameters"},
                "agent_id": {"type": "string", "description": "Submitting agent ID"},
                "inspiration_ids": {"type": "array", "items": {"type": "string"}, "description": "Breakthrough experiment IDs that inspired this"},
                "parent_id": {"type": "string", "description": "Parent experiment ID"},
                "metadata": {"type": "object", "description": "Additional metadata"},
            },
            "required": ["hypothesis"],
        },
        gana="gana_winnowing_basket",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="research.dag.result",
        description="Record an experiment result with fitness score",
        category=ToolCategory.SYNTHESIS,
        safety=ToolSafety.WRITE,
        input_schema={
            "type": "object",
            "properties": {
                "experiment_id": {"type": "string", "description": "Experiment ID"},
                "fitness_score": {"type": "number", "description": "Fitness score (0.0-1.0)"},
                "outcome": {"type": "object", "description": "Outcome details"},
            },
            "required": ["experiment_id", "fitness_score"],
        },
        gana="gana_winnowing_basket",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="research.dag.critique",
        description="Submit a peer critique of an experiment (score 1-10)",
        category=ToolCategory.SYNTHESIS,
        safety=ToolSafety.WRITE,
        input_schema={
            "type": "object",
            "properties": {
                "experiment_id": {"type": "string", "description": "Experiment ID"},
                "score": {"type": "integer", "minimum": 1, "maximum": 10, "description": "Critique score (1-10, 8+ = breakthrough)"},
                "critic_agent_id": {"type": "string", "description": "Critic agent ID"},
                "notes": {"type": "string", "description": "Critique notes"},
            },
            "required": ["experiment_id", "score"],
        },
        gana="gana_three_stars",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="research.dag.lineage",
        description="Get lineage tree for an experiment (ancestors + descendants)",
        category=ToolCategory.SYNTHESIS,
        safety=ToolSafety.READ,
        input_schema={
            "type": "object",
            "properties": {
                "experiment_id": {"type": "string", "description": "Experiment ID"},
                "max_depth": {"type": "integer", "default": 10, "description": "Maximum traversal depth"},
            },
            "required": ["experiment_id"],
        },
        gana="gana_winnowing_basket",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="research.dag.breakthroughs",
        description="List top breakthroughs, optionally filtered by domain",
        category=ToolCategory.SYNTHESIS,
        safety=ToolSafety.READ,
        input_schema={
            "type": "object",
            "properties": {
                "domain": {"type": "string", "description": "Filter by research domain"},
                "limit": {"type": "integer", "default": 20},
            },
        },
        gana="gana_winnowing_basket",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="research.dag.stats",
        description="Get research DAG statistics (total experiments, breakthroughs, etc.)",
        category=ToolCategory.SYNTHESIS,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
        gana="gana_winnowing_basket",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="research.dag.leaderboard",
        description="Get domain leaderboard (top experiments by fitness)",
        category=ToolCategory.SYNTHESIS,
        safety=ToolSafety.READ,
        input_schema={
            "type": "object",
            "properties": {
                "domain": {"type": "string", "default": "cognitive"},
                "limit": {"type": "integer", "default": 10},
            },
        },
        gana="gana_winnowing_basket",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="research.dag.experiments",
        description="Query experiments with optional domain and stage filters",
        category=ToolCategory.SYNTHESIS,
        safety=ToolSafety.READ,
        input_schema={
            "type": "object",
            "properties": {
                "domain": {"type": "string", "description": "Filter by domain"},
                "stage": {"type": "string", "description": "Filter by stage (hypothesis, trial, result, critique, breakthrough, failed)"},
                "limit": {"type": "integer", "default": 50},
                "offset": {"type": "integer", "default": 0},
            },
        },
        gana="gana_winnowing_basket",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── Autoswarm ──
    ToolDefinition(
        name="autoswarm.campaign",
        description="Launch an evolutionary campaign (hypothesis → trial → result → share)",
        category=ToolCategory.AGENT,
        safety=ToolSafety.WRITE,
        input_schema={
            "type": "object",
            "properties": {
                "campaign_name": {"type": "string", "default": "manual_campaign"},
                "domain": {"type": "string", "default": "cognitive"},
                "hypothesis_space": {"type": "string", "default": "guna_balance"},
                "n_trials": {"type": "integer", "default": 50},
                "max_iterations": {"type": "integer", "default": 10},
                "share_results": {"type": "boolean", "default": True},
                "dream_integration": {"type": "boolean", "default": True},
            },
        },
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="autoswarm.status",
        description="Get autoswarm status (running state, stats, recent campaigns)",
        category=ToolCategory.AGENT,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
        gana="gana_ghost",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="autoswarm.start",
        description="Start continuous evolutionary autoswarm loop",
        category=ToolCategory.AGENT,
        safety=ToolSafety.WRITE,
        input_schema={
            "type": "object",
            "properties": {
                "interval_seconds": {"type": "number", "default": 300.0},
            },
        },
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="autoswarm.stop",
        description="Stop continuous autoswarm loop",
        category=ToolCategory.AGENT,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── Warps ──
    ToolDefinition(
        name="warp.load",
        description="Load a warp preset by name, or stack multiple warps with 'stack' param",
        category=ToolCategory.AGENT,
        safety=ToolSafety.READ,
        input_schema={
            "type": "object",
            "properties": {
                "name": {"type": "string", "description": "Warp name (e.g. researcher, sentinel, oracle)"},
                "stack": {"type": "string", "description": "Stack multiple warps: 'researcher+sentinel'"},
            },
            "required": ["name"],
        },
        gana="gana_dipper",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="warp.list",
        description="List all available warps (built-in and custom)",
        category=ToolCategory.AGENT,
        safety=ToolSafety.READ,
        input_schema={
            "type": "object",
            "properties": {
                "include_custom": {"type": "boolean", "default": True},
            },
        },
        gana="gana_dipper",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="warp.create",
        description="Create a custom warp preset",
        category=ToolCategory.AGENT,
        safety=ToolSafety.WRITE,
        input_schema={
            "type": "object",
            "properties": {
                "name": {"type": "string", "description": "Warp name"},
                "description": {"type": "string"},
                "tools_allowed": {"type": "array", "items": {"type": "string"}},
                "tools_denied": {"type": "array", "items": {"type": "string"}},
                "dharma_profile": {"type": "string"},
                "inference_tier": {"type": "string", "enum": ["edge", "local_small", "local_large", "cloud"]},
                "galaxies_accessible": {"type": "array", "items": {"type": "string"}},
                "execution_mode": {"type": "string", "enum": ["interactive", "autonomous", "dream"]},
                "research_domains": {"type": "array", "items": {"type": "string"}},
                "shelter_template": {"type": "string", "enum": ["research", "sandbox", "production", "secure"]},
                "max_iterations": {"type": "integer"},
                "timeout_seconds": {"type": "integer"},
                "metadata": {"type": "object"},
                "persist": {"type": "boolean", "default": True},
            },
            "required": ["name"],
        },
        gana="gana_dipper",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="warp.delete",
        description="Delete a custom warp (built-in warps cannot be deleted)",
        category=ToolCategory.AGENT,
        safety=ToolSafety.DELETE,
        input_schema={
            "type": "object",
            "properties": {
                "name": {"type": "string", "description": "Warp name to delete"},
            },
            "required": ["name"],
        },
        gana="gana_dipper",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="warp.status",
        description="Get warp manager status (builtin count, custom count, names)",
        category=ToolCategory.AGENT,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
        gana="gana_dipper",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── Mesh Experiment Sync ──
    ToolDefinition(
        name="mesh.experiment.share",
        description="Share an experiment result to the P2P mesh",
        category=ToolCategory.AGENT,
        safety=ToolSafety.WRITE,
        input_schema={
            "type": "object",
            "properties": {
                "experiment_id": {"type": "string", "description": "Experiment ID to share"},
                "domain": {"type": "string", "description": "Research domain"},
            },
            "required": ["experiment_id"],
        },
        gana="gana_wings",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="mesh.experiment.receive",
        description="Receive an experiment from a peer node (called on EXPERIMENT_SHARE signal)",
        category=ToolCategory.AGENT,
        safety=ToolSafety.WRITE,
        input_schema={
            "type": "object",
            "properties": {
                "payload": {"type": "string", "description": "JSON payload with experiment data"},
                "source_node": {"type": "string", "description": "Source node ID"},
            },
            "required": ["payload"],
        },
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="mesh.experiment.status",
        description="Get experiment sync status (sent, received, imported counts)",
        category=ToolCategory.AGENT,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
        gana="gana_wings",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="mesh.experiment.peers",
        description="Get experiments received from peer nodes",
        category=ToolCategory.AGENT,
        safety=ToolSafety.READ,
        input_schema={
            "type": "object",
            "properties": {
                "domain": {"type": "string", "description": "Filter by domain"},
                "limit": {"type": "integer", "default": 20},
            },
        },
        gana="gana_wings",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="mesh.experiment.discover",
        description="Discover peers on the mesh network",
        category=ToolCategory.AGENT,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
        gana="gana_wings",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── Research DAG Synthesis ──
    ToolDefinition(
        name="research.dag.synthesize",
        description="Generate a synthesis (mini research paper) from accumulated experiments",
        category=ToolCategory.SYNTHESIS,
        safety=ToolSafety.WRITE,
        input_schema={
            "type": "object",
            "properties": {
                "domain": {"type": "string", "description": "Filter by research domain"},
                "min_experiments": {"type": "integer", "default": 5, "description": "Minimum experiments needed"},
                "top_n": {"type": "integer", "default": 10, "description": "Number of top experiments to include"},
            },
        },
        gana="gana_three_stars",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── CRDT Leaderboard ──
    ToolDefinition(
        name="leaderboard.submit",
        description="Submit an experiment to the distributed CRDT leaderboard",
        category=ToolCategory.AGENT,
        safety=ToolSafety.WRITE,
        input_schema={
            "type": "object",
            "properties": {
                "experiment_id": {"type": "string", "description": "Experiment ID"},
                "hypothesis": {"type": "string", "description": "Hypothesis text"},
                "domain": {"type": "string", "default": "custom"},
                "fitness_score": {"type": "number", "description": "Fitness score (0.0-1.0)"},
                "agent_id": {"type": "string"},
                "metadata": {"type": "object"},
            },
            "required": ["experiment_id", "fitness_score"],
        },
        gana="gana_wings",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="leaderboard.top",
        description="Get top entries from the distributed leaderboard",
        category=ToolCategory.AGENT,
        safety=ToolSafety.READ,
        input_schema={
            "type": "object",
            "properties": {
                "n": {"type": "integer", "default": 10},
                "domain": {"type": "string", "description": "Filter by domain"},
            },
        },
        gana="gana_wings",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="leaderboard.status",
        description="Get CRDT leaderboard status (Loro enabled, entries, merges)",
        category=ToolCategory.AGENT,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
        gana="gana_wings",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="leaderboard.merge",
        description="Merge remote leaderboard data from a peer node",
        category=ToolCategory.AGENT,
        safety=ToolSafety.WRITE,
        input_schema={
            "type": "object",
            "properties": {
                "remote_data": {"type": "string", "description": "Serialized CRDT update or JSON from peer"},
            },
            "required": ["remote_data"],
        },
        gana="gana_wings",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── Pulse Verification ──
    ToolDefinition(
        name="pulse.verify",
        description="Verify an experiment pulse through tiered checks (Ed25519 + Merkle + karma)",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={
            "type": "object",
            "properties": {
                "experiment_id": {"type": "string", "description": "Experiment ID to verify"},
                "experiment_data": {"type": "object", "description": "Data to verify against Merkle root"},
                "node_reputation": {"type": "number", "default": 0.5, "description": "Node reputation (0.0-1.0)"},
                "force_tier": {"type": "integer", "description": "Force verification up to tier (0-3)"},
            },
            "required": ["experiment_id"],
        },
        gana="gana_hairy_head",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="pulse.verify.status",
        description="Get pulse verification system status",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
        gana="gana_hairy_head",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── Critique Protocol ──
    ToolDefinition(
        name="critique.submit",
        description="Submit a structured peer critique (methodology, novelty, significance, reproducibility)",
        category=ToolCategory.SYNTHESIS,
        safety=ToolSafety.WRITE,
        input_schema={
            "type": "object",
            "properties": {
                "experiment_id": {"type": "string", "description": "Experiment ID to critique"},
                "scores": {
                    "type": "object",
                    "description": "Dimension scores (1-10): methodology, novelty, significance, reproducibility",
                    "properties": {
                        "methodology": {"type": "integer", "minimum": 1, "maximum": 10},
                        "novelty": {"type": "integer", "minimum": 1, "maximum": 10},
                        "significance": {"type": "integer", "minimum": 1, "maximum": 10},
                        "reproducibility": {"type": "integer", "minimum": 1, "maximum": 10},
                    },
                },
                "critic_agent_id": {"type": "string", "default": "anonymous"},
                "written_review": {"type": "string", "description": "Written feedback"},
            },
            "required": ["experiment_id", "scores"],
        },
        gana="gana_three_stars",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="critique.auto",
        description="Automatically critique an experiment using heuristics",
        category=ToolCategory.SYNTHESIS,
        safety=ToolSafety.WRITE,
        input_schema={
            "type": "object",
            "properties": {
                "experiment_id": {"type": "string", "description": "Experiment ID to critique"},
                "critic_agent_id": {"type": "string", "default": "auto_critic"},
            },
            "required": ["experiment_id"],
        },
        gana="gana_three_stars",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="critique.status",
        description="Get critique protocol status (total critiques, accept/reject counts)",
        category=ToolCategory.SYNTHESIS,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
        gana="gana_three_stars",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── Durable Archive ──
    ToolDefinition(
        name="archive.run",
        description="Run a durable archive cycle (snapshot breakthroughs to git branch)",
        category=ToolCategory.AGENT,
        safety=ToolSafety.WRITE,
        input_schema={
            "type": "object",
            "properties": {
                "force": {"type": "boolean", "default": False, "description": "Re-archive even already-archived experiments"},
            },
        },
        gana="gana_wings",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="archive.status",
        description="Get durable archive status (files, commits, last archive time)",
        category=ToolCategory.AGENT,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
        gana="gana_wings",
        stability=ToolStability.EXPERIMENTAL,
    ),
]
