"""Registry definitions for security bounty tools (v24.1).

Foundry bridge, ABI decoder, vuln knowledge, contest pipeline, OSS scanner.
"""
from whitemagic.tools.tool_types import (
    ToolCategory,
    ToolDefinition,
    ToolSafety,
    ToolStability,
)

TOOLS: list[ToolDefinition] = [
    # ── Foundry Bridge ──
    ToolDefinition(
        name="foundry.build",
        description="Build a Foundry project using forge build",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={
            "project_dir": {"type": "string", "description": "Foundry project directory"},
            "silent": {"type": "boolean", "default": True},
        },
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="foundry.test",
        description="Run Foundry tests with forge test",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={
            "project_dir": {"type": "string", "description": "Foundry project directory"},
            "match": {"type": "string", "description": "Test name pattern to match"},
            "gas_report": {"type": "boolean", "default": False},
        },
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="foundry.test_json",
        description="Run Foundry tests and return JSON output",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={
            "project_dir": {"type": "string", "description": "Foundry project directory"},
            "match": {"type": "string", "description": "Test name pattern to match"},
        },
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── ABI Decoder ──
    ToolDefinition(
        name="abi.parse",
        description="Parse Solidity ABI JSON into function signatures",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={
            "abi_json": {"type": "string", "description": "ABI JSON string"},
        },
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="abi.summarize",
        description="Summarize an ABI — function count, events, signatures",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={
            "abi_json": {"type": "string", "description": "ABI JSON string"},
        },
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="abi.decode_calldata",
        description="Decode raw calldata hex into selector and parameters",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={
            "calldata": {"type": "string", "description": "Hex calldata string"},
            "abi_json": {"type": "string", "description": "Optional ABI JSON for function name matching"},
        },
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── Vulnerability Knowledge ──
    ToolDefinition(
        name="vuln.search",
        description="Search vulnerability knowledge base by keyword or category",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={
            "query": {"type": "string", "description": "Search query"},
        },
        gana="gana_extended_net",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="vuln.status",
        description="Get vulnerability knowledge base status",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={},
        gana="gana_extended_net",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="vuln.ingest_report",
        description="Ingest an audit report into the vulnerability knowledge base",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.WRITE,
        input_schema={
            "report_text": {"type": "string", "description": "Audit report text"},
            "source": {"type": "string", "default": "audit_report"},
        },
        gana="gana_extended_net",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── Contest Pipeline ──
    ToolDefinition(
        name="contest.add_finding",
        description="Add a finding to the contest pipeline",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.WRITE,
        input_schema={
            "title": {"type": "string"},
            "severity": {"type": "string"},
            "category": {"type": "string"},
            "file": {"type": "string"},
            "line": {"type": "integer"},
            "description": {"type": "string"},
            "impact": {"type": "string"},
            "proof_of_concept": {"type": "string"},
            "mitigation": {"type": "string"},
        },
        gana="gana_wall",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="contest.format",
        description="Format findings for a specific contest platform (code4rena, sherlock, etc.)",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={
            "platform": {"type": "string", "default": "code4rena"},
        },
        gana="gana_wall",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="contest.status",
        description="Get contest pipeline status",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={},
        gana="gana_wall",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── OSS Bounty Scanner ──
    ToolDefinition(
        name="oss.scan_repo",
        description="Scan a GitHub repo for bounty-labeled issues",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={
            "repo": {"type": "string", "description": "GitHub repo (owner/name)"},
        },
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="oss.scan_org",
        description="Scan all repos in a GitHub org for bounties",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={
            "org": {"type": "string", "description": "GitHub org name"},
        },
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── Aggregate ──
    ToolDefinition(
        name="security.status",
        description="Get aggregate status of all security subsystems",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={},
        gana="gana_ghost",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── PoC Pipeline ──
    ToolDefinition(
        name="poc.generate",
        description="Generate a PoC from a template with variables",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={
            "template_name": {"type": "string"},
            "variables": {"type": "object"},
            "tier": {"type": "string", "default": "default"},
        },
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="poc.verify",
        description="Full PoC pipeline: governance → render → compile → test → verify",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={
            "template_name": {"type": "string"},
            "variables": {"type": "object"},
            "project_dir": {"type": "string"},
            "tier": {"type": "string", "default": "huben"},
            "target": {"type": "string"},
        },
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="contest.prepare",
        description="One-command contest setup: clone → scan → filter → prioritize",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={
            "repo_url": {"type": "string"},
            "project_dir": {"type": "string"},
            "checkers": {"type": "array", "items": {"type": "string"}},
        },
        gana="gana_wall",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── HTTP Probe ──
    ToolDefinition(
        name="http_probe.get",
        description="Send an HTTP GET request",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"url": {"type": "string"}, "params": {"type": "object"}, "headers": {"type": "object"}},
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="http_probe.post",
        description="Send an HTTP POST request",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"url": {"type": "string"}, "json": {"type": "object"}, "data": {"type": "object"}, "headers": {"type": "object"}},
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="http_probe.xss",
        description="Probe a URL parameter for reflected XSS",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"url": {"type": "string"}, "param": {"type": "string"}},
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="http_probe.sqli",
        description="Probe a URL parameter for SQL injection",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"url": {"type": "string"}, "param": {"type": "string"}},
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="http_probe.idor",
        description="Probe for IDOR by iterating resource IDs",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"base_url": {"type": "string"}, "resource_path": {"type": "string"}, "max_id": {"type": "integer", "default": 20}},
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="http_probe.ssrf",
        description="Probe a URL parameter for SSRF",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"url": {"type": "string"}, "param": {"type": "string"}},
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="api.state_machine",
        description="Run API call sequences and detect state inconsistencies",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"base_url": {"type": "string"}, "sequences": {"type": "array"}},
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── Echidna ──
    ToolDefinition(
        name="echidna.fuzz",
        description="Run Echidna property-based fuzzer on a Solidity contract",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"contract_file": {"type": "string"}, "contract_name": {"type": "string"}, "config_file": {"type": "string"}, "workdir": {"type": "string"}},
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="echidna.status",
        description="Check Echidna availability and configuration",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={},
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── Fix Generator ──
    ToolDefinition(
        name="fix.generate",
        description="Generate fix suggestions from STRATA findings",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"findings": {"type": "array"}, "project_path": {"type": "string"}},
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="fix.apply",
        description="Apply a fix to a file (dry-run by default)",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.WRITE,
        input_schema={"file": {"type": "string"}, "line": {"type": "integer"}, "original": {"type": "string"}, "fixed": {"type": "string"}, "dry_run": {"type": "boolean", "default": True}},
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="pr.create",
        description="Create a GitHub PR with security fix",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.WRITE,
        input_schema={"repo_dir": {"type": "string"}, "branch_name": {"type": "string"}, "title": {"type": "string"}, "body": {"type": "string"}, "labels": {"type": "array"}, "bounty_ref": {"type": "string"}},
        gana="gana_wall",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="bounty.track",
        description="Track bounty earnings as a memory artifact",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.WRITE,
        input_schema={"source": {"type": "string"}, "amount": {"type": "string"}, "issue_url": {"type": "string"}, "status": {"type": "string", "default": "pending"}},
        gana="gana_abundance",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── Report Scraper ──
    ToolDefinition(
        name="report.scrape",
        description="Scrape a public audit report from Code4rena/Sherlock/CodeHawks",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"url": {"type": "string"}, "platform": {"type": "string", "default": "code4rena"}},
        gana="gana_extended_net",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="report.ingest",
        description="Scrape and ingest a report into the vuln knowledge base",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.WRITE,
        input_schema={"url": {"type": "string"}, "platform": {"type": "string", "default": "code4rena"}},
        gana="gana_extended_net",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── Phase 7: Advanced Tools ──
    ToolDefinition(
        name="vuln_graph.status",
        description="Get vulnerability knowledge graph status",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={},
        gana="gana_extended_net",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="vuln_graph.chains",
        description="Find exploit chains from a starting vulnerability",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"start_vuln": {"type": "string"}, "max_depth": {"type": "integer", "default": 5}},
        gana="gana_extended_net",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="vuln_graph.cross_chain",
        description="Analyze vulnerabilities across multiple blockchain protocols",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"chains": {"type": "array"}},
        gana="gana_extended_net",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="formal.verify",
        description="Run formal verification (Halmos/Certora) on Solidity contracts",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"project_dir": {"type": "string"}, "match": {"type": "string", "default": ".*"}},
        gana="gana_three_stars",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="formal.status",
        description="Check formal verification solver availability",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={},
        gana="gana_three_stars",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="swarm.analyze",
        description="Run multi-agent security analysis swarm on a project",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"project_path": {"type": "string"}},
        gana="gana_ox",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="swarm.status",
        description="Get security swarm status",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={},
        gana="gana_ox",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="predictive.score",
        description="Score a contract for vulnerability risk using predictive model",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"contract_file": {"type": "string"}, "contract_name": {"type": "string"}, "content": {"type": "string"}},
        gana="gana_dipper",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="predictive.batch",
        description="Batch score multiple contracts for vulnerability risk",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"contracts": {"type": "array"}},
        gana="gana_dipper",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="audit.report",
        description="Generate a professional audit report from findings",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"project_name": {"type": "string"}, "findings": {"type": "array"}, "format": {"type": "string", "default": "standard"}, "coverage": {"type": "object"}},
        gana="gana_chariot",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="monitor.status",
        description="Get security monitor status",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={},
        gana="gana_hairy_head",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="monitor.alerts",
        description="Get recent security alerts",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"severity": {"type": "string"}, "limit": {"type": "integer", "default": 100}},
        gana="gana_hairy_head",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="monitor.contract",
        description="Register a contract for real-time monitoring",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.WRITE,
        input_schema={"address": {"type": "string"}, "chain_id": {"type": "integer", "default": 1}},
        gana="gana_hairy_head",
        stability=ToolStability.EXPERIMENTAL,
    ),
    # ── Slither Integration ──
    ToolDefinition(
        name="slither.scan",
        description="Run Slither static analysis on a Solidity project",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"project_dir": {"type": "string"}},
        gana="gana_three_stars",
        stability=ToolStability.EXPERIMENTAL,
    ),
    ToolDefinition(
        name="slither.status",
        description="Check Slither availability and version",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={},
        gana="gana_three_stars",
        stability=ToolStability.EXPERIMENTAL,
    ),
]
