"""Auto-generated tool definitions for unauthored intelligence."""

from whitemagic.tools.tool_types import (
    ToolCategory,
    ToolDefinition,
    ToolSafety,
)

TOOLS: list[ToolDefinition] = [
    ToolDefinition(
        name="codegenome.fork",
        description="WhiteMagic tool: codegenome fork",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="codegenome.generate",
        description="WhiteMagic tool: codegenome generate",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="codegenome.list",
        description="WhiteMagic tool: codegenome list",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="codegenome.status",
        description="WhiteMagic tool: codegenome status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="codegenome_validate",
        description="WhiteMagic tool: codegenome validate",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="genetic.run",
        description="WhiteMagic tool: genetic run",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="genetic.status",
        description="WhiteMagic tool: genetic status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="causal.mine",
        description="WhiteMagic tool: causal mine",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="causal.stats",
        description="WhiteMagic tool: causal stats",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="bridge.synthesize",
        description="WhiteMagic tool: bridge synthesize",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="elemental.optimize",
        description="WhiteMagic tool: elemental optimize",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="solve_optimization",
        description="WhiteMagic tool: solve optimization",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="parallel_reason",
        description="WhiteMagic tool: parallel reason",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="thought_clone",
        description="WhiteMagic tool: thought clone",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="image_analyze",
        description="WhiteMagic tool: image analyze",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="analyze_scratchpad",
        description="WhiteMagic tool: analyze scratchpad",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="discover",
        description="WhiteMagic tool: discover",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="focus_session",
        description="WhiteMagic tool: focus session",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="anti_loop_check",
        description="WhiteMagic tool: anti loop check",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="resonance_trace",
        description="WhiteMagic tool: resonance trace",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="view_hologram",
        description="WhiteMagic tool: view hologram",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="vitality",
        description="WhiteMagic tool: vitality",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="wu_xing_balance",
        description="WhiteMagic tool: wu xing balance",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="zodiac.status",
        description="WhiteMagic tool: zodiac status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="astro_shift",
        description="WhiteMagic tool: astro shift",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="astro_status",
        description="WhiteMagic tool: astro status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="alchemical_cycle",
        description="WhiteMagic tool: alchemical cycle",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="satkona.fuse",
        description="WhiteMagic tool: satkona fuse",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="guna.correct",
        description="WhiteMagic tool: guna correct",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="navigate_grimoire",
        description="WhiteMagic tool: navigate grimoire",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="grimoire_list",
        description="WhiteMagic tool: grimoire list",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="grimoire_read",
        description="WhiteMagic tool: grimoire read",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="get_agent_capabilities",
        description="WhiteMagic tool: get agent capabilities",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="get_dharma_guidance",
        description="WhiteMagic tool: get dharma guidance",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="get_ethical_score",
        description="WhiteMagic tool: get ethical score",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="get_session_context",
        description="WhiteMagic tool: get session context",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="get_telemetry_summary",
        description="WhiteMagic tool: get telemetry summary",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="capability.matrix",
        description="WhiteMagic tool: capability matrix",
        category=ToolCategory.INTROSPECTION,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="capability.status",
        description="WhiteMagic tool: capability status",
        category=ToolCategory.INTROSPECTION,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="capability.suggest",
        description="WhiteMagic tool: capability suggest",
        category=ToolCategory.INTROSPECTION,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="capability_harness",
        description="WhiteMagic tool: capability harness",
        category=ToolCategory.INTROSPECTION,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="prat_get_context",
        description="WhiteMagic tool: prat get context",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="prat_invoke",
        description="WhiteMagic tool: prat invoke",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="prat_list_morphologies",
        description="WhiteMagic tool: prat list morphologies",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="prat_status",
        description="WhiteMagic tool: prat status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
]
