"""Auto-generated tool definitions for unauthored archaeology."""

from whitemagic.tools.tool_types import (
    ToolCategory,
    ToolDefinition,
    ToolSafety,
)

TOOLS: list[ToolDefinition] = [
    ToolDefinition(
        name="archaeology_daily_digest",
        description="WhiteMagic tool: archaeology daily digest",
        category=ToolCategory.ARCHAEOLOGY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="archaeology_find_changed",
        description="WhiteMagic tool: archaeology find changed",
        category=ToolCategory.ARCHAEOLOGY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="archaeology_find_unread",
        description="WhiteMagic tool: archaeology find unread",
        category=ToolCategory.ARCHAEOLOGY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="archaeology_have_read",
        description="WhiteMagic tool: archaeology have read",
        category=ToolCategory.ARCHAEOLOGY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="archaeology_mark_read",
        description="WhiteMagic tool: archaeology mark read",
        category=ToolCategory.ARCHAEOLOGY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="archaeology_mark_written",
        description="WhiteMagic tool: archaeology mark written",
        category=ToolCategory.ARCHAEOLOGY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="archaeology_process_wisdom",
        description="WhiteMagic tool: archaeology process wisdom",
        category=ToolCategory.ARCHAEOLOGY,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="archaeology_recent_reads",
        description="WhiteMagic tool: archaeology recent reads",
        category=ToolCategory.ARCHAEOLOGY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="archaeology_report",
        description="WhiteMagic tool: archaeology report",
        category=ToolCategory.ARCHAEOLOGY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="archaeology_scan_directory",
        description="WhiteMagic tool: archaeology scan directory",
        category=ToolCategory.ARCHAEOLOGY,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="archaeology_search",
        description="WhiteMagic tool: archaeology search",
        category=ToolCategory.ARCHAEOLOGY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="archaeology_stats",
        description="WhiteMagic tool: archaeology stats",
        category=ToolCategory.ARCHAEOLOGY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="research_repo",
        description="WhiteMagic tool: research repo",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="research_topic",
        description="WhiteMagic tool: research topic",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="research_url",
        description="WhiteMagic tool: research url",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="rabbit_hole_research",
        description="WhiteMagic tool: rabbit hole research",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="deep_fetch",
        description="WhiteMagic tool: deep fetch",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="external.repo_compare",
        description="WhiteMagic tool: external repo compare",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="external.repo_scan",
        description="WhiteMagic tool: external repo scan",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="external.wiki_query",
        description="WhiteMagic tool: external wiki query",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="wiki.generate",
        description="WhiteMagic tool: wiki generate",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="wiki.query",
        description="WhiteMagic tool: wiki query",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="wiki.scan",
        description="WhiteMagic tool: wiki scan",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="wiki.stats",
        description="WhiteMagic tool: wiki stats",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="wiki.update",
        description="WhiteMagic tool: wiki update",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="windsurf_export_conversation",
        description="WhiteMagic tool: windsurf export conversation",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="windsurf_list_conversations",
        description="WhiteMagic tool: windsurf list conversations",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="windsurf_read_conversation",
        description="WhiteMagic tool: windsurf read conversation",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="windsurf_search_conversations",
        description="WhiteMagic tool: windsurf search conversations",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="windsurf_stats",
        description="WhiteMagic tool: windsurf stats",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
]
