"""Auto-generated tool definitions for unauthored garden."""

from whitemagic.tools.tool_types import (
    ToolCategory,
    ToolDefinition,
    ToolSafety,
)

TOOLS: list[ToolDefinition] = [
    ToolDefinition(
        name="garden_browse",
        description="WhiteMagic tool: garden browse",
        category=ToolCategory.GARDEN,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="garden_list_files",
        description="WhiteMagic tool: garden list files",
        category=ToolCategory.GARDEN,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="garden_list_functions",
        description="WhiteMagic tool: garden list functions",
        category=ToolCategory.GARDEN,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="garden_map_system",
        description="WhiteMagic tool: garden map system",
        category=ToolCategory.GARDEN,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="garden_resolve",
        description="WhiteMagic tool: garden resolve",
        category=ToolCategory.GARDEN,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="garden_resonance",
        description="WhiteMagic tool: garden resonance",
        category=ToolCategory.GARDEN,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="garden_search",
        description="WhiteMagic tool: garden search",
        category=ToolCategory.GARDEN,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="garden_stats",
        description="WhiteMagic tool: garden stats",
        category=ToolCategory.GARDEN,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="garden_synergy",
        description="WhiteMagic tool: garden synergy",
        category=ToolCategory.GARDEN,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="skill.amend",
        description="WhiteMagic tool: skill amend",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="skill.evaluate",
        description="WhiteMagic tool: skill evaluate",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="skill.export_all",
        description="WhiteMagic tool: skill export all",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="skill.history",
        description="WhiteMagic tool: skill history",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="skill.import",
        description="WhiteMagic tool: skill import",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="skill.invoke",
        description="WhiteMagic tool: skill invoke",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="skill.list",
        description="WhiteMagic tool: skill list",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="skill.rollback",
        description="WhiteMagic tool: skill rollback",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="skill.seed",
        description="WhiteMagic tool: skill seed",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="pattern.avoid",
        description="WhiteMagic tool: pattern avoid",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="pattern.ingest",
        description="WhiteMagic tool: pattern ingest",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="pattern.learn",
        description="WhiteMagic tool: pattern learn",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="pattern.list",
        description="WhiteMagic tool: pattern list",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="pattern.lookup",
        description="WhiteMagic tool: pattern lookup",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="pattern.resolve",
        description="WhiteMagic tool: pattern resolve",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="pattern.summary",
        description="WhiteMagic tool: pattern summary",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="guideline.evolve",
        description="WhiteMagic tool: guideline evolve",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="art_of_war.assess",
        description="WhiteMagic tool: art of war assess",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="art_of_war.campaign",
        description="WhiteMagic tool: art of war campaign",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="art_of_war.chapter",
        description="WhiteMagic tool: art of war chapter",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="art_of_war.plan",
        description="WhiteMagic tool: art of war plan",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="art_of_war.terrain",
        description="WhiteMagic tool: art of war terrain",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="art_of_war.wisdom",
        description="WhiteMagic tool: art of war wisdom",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="doctrine.force",
        description="WhiteMagic tool: doctrine force",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="doctrine.stratagems",
        description="WhiteMagic tool: doctrine stratagems",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="doctrine.summary",
        description="WhiteMagic tool: doctrine summary",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="war_room.campaigns",
        description="WhiteMagic tool: war room campaigns",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="war_room.execute",
        description="WhiteMagic tool: war room execute",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="war_room.hierarchy",
        description="WhiteMagic tool: war room hierarchy",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="war_room.phase",
        description="WhiteMagic tool: war room phase",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="war_room.plan",
        description="WhiteMagic tool: war room plan",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="war_room.status",
        description="WhiteMagic tool: war room status",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="fool_guard.dare_to_die",
        description="WhiteMagic tool: fool guard dare to die",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="fool_guard.ralph",
        description="WhiteMagic tool: fool guard ralph",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="fool_guard.status",
        description="WhiteMagic tool: fool guard status",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
]
