"""Auto-generated tool definitions for unauthored memory."""

from whitemagic.tools.tool_types import (
    ToolCategory,
    ToolDefinition,
    ToolSafety,
)

TOOLS: list[ToolDefinition] = [
    ToolDefinition(
        name="galaxy.backup",
        description="WhiteMagic tool: galaxy backup",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="galaxy.canonical_taxonomy",
        description="WhiteMagic tool: galaxy canonical taxonomy",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="galaxy.export_tutorial",
        description="WhiteMagic tool: galaxy export tutorial",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="galaxy.lineage",
        description="WhiteMagic tool: galaxy lineage",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="galaxy.lineage_stats",
        description="WhiteMagic tool: galaxy lineage stats",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="galaxy.merge",
        description="WhiteMagic tool: galaxy merge",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="galaxy.sync",
        description="WhiteMagic tool: galaxy sync",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="galaxy.taxonomy",
        description="WhiteMagic tool: galaxy taxonomy",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="galaxy.transfer",
        description="WhiteMagic tool: galaxy transfer",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="galaxy.use",
        description="WhiteMagic tool: galaxy use",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="memory.consolidate",
        description="WhiteMagic tool: memory consolidate",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="memory.consolidation_stats",
        description="WhiteMagic tool: memory consolidation stats",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="memory.lifecycle",
        description="WhiteMagic tool: memory lifecycle",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="memory.lifecycle_stats",
        description="WhiteMagic tool: memory lifecycle stats",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="memory.lifecycle_sweep",
        description="WhiteMagic tool: memory lifecycle sweep",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="memory.retention_sweep",
        description="WhiteMagic tool: memory retention sweep",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="memory_delete",
        description="WhiteMagic tool: memory delete",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="memory_read",
        description="WhiteMagic tool: memory read",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="memory_search",
        description="WhiteMagic tool: memory search",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="memory_update",
        description="WhiteMagic tool: memory update",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="oms.export",
        description="WhiteMagic tool: oms export",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="oms.import",
        description="WhiteMagic tool: oms import",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="oms.inspect",
        description="WhiteMagic tool: oms inspect",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="oms.list",
        description="WhiteMagic tool: oms list",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="oms.price",
        description="WhiteMagic tool: oms price",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="oms.status",
        description="WhiteMagic tool: oms status",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="oms.verify",
        description="WhiteMagic tool: oms verify",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="search.telemetry",
        description="WhiteMagic tool: search telemetry",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="search_memories",
        description="WhiteMagic tool: search memories",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="search_query",
        description="WhiteMagic tool: search query",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="association.mine",
        description="WhiteMagic tool: association mine",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="association.mine_semantic",
        description="WhiteMagic tool: association mine semantic",
        category=ToolCategory.MEMORY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="list_ganas",
        description="WhiteMagic tool: list ganas",
        category=ToolCategory.INTROSPECTION,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="list_memories",
        description="WhiteMagic tool: list memories",
        category=ToolCategory.INTROSPECTION,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="batch_read_memories",
        description="WhiteMagic tool: batch read memories",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="fast_read_memory",
        description="WhiteMagic tool: fast read memory",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="read_memory",
        description="WhiteMagic tool: read memory",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="create_memory",
        description="WhiteMagic tool: create memory",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="delete_memory",
        description="WhiteMagic tool: delete memory",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="update_memory",
        description="WhiteMagic tool: update memory",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="export_memories",
        description="WhiteMagic tool: export memories",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="import_memories",
        description="WhiteMagic tool: import memories",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
]
