"""Auto-generated tool definitions for unauthored infrastructure."""

from whitemagic.tools.tool_types import (
    ToolCategory,
    ToolDefinition,
    ToolSafety,
)

TOOLS: list[ToolDefinition] = [
    ToolDefinition(
        name="cache.flush",
        description="WhiteMagic tool: cache flush",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="cache.status",
        description="WhiteMagic tool: cache status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="cache.tune",
        description="WhiteMagic tool: cache tune",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="embedding.daemon_process",
        description="WhiteMagic tool: embedding daemon process",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="embedding.daemon_start",
        description="WhiteMagic tool: embedding daemon start",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="embedding.daemon_status",
        description="WhiteMagic tool: embedding daemon status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="embedding.daemon_stop",
        description="WhiteMagic tool: embedding daemon stop",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="vector.index",
        description="WhiteMagic tool: vector index",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="vector.search",
        description="WhiteMagic tool: vector search",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="vector.status",
        description="WhiteMagic tool: vector status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="otel.metrics",
        description="WhiteMagic tool: otel metrics",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="otel.spans",
        description="WhiteMagic tool: otel spans",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="otel.status",
        description="WhiteMagic tool: otel status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="rate_limiter.stats",
        description="WhiteMagic tool: rate limiter stats",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="rust_audit",
        description="WhiteMagic tool: rust audit",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="rust_compress",
        description="WhiteMagic tool: rust compress",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="pipeline.create",
        description="WhiteMagic tool: pipeline create",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="pipeline.list",
        description="WhiteMagic tool: pipeline list",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="pipeline.status",
        description="WhiteMagic tool: pipeline status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="broker.history",
        description="WhiteMagic tool: broker history",
        category=ToolCategory.BROKER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="broker.publish",
        description="WhiteMagic tool: broker publish",
        category=ToolCategory.BROKER,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="broker.status",
        description="WhiteMagic tool: broker status",
        category=ToolCategory.BROKER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="ganying_emit",
        description="WhiteMagic tool: ganying emit",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="ganying_history",
        description="WhiteMagic tool: ganying history",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="ganying_listeners",
        description="WhiteMagic tool: ganying listeners",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="homeostasis.check",
        description="WhiteMagic tool: homeostasis check",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="homeostasis.status",
        description="WhiteMagic tool: homeostasis status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="anomaly.check",
        description="WhiteMagic tool: anomaly check",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="anomaly.history",
        description="WhiteMagic tool: anomaly history",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="anomaly.status",
        description="WhiteMagic tool: anomaly status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="ambient.state",
        description="WhiteMagic tool: ambient state",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="ambient.status",
        description="WhiteMagic tool: ambient status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="state.paths",
        description="WhiteMagic tool: state paths",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="state.summary",
        description="WhiteMagic tool: state summary",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="tool.graph_full",
        description="WhiteMagic tool: tool graph full",
        category=ToolCategory.INTROSPECTION,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="tool_usage_stats",
        description="WhiteMagic tool: tool usage stats",
        category=ToolCategory.INTROSPECTION,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="wm_help",
        description="WhiteMagic tool: wm help",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="audit.export",
        description="WhiteMagic tool: audit export",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="token_report",
        description="WhiteMagic tool: token report",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="voice_audit.quarantine_list",
        description="WhiteMagic tool: voice audit quarantine list",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="voice_audit.scan",
        description="WhiteMagic tool: voice audit scan",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="voice_audit.status",
        description="WhiteMagic tool: voice audit status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="scratchpad_create",
        description="WhiteMagic tool: scratchpad create",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="scratchpad_finalize",
        description="WhiteMagic tool: scratchpad finalize",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="scratchpad_update",
        description="WhiteMagic tool: scratchpad update",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="starter_packs.get",
        description="WhiteMagic tool: starter packs get",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="starter_packs.list",
        description="WhiteMagic tool: starter packs list",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="starter_packs.suggest",
        description="WhiteMagic tool: starter packs suggest",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="starter_packs",
        description="WhiteMagic tool: starter packs",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="galactic.stats",
        description="WhiteMagic tool: galactic stats",
        category=ToolCategory.INTROSPECTION,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="galactic.sweep",
        description="WhiteMagic tool: galactic sweep",
        category=ToolCategory.INTROSPECTION,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="galactic_dashboard",
        description="WhiteMagic tool: galactic dashboard",
        category=ToolCategory.INTROSPECTION,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="edge_add_rule",
        description="WhiteMagic tool: edge add rule",
        category=ToolCategory.EDGE,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="repo.summary",
        description="WhiteMagic tool: repo summary",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
]
