"""Auto-generated tool definitions for unauthored consciousness."""

from whitemagic.tools.tool_types import (
    ToolCategory,
    ToolDefinition,
    ToolSafety,
)

TOOLS: list[ToolDefinition] = [
    ToolDefinition(
        name="consciousness.awaken",
        description="WhiteMagic tool: consciousness awaken",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="consciousness.calibration",
        description="WhiteMagic tool: consciousness calibration",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="consciousness.coherence",
        description="WhiteMagic tool: consciousness coherence",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="consciousness.depth",
        description="WhiteMagic tool: consciousness depth",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="consciousness.flow",
        description="WhiteMagic tool: consciousness flow",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="consciousness.narrative",
        description="WhiteMagic tool: consciousness narrative",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="consciousness.reflect",
        description="WhiteMagic tool: consciousness reflect",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="consciousness.smarana",
        description="WhiteMagic tool: consciousness smarana",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="consciousness.status",
        description="WhiteMagic tool: consciousness status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="consciousness.stillness",
        description="WhiteMagic tool: consciousness stillness",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="consciousness.time_dilation",
        description="WhiteMagic tool: consciousness time dilation",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="consciousness.token_economy",
        description="WhiteMagic tool: consciousness token economy",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="consciousness.token_report",
        description="WhiteMagic tool: consciousness token report",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="consciousness.unified_field",
        description="WhiteMagic tool: consciousness unified field",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="citta.continuity",
        description="WhiteMagic tool: citta continuity",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="citta.cycle",
        description="WhiteMagic tool: citta cycle",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="citta.ignitions",
        description="WhiteMagic tool: citta ignitions",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="citta.sensorium",
        description="WhiteMagic tool: citta sensorium",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="citta.stream_summary",
        description="WhiteMagic tool: citta stream summary",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="coherence_boost",
        description="WhiteMagic tool: coherence boost",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="pattern_consciousness.status",
        description="WhiteMagic tool: pattern consciousness status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="cognitive.action_loop",
        description="WhiteMagic tool: cognitive action loop",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="cognitive.patterns",
        description="WhiteMagic tool: cognitive patterns",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="cognitive.signals",
        description="WhiteMagic tool: cognitive signals",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="reasoning.bicameral",
        description="WhiteMagic tool: reasoning bicameral",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="reasoning.multispectral",
        description="WhiteMagic tool: reasoning multispectral",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="corpus_callosum.debate",
        description="WhiteMagic tool: corpus callosum debate",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="corpus_callosum.status",
        description="WhiteMagic tool: corpus callosum status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="novelty.detect",
        description="WhiteMagic tool: novelty detect",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="novelty.stats",
        description="WhiteMagic tool: novelty stats",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="salience.spotlight",
        description="WhiteMagic tool: salience spotlight",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="foresight.analyze",
        description="WhiteMagic tool: foresight analyze",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="foresight.constellations",
        description="WhiteMagic tool: foresight constellations",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="foresight.convergence",
        description="WhiteMagic tool: foresight convergence",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="foresight.decay",
        description="WhiteMagic tool: foresight decay",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="constellation.detect",
        description="WhiteMagic tool: constellation detect",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="constellation.merge",
        description="WhiteMagic tool: constellation merge",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="constellation.stats",
        description="WhiteMagic tool: constellation stats",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="emergence.insights",
        description="WhiteMagic tool: emergence insights",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="emergence.scan",
        description="WhiteMagic tool: emergence scan",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="emergence.status",
        description="WhiteMagic tool: emergence status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="ensemble.history",
        description="WhiteMagic tool: ensemble history",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="ensemble.query",
        description="WhiteMagic tool: ensemble query",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="ensemble.status",
        description="WhiteMagic tool: ensemble status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="neurotransmitter.report",
        description="WhiteMagic tool: neurotransmitter report",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="neurotransmitter.status",
        description="WhiteMagic tool: neurotransmitter status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="dream.expire",
        description="WhiteMagic tool: dream expire",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.DELETE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="dream.list",
        description="WhiteMagic tool: dream list",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="dream.promote",
        description="WhiteMagic tool: dream promote",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="dream.read",
        description="WhiteMagic tool: dream read",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="dream_now",
        description="WhiteMagic tool: dream now",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="dream_start",
        description="WhiteMagic tool: dream start",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="dream_status",
        description="WhiteMagic tool: dream status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="dream_stop",
        description="WhiteMagic tool: dream stop",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="hexagram.boltzmann_select",
        description="WhiteMagic tool: hexagram boltzmann select",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="hexagram.dispatch",
        description="WhiteMagic tool: hexagram dispatch",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="hexagram.interaction_score",
        description="WhiteMagic tool: hexagram interaction score",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="hexagram.nearest",
        description="WhiteMagic tool: hexagram nearest",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="hexagram.simd_execute",
        description="WhiteMagic tool: hexagram simd execute",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="hexagram.superpose",
        description="WhiteMagic tool: hexagram superpose",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="hexagram.synergies",
        description="WhiteMagic tool: hexagram synergies",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="hexagram.vector",
        description="WhiteMagic tool: hexagram vector",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="cast_oracle",
        description="WhiteMagic tool: cast oracle",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
]
