"""Auto-generated tool definitions for unauthored security."""

from whitemagic.tools.tool_types import (
    ToolCategory,
    ToolDefinition,
    ToolSafety,
)

TOOLS: list[ToolDefinition] = [
    ToolDefinition(
        name="agent_redteam.run",
        description="WhiteMagic tool: agent redteam run",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="agent_redteam.status",
        description="WhiteMagic tool: agent redteam status",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="redteam.autonomous",
        description="WhiteMagic tool: redteam autonomous",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="redteam.status",
        description="WhiteMagic tool: redteam status",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="attack_cell.execute",
        description="WhiteMagic tool: attack cell execute",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="attack_cell.status",
        description="WhiteMagic tool: attack cell status",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="nmap_scan",
        description="WhiteMagic tool: nmap scan",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="nikto_scan",
        description="WhiteMagic tool: nikto scan",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="nuclei_scan",
        description="WhiteMagic tool: nuclei scan",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="sqlmap_scan",
        description="WhiteMagic tool: sqlmap scan",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="ffuf_fuzz",
        description="WhiteMagic tool: ffuf fuzz",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="hydra_brute",
        description="WhiteMagic tool: hydra brute",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="shelter.create",
        description="WhiteMagic tool: shelter create",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="shelter.destroy",
        description="WhiteMagic tool: shelter destroy",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.DELETE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="shelter.execute",
        description="WhiteMagic tool: shelter execute",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="shelter.inspect",
        description="WhiteMagic tool: shelter inspect",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="shelter.policy",
        description="WhiteMagic tool: shelter policy",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="shelter.status",
        description="WhiteMagic tool: shelter status",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="tx_firewall.set_policy",
        description="WhiteMagic tool: tx firewall set policy",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="tx_firewall.status",
        description="WhiteMagic tool: tx firewall status",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="bounty.auto_claim",
        description="WhiteMagic tool: bounty auto claim",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="bounty.connector_status",
        description="WhiteMagic tool: bounty connector status",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="bounty.scan",
        description="WhiteMagic tool: bounty scan",
        category=ToolCategory.SECURITY,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="verification.attest",
        description="WhiteMagic tool: verification attest",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="verification.request",
        description="WhiteMagic tool: verification request",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="verification.status",
        description="WhiteMagic tool: verification status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="verify_consent",
        description="WhiteMagic tool: verify consent",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="wasm_verify.status",
        description="WhiteMagic tool: wasm verify status",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="check_boundaries",
        description="WhiteMagic tool: check boundaries",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="evaluate_ethics",
        description="WhiteMagic tool: evaluate ethics",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="immune_heal",
        description="WhiteMagic tool: immune heal",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="immune_scan",
        description="WhiteMagic tool: immune scan",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
]
