"""Auto-generated tool definitions for unauthored browser."""

from whitemagic.tools.tool_types import (
    ToolCategory,
    ToolDefinition,
    ToolSafety,
)

TOOLS: list[ToolDefinition] = [
    ToolDefinition(
        name="web_cache_clear",
        description="WhiteMagic tool: web cache clear",
        category=ToolCategory.BROWSER,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="web_cache_list",
        description="WhiteMagic tool: web cache list",
        category=ToolCategory.BROWSER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="web_fetch",
        description="WhiteMagic tool: web fetch",
        category=ToolCategory.BROWSER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="web_fetch_enhanced",
        description="WhiteMagic tool: web fetch enhanced",
        category=ToolCategory.BROWSER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="web_search",
        description="WhiteMagic tool: web search",
        category=ToolCategory.BROWSER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="web_search_and_read",
        description="WhiteMagic tool: web search and read",
        category=ToolCategory.BROWSER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="web_search_batch",
        description="WhiteMagic tool: web search batch",
        category=ToolCategory.BROWSER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="web_search_category",
        description="WhiteMagic tool: web search category",
        category=ToolCategory.BROWSER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="browser_click",
        description="WhiteMagic tool: browser click",
        category=ToolCategory.BROWSER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="browser_extract_dom",
        description="WhiteMagic tool: browser extract dom",
        category=ToolCategory.BROWSER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="browser_get_interactables",
        description="WhiteMagic tool: browser get interactables",
        category=ToolCategory.BROWSER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="browser_navigate",
        description="WhiteMagic tool: browser navigate",
        category=ToolCategory.BROWSER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="browser_screenshot",
        description="WhiteMagic tool: browser screenshot",
        category=ToolCategory.BROWSER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="browser_session_status",
        description="WhiteMagic tool: browser session status",
        category=ToolCategory.BROWSER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="browser_type",
        description="WhiteMagic tool: browser type",
        category=ToolCategory.BROWSER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="marketplace.complete",
        description="WhiteMagic tool: marketplace complete",
        category=ToolCategory.AGENT,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="marketplace.discover",
        description="WhiteMagic tool: marketplace discover",
        category=ToolCategory.AGENT,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="marketplace.my_listings",
        description="WhiteMagic tool: marketplace my listings",
        category=ToolCategory.AGENT,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="marketplace.negotiate",
        description="WhiteMagic tool: marketplace negotiate",
        category=ToolCategory.AGENT,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="marketplace.publish",
        description="WhiteMagic tool: marketplace publish",
        category=ToolCategory.AGENT,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="marketplace.remove",
        description="WhiteMagic tool: marketplace remove",
        category=ToolCategory.AGENT,
        safety=ToolSafety.DELETE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="marketplace.status",
        description="WhiteMagic tool: marketplace status",
        category=ToolCategory.AGENT,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="ilp.balance",
        description="WhiteMagic tool: ilp balance",
        category=ToolCategory.AGENT,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="ilp.configure",
        description="WhiteMagic tool: ilp configure",
        category=ToolCategory.AGENT,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="ilp.history",
        description="WhiteMagic tool: ilp history",
        category=ToolCategory.AGENT,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="ilp.receipt",
        description="WhiteMagic tool: ilp receipt",
        category=ToolCategory.AGENT,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="ilp.send",
        description="WhiteMagic tool: ilp send",
        category=ToolCategory.AGENT,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="ilp.status",
        description="WhiteMagic tool: ilp status",
        category=ToolCategory.AGENT,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
]
