"""Auto-generated tool definitions for unauthored session."""

from whitemagic.tools.tool_types import (
    ToolCategory,
    ToolDefinition,
    ToolSafety,
)

TOOLS: list[ToolDefinition] = [
    ToolDefinition(
        name="session.accept_handoff",
        description="WhiteMagic tool: session accept handoff",
        category=ToolCategory.SESSION,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="session.handoff_transfer",
        description="WhiteMagic tool: session handoff transfer",
        category=ToolCategory.SESSION,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="session.list_handoffs",
        description="WhiteMagic tool: session list handoffs",
        category=ToolCategory.SESSION,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="session_handoff",
        description="WhiteMagic tool: session handoff",
        category=ToolCategory.SESSION,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="session_handoff_summary",
        description="WhiteMagic tool: session handoff summary",
        category=ToolCategory.SESSION,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="session_status",
        description="WhiteMagic tool: session status",
        category=ToolCategory.SESSION,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="task.complete",
        description="WhiteMagic tool: task complete",
        category=ToolCategory.TASK,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="task.distribute",
        description="WhiteMagic tool: task distribute",
        category=ToolCategory.TASK,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="task.list",
        description="WhiteMagic tool: task list",
        category=ToolCategory.TASK,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="task.status",
        description="WhiteMagic tool: task status",
        category=ToolCategory.TASK,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="watcher_add",
        description="WhiteMagic tool: watcher add",
        category=ToolCategory.WATCHER,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="watcher_list",
        description="WhiteMagic tool: watcher list",
        category=ToolCategory.WATCHER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="watcher_recent_events",
        description="WhiteMagic tool: watcher recent events",
        category=ToolCategory.WATCHER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="watcher_remove",
        description="WhiteMagic tool: watcher remove",
        category=ToolCategory.WATCHER,
        safety=ToolSafety.DELETE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="watcher_start",
        description="WhiteMagic tool: watcher start",
        category=ToolCategory.WATCHER,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="watcher_stats",
        description="WhiteMagic tool: watcher stats",
        category=ToolCategory.WATCHER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="watcher_status",
        description="WhiteMagic tool: watcher status",
        category=ToolCategory.WATCHER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="watcher_stop",
        description="WhiteMagic tool: watcher stop",
        category=ToolCategory.WATCHER,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="model.optimize",
        description="WhiteMagic tool: model optimize",
        category=ToolCategory.INFERENCE,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="model.optimize_status",
        description="WhiteMagic tool: model optimize status",
        category=ToolCategory.INFERENCE,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
]
