"""Auto-generated tool definitions for unauthored governance."""

from whitemagic.tools.tool_types import (
    ToolCategory,
    ToolDefinition,
    ToolSafety,
)

TOOLS: list[ToolDefinition] = [
    ToolDefinition(
        name="karma.anchor",
        description="WhiteMagic tool: karma anchor",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="karma.anchor_status",
        description="WhiteMagic tool: karma anchor status",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="karma.verify_anchor",
        description="WhiteMagic tool: karma verify anchor",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="karma_record",
        description="WhiteMagic tool: karma record",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="karma_report",
        description="WhiteMagic tool: karma report",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="karmic_trace",
        description="WhiteMagic tool: karmic trace",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="network_state.create_identity",
        description="WhiteMagic tool: network state create identity",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="network_state.propose",
        description="WhiteMagic tool: network state propose",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="network_state.resolve",
        description="WhiteMagic tool: network state resolve",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="network_state.status",
        description="WhiteMagic tool: network state status",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="network_state.vote",
        description="WhiteMagic tool: network state vote",
        category=ToolCategory.GOVERNANCE,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="vote.analyze",
        description="WhiteMagic tool: vote analyze",
        category=ToolCategory.VOTING,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="vote.cast",
        description="WhiteMagic tool: vote cast",
        category=ToolCategory.VOTING,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="vote.create",
        description="WhiteMagic tool: vote create",
        category=ToolCategory.VOTING,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="vote.list",
        description="WhiteMagic tool: vote list",
        category=ToolCategory.VOTING,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="vote.record_outcome",
        description="WhiteMagic tool: vote record outcome",
        category=ToolCategory.VOTING,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="governor_check_budget",
        description="WhiteMagic tool: governor check budget",
        category=ToolCategory.GOVERNOR,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="governor_check_dharma",
        description="WhiteMagic tool: governor check dharma",
        category=ToolCategory.GOVERNOR,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="governor_stats",
        description="WhiteMagic tool: governor stats",
        category=ToolCategory.GOVERNOR,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="governor_validate_path",
        description="WhiteMagic tool: governor validate path",
        category=ToolCategory.GOVERNOR,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="dharma_rules",
        description="WhiteMagic tool: dharma rules",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="set_dharma_profile",
        description="WhiteMagic tool: set dharma profile",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="sangha_lock_acquire",
        description="WhiteMagic tool: sangha lock acquire",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.WRITE,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="sangha_lock_list",
        description="WhiteMagic tool: sangha lock list",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="sangha_lock_release",
        description="WhiteMagic tool: sangha lock release",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="consult_wisdom_council",
        description="WhiteMagic tool: consult wisdom council",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
    ToolDefinition(
        name="ship.check",
        description="WhiteMagic tool: ship check",
        category=ToolCategory.SYSTEM,
        safety=ToolSafety.READ,
        input_schema={"type": "object", "properties": {}},
    ),
]
