/**
 * Gana Activity Heatmap — D3 radial heatmap of 28 Lunar Mansions
 *
 * Ported from whitemagic-aux/whitemagic-frontend/dashboard-app/GanaActivityHeatmap.tsx
 * Uses real tool counts from the static manifest (public/api/manifest.json)
 * to show how many tools each Gana governs. Uses D3 scaleSequential + interpolateViridis.
 */

"use client";

import { useEffect, useRef, useState, useMemo } from "react";
import { select, scaleSequential, interpolateViridis, arc } from "d3";

interface GanaActivity {
  glyph: string;
  name: string;
  nameZh: string;
  quadrant: "east" | "south" | "west" | "north";
  desc: string;
  toolCount: number;
  tools: string[];
}

const GANA_BASE: Array<{
  glyph: string;
  name: string;
  nameZh: string;
  quadrant: "east" | "south" | "west" | "north";
  desc: string;
}> = [
  { glyph: "\u89d2", name: "Horn", nameZh: "\u89d2\u5bbf", quadrant: "east", desc: "Session initialization" },
  { glyph: "\u4ea2", name: "Neck", nameZh: "\u4ea2\u5bbf", quadrant: "east", desc: "Memory creation" },
  { glyph: "\u6c10", name: "Root", nameZh: "\u6c10\u5bbf", quadrant: "east", desc: "System health" },
  { glyph: "\u623f", name: "Room", nameZh: "\u623f\u5bbf", quadrant: "east", desc: "Resource locks & privacy" },
  { glyph: "\u5fc3", name: "Heart", nameZh: "\u5fc3\u5bbf", quadrant: "east", desc: "Session context" },
  { glyph: "\u5c3e", name: "Tail", nameZh: "\u5c3e\u5bbf", quadrant: "east", desc: "Performance & acceleration" },
  { glyph: "\u7b95", name: "Basket", nameZh: "\u7b95\u5bbf", quadrant: "east", desc: "Wisdom & search" },
  { glyph: "\u9b3c", name: "Ghost", nameZh: "\u9b3c\u5bbf", quadrant: "south", desc: "Introspection & web" },
  { glyph: "\u67f3", name: "Willow", nameZh: "\u67f3\u5bbf", quadrant: "south", desc: "Resilience" },
  { glyph: "\u661f", name: "Star", nameZh: "\u661f\u5bbf", quadrant: "south", desc: "Governance" },
  { glyph: "\u5f20", name: "Net", nameZh: "\u5f20\u5bbf", quadrant: "south", desc: "Capture & filtering" },
  { glyph: "\u7ffc", name: "Wings", nameZh: "\u7ffc\u5bbf", quadrant: "south", desc: "Deployment & export" },
  { glyph: "\u8f78", name: "Chariot", nameZh: "\u8f78\u5bbf", quadrant: "south", desc: "Archaeology & KG" },
  { glyph: "\u8c50", name: "Abundance", nameZh: "\u8c50\u5bbf", quadrant: "south", desc: "Regeneration" },
  { glyph: "\u594e", name: "Legs", nameZh: "\u594e\u5bbf", quadrant: "west", desc: "Ethics & balance" },
  { glyph: "\u5a04", name: "Mound", nameZh: "\u5a04\u5bbf", quadrant: "west", desc: "Metrics & caching" },
  { glyph: "\u80c3", name: "Stomach", nameZh: "\u80c3\u5bbf", quadrant: "west", desc: "Digestion & tasks" },
  { glyph: "\u6634", name: "Hairy Head", nameZh: "\u6634\u5bbf", quadrant: "west", desc: "Detail & debug" },
  { glyph: "\u6bd5", name: "Extended Net", nameZh: "\u6bd5\u5bbf", quadrant: "west", desc: "Pattern connectivity" },
  { glyph: "\u89dc", name: "Turtle Beak", nameZh: "\u89dc\u5bbf", quadrant: "west", desc: "Precision" },
  { glyph: "\u53c2", name: "Three Stars", nameZh: "\u53c2\u5bbf", quadrant: "west", desc: "Judgment & synthesis" },
  { glyph: "\u6597", name: "Dipper", nameZh: "\u6597\u5bbf", quadrant: "north", desc: "Strategy" },
  { glyph: "\u725b", name: "Ox", nameZh: "\u725b\u5bbf", quadrant: "north", desc: "Endurance" },
  { glyph: "\u5973", name: "Girl", nameZh: "\u5973\u5bbf", quadrant: "north", desc: "Nurture" },
  { glyph: "\u865a", name: "Void", nameZh: "\u865a\u5bbf", quadrant: "north", desc: "Stillness & galaxies" },
  { glyph: "\u5371", name: "Roof", nameZh: "\u5371\u5bbf", quadrant: "north", desc: "Shelter" },
  { glyph: "\u5ba4", name: "Encampment", nameZh: "\u5ba4\u5bbf", quadrant: "north", desc: "Community" },
  { glyph: "\u58c1", name: "Wall", nameZh: "\u58c1\u5bbf", quadrant: "north", desc: "Boundaries" },
];

// Real tool counts from the static manifest (public/api/manifest.json)
// Generated by core/scripts/generate_manifest_json.py from the live tool registry
const GANA_TOOL_COUNTS: Record<string, { count: number; tools: string[] }> = {
  Horn: { count: 9, tools: ["checkpoint_session", "create_session", "focus_session", "resume_session", "session.accept_handoff", "session.handoff_transfer", "session.list_handoffs", "session_bootstrap", "session_status"] },
  Neck: { count: 8, tools: ["create_memory", "delete_memory", "import_memories", "memory_delete", "memory_update", "remember", "thought_clone", "update_memory"] },
  Root: { count: 9, tools: ["check", "health_report", "rust_audit", "rust_compress", "rust_similarity", "rust_status", "ship.check", "state.paths", "state.summary"] },
  Room: { count: 22, tools: ["anti_loop_check", "hermit.assess", "hermit.check_access", "hermit.mediate", "hermit.resolve", "hermit.status", "hermit.verify_ledger", "hermit.withdraw", "immune_heal", "immune_scan", "mcp_integrity.snapshot", "mcp_integrity.status", "mcp_integrity.verify", "sandbox.set_limits", "sandbox.status", "sandbox.violations", "sangha_lock", "sangha_lock_acquire", "sangha_lock_list", "sangha_lock_release", "security.alerts", "security.monitor_status"] },
  Heart: { count: 14, tools: ["analyze_scratchpad", "context.pack", "context.status", "get_session_context", "scratchpad", "scratchpad_create", "scratchpad_finalize", "scratchpad_update", "session.handoff", "session_handoff", "session_handoff_summary", "working_memory.attend", "working_memory.context", "working_memory.status"] },
  Tail: { count: 6, tools: ["execute_cascade", "list_cascade_patterns", "simd.batch", "simd.cosine", "simd.status", "token_report"] },
  Basket: { count: 18, tools: ["batch_read_memories", "fast_read_memory", "fragment.index", "fragment.query", "fragment.search", "fragment.status", "graph_walk", "hybrid_recall", "jit_research", "jit_research.stats", "list_memories", "memory_read", "memory_search", "read_memory", "recall", "rerank", "rerank.status", "search_memories"] },
  Ghost: { count: 39, tools: [] },
  Willow: { count: 13, tools: [] },
  Star: { count: 17, tools: [] },
  Net: { count: 4, tools: [] },
  Wings: { count: 7, tools: [] },
  Chariot: { count: 41, tools: [] },
  Abundance: { count: 39, tools: [] },
  Legs: { count: 10, tools: [] },
  Mound: { count: 9, tools: [] },
  Stomach: { count: 9, tools: [] },
  Hairy: { count: 19, tools: [] },
  Net2: { count: 24, tools: [] },
  Turtle: { count: 6, tools: [] },
  Three: { count: 27, tools: [] },
  Dipper: { count: 19, tools: [] },
  Ox: { count: 14, tools: [] },
  Girl: { count: 6, tools: [] },
  Void: { count: 35, tools: [] },
  Roof: { count: 17, tools: [] },
  Encampment: { count: 8, tools: [] },
  Wall: { count: 10, tools: [] },
};

// Map GANA_BASE names to manifest keys for tool count lookup
const NAME_TO_KEY: Record<string, string> = {
  "Horn": "Horn",
  "Neck": "Neck",
  "Root": "Root",
  "Room": "Room",
  "Heart": "Heart",
  "Tail": "Tail",
  "Basket": "Basket",
  "Ghost": "Ghost",
  "Willow": "Willow",
  "Star": "Star",
  "Net": "Net",
  "Wings": "Wings",
  "Chariot": "Chariot",
  "Abundance": "Abundance",
  "Legs": "Legs",
  "Mound": "Mound",
  "Stomach": "Stomach",
  "Hairy Head": "Hairy",
  "Extended Net": "Net2",
  "Turtle Beak": "Turtle",
  "Three Stars": "Three",
  "Dipper": "Dipper",
  "Ox": "Ox",
  "Girl": "Girl",
  "Void": "Void",
  "Roof": "Roof",
  "Encampment": "Encampment",
  "Wall": "Wall",
};

function getGanaActivity(): GanaActivity[] {
  return GANA_BASE.map((g) => {
    const key = NAME_TO_KEY[g.name] || g.name;
    const data = GANA_TOOL_COUNTS[key] || { count: 0, tools: [] };
    return {
      ...g,
      toolCount: data.count,
      tools: data.tools,
    };
  });
}

const QUADRANT_LABELS: Record<string, string> = {
  east: "East \u00b7 Azure Dragon",
  south: "South \u00b7 Vermilion Bird",
  west: "West \u00b7 White Tiger",
  north: "North \u00b7 Black Tortoise",
};

export function GanaActivityHeatmap({ size = 500 }: { size?: number }) {
  const svgRef = useRef<SVGSVGElement>(null);
  const [selectedGana, setSelectedGana] = useState<GanaActivity | null>(null);

  const ganaData = useMemo(() => getGanaActivity(), []);

  const maxInvocations = useMemo(
    () => Math.max(...ganaData.map((d) => d.toolCount)),
    [ganaData],
  );

  useEffect(() => {
    const svgEl = svgRef.current;
    if (!svgEl || ganaData.length === 0) return;

    const svg = select(svgEl);
    svg.selectAll("*").remove();

    const width = size;
    const height = size;
    const centerX = width / 2;
    const centerY = height / 2;
    const radius = Math.min(width, height) / 2 - 50;
    const angleStep = (2 * Math.PI) / 28;

    const colorScale = scaleSequential(interpolateViridis)
      .domain([0, maxInvocations]);

    // Outer circle
    svg
      .append("circle")
      .attr("cx", centerX)
      .attr("cy", centerY)
      .attr("r", radius + 15)
      .attr("fill", "none")
      .attr("stroke", "#374151")
      .attr("stroke-width", 1)
      .attr("opacity", 0.5);

    // Quadrant divider lines
    [0, Math.PI / 2].forEach((rot) => {
      svg
        .append("line")
        .attr("x1", centerX + Math.cos(rot - Math.PI / 2) * (radius + 15))
        .attr("y1", centerY + Math.sin(rot - Math.PI / 2) * (radius + 15))
        .attr("x2", centerX + Math.cos(rot - Math.PI / 2 + Math.PI) * (radius + 15))
        .attr("y2", centerY + Math.sin(rot - Math.PI / 2 + Math.PI) * (radius + 15))
        .attr("stroke", "#4b5563")
        .attr("stroke-width", 1)
        .attr("stroke-dasharray", "4,4")
        .attr("opacity", 0.4);
    });

    // Gana segments
    const arcGen = arc<GanaActivity>()
      .innerRadius(radius * 0.35)
      .outerRadius((d) => radius * (0.35 + 0.65 * (d.toolCount / maxInvocations)))
      .startAngle((_, i) => i * angleStep - Math.PI / 2)
      .endAngle((_, i) => (i + 1) * angleStep - Math.PI / 2)
      .padAngle(0.02)
      .padRadius(radius * 0.35);

    svg
      .selectAll(".gana-segment")
      .data(ganaData)
      .enter()
      .append("path")
      .attr("class", "gana-segment")
      .attr("transform", `translate(${centerX}, ${centerY})`)
      .attr("d", arcGen as unknown as string)
      .attr("fill", (d) => colorScale(d.toolCount))
      .attr("stroke", "#1f2937")
      .attr("stroke-width", 1.5)
      .style("cursor", "pointer")
      .attr("tabindex", "0")
      .attr("role", "button")
      .attr("aria-label", (d) => `${d.name} (${d.nameZh}): ${d.toolCount} tools`)
      .on("mouseover", function (event, d) {
        select(this).attr("opacity", 0.75);
        setSelectedGana(d);
      })
      .on("mouseout", function () {
        select(this).attr("opacity", 1);
      })
      .on("click", function (event, d) {
        setSelectedGana(d);
      })
      .on("keydown", function (event, d) {
        if (event.key === "Enter" || event.key === " ") {
          event.preventDefault();
          setSelectedGana(d);
        }
      });

    // Glyph labels
    svg
      .selectAll(".gana-glyph")
      .data(ganaData)
      .enter()
      .append("text")
      .attr("class", "gana-glyph")
      .attr("x", (_, i) => {
        const angle = i * angleStep - Math.PI / 2 + angleStep / 2;
        return centerX + Math.cos(angle) * (radius * 0.2);
      })
      .attr("y", (_, i) => {
        const angle = i * angleStep - Math.PI / 2 + angleStep / 2;
        return centerY + Math.sin(angle) * (radius * 0.2);
      })
      .attr("text-anchor", "middle")
      .attr("dominant-baseline", "middle")
      .attr("font-size", "12px")
      .attr("font-family", "'Noto Serif SC', serif")
      .attr("fill", "#b8a9d4")
      .attr("opacity", 0.7)
      .text((d) => d.glyph);

    // Quadrant labels
    const quadrants = [
      { label: "EAST", x: centerX + radius + 30, y: centerY, color: "#22c55e" },
      { label: "SOUTH", x: centerX, y: centerY + radius + 35, color: "#ef4444" },
      { label: "WEST", x: centerX - radius - 30, y: centerY, color: "#eab308" },
      { label: "NORTH", x: centerX, y: centerY - radius - 35, color: "#3b82f6" },
    ];

    svg
      .selectAll(".quadrant-label")
      .data(quadrants)
      .enter()
      .append("text")
      .attr("class", "quadrant-label")
      .attr("x", (d) => d.x)
      .attr("y", (d) => d.y)
      .attr("text-anchor", "middle")
      .attr("dominant-baseline", "middle")
      .attr("font-size", "11px")
      .attr("font-weight", "bold")
      .attr("font-family", "monospace")
      .attr("fill", (d) => d.color)
      .attr("opacity", 0.6)
      .text((d) => d.label);
  }, [ganaData, maxInvocations, size]);

  return (
    <div className="flex flex-col items-center gap-6 lg:flex-row lg:items-start lg:justify-center">
      <div className="relative">
        <svg
          ref={svgRef}
          width={size}
          height={size}
          role="img"
          aria-label="28 Gana activity heatmap — radial chart showing invocation frequency per Lunar Mansion"
        />
      </div>

      {/* Detail Panel */}
      <div className="w-full max-w-sm">
        {selectedGana ? (
          <div className="rounded-2xl border border-border bg-surface p-6">
            <div className="mb-4 flex items-center gap-3">
              <span className="text-3xl font-bold text-lavender">
                {selectedGana.glyph}
              </span>
              <div>
                <h3 className="font-head text-lg font-semibold text-ink">
                  {selectedGana.name}
                </h3>
                <p className="font-mono text-xs text-dim">
                  {selectedGana.nameZh} \u00b7 {QUADRANT_LABELS[selectedGana.quadrant]}
                </p>
              </div>
            </div>

            <p className="mb-4 text-sm text-muted">{selectedGana.desc}</p>

            <div className="space-y-3 border-t border-border pt-4">
              <div className="flex justify-between text-sm">
                <span className="text-dim">Tools governed</span>
                <span className="font-mono font-medium text-green-400">
                  {selectedGana.toolCount}
                </span>
              </div>
              {selectedGana.tools.length > 0 && (
                <div className="border-t border-border pt-3">
                  <div className="mb-2 font-mono text-xs text-dim">Tool list</div>
                  <div className="flex flex-wrap gap-1">
                    {selectedGana.tools.map((t) => (
                      <span key={t} className="rounded bg-surface-alt px-1.5 py-0.5 font-mono text-[10px] text-muted">
                        {t}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>

            {/* Activity bar */}
            <div className="mt-4">
              <div className="mb-1 flex justify-between font-mono text-xs text-dim">
                <span>Capability density</span>
                <span>
                  {Math.round((selectedGana.toolCount / maxInvocations) * 100)}%
                </span>
              </div>
              <div className="h-2 overflow-hidden rounded-full bg-surface-alt">
                <div
                  className="h-full rounded-full transition-all duration-300"
                  style={{
                    width: `${(selectedGana.toolCount / maxInvocations) * 100}%`,
                    backgroundColor: interpolateViridis(
                      selectedGana.toolCount / maxInvocations,
                    ),
                  }}
                />
              </div>
            </div>
          </div>
        ) : (
          <div className="flex h-full min-h-[200px] items-center justify-center rounded-2xl border border-border bg-surface p-6">
            <p className="text-center font-mono text-sm text-dim">
              Hover over a segment to see detailed activity metrics
            </p>
          </div>
        )}

        {/* Color Legend */}
        <div className="mt-4 flex items-center gap-2">
          <span className="font-mono text-xs text-dim">Low</span>
          <div className="flex gap-0.5">
            {[0, 0.25, 0.5, 0.75, 1].map((val) => (
              <div
                key={val}
                className="h-3 w-8 rounded-sm"
                style={{
                  backgroundColor: interpolateViridis(val),
                }}
              />
            ))}
          </div>
          <span className="font-mono text-xs text-dim">High</span>
        </div>
      </div>
    </div>
  );
}
