/**
 * WASM Runtime Loader — Initializes WhiteMagic WASM module + SQLite OPFS
 *
 * Loads the compiled Rust core as WebAssembly and provides
 * a React context for accessing WASM functions and browser-side SQLite storage.
 */

"use client";

import { createContext, useContext, useEffect, useState, useCallback, useRef } from "react";
import { getOPFSSQLite, type MemoryRecord, type AssociationRecord, type QueryResult, type DBStats } from "@/lib/sqlite-opfs";
import { getEmbeddingProvider, type EmbeddingResult } from "@/lib/onnx-embedding";
import { useAuth } from "@/lib/auth";

interface WASMRuntime {
  initialized: boolean;
  sqliteReady: boolean;
  embeddingReady: boolean;
  error: string | null;
  version: string;
  // Edge inference
  infer: (query: string) => { answer: string; confidence: number; method: string };
  // Cosine similarity
  cosineSimilarity: (a: number[], b: number[]) => number;
  // Batch cosine
  batchSimilarity: (query: number[], candidates: number[][], topK: number) => Array<{ index: number; score: number }>;
  // Text search
  textSearch: (query: string, texts: string[]) => number[];
  // Stats
  getStats: () => string;
  // SQLite OPFS operations
  insertMemory: (memory: Partial<MemoryRecord>) => Promise<string>;
  queryMemories: (options?: { garden?: string; type?: string; limit?: number; offset?: number; search?: string }) => Promise<QueryResult>;
  getMemory: (id: string) => Promise<MemoryRecord | null>;
  updateMemory: (id: string, updates: Partial<MemoryRecord>) => Promise<void>;
  deleteMemory: (id: string) => Promise<void>;
  insertAssociation: (assoc: Partial<AssociationRecord>) => Promise<string>;
  getAssociations: (memoryId: string) => Promise<AssociationRecord[]>;
  getDBStats: () => Promise<DBStats>;
  getGardenStats: () => Promise<Record<string, number>>;
  // ONNX Embedding operations
  embed: (text: string) => Promise<EmbeddingResult>;
  embedBatch: (texts: string[]) => Promise<EmbeddingResult[]>;
  createMemoryWithEmbedding: (content: string, garden: string, type?: string) => Promise<string>;
  searchBySimilarity: (query: string, topK?: number) => Promise<Array<{ memory: MemoryRecord; score: number }>>;
}

const WASMContext = createContext<WASMRuntime | null>(null);

export function useWASM() {
  const ctx = useContext(WASMContext);
  if (!ctx) throw new Error("useWASM must be used within WASMProvider");
  return ctx;
}

// WASM module types (generated by wasm-bindgen)
interface WASMModule {
  default: (init: string | URL) => Promise<void>;
  EdgeEngine: new () => {
    infer: (query: string) => { answer: () => string; confidence: () => number; method: () => string; needs_cloud: () => boolean; tokens_saved: () => number };
    get_stats: () => string;
  };
  cosine_similarity: (a: string, b: string) => number;
  batch_similarity: (query: string, candidates: string, top_k: number) => string;
  text_search: (query: string, texts: string) => string;
  wasm_version: () => string;
  wasm_ready: () => boolean;
}

export function WASMProvider({ children }: { children: React.ReactNode }) {
  const { user } = useAuth();
  const [initialized, setInitialized] = useState(false);
  const [sqliteReady, setSqliteReady] = useState(false);
  const [embeddingReady, setEmbeddingReady] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [version, setVersion] = useState("loading...");
  const engineRef = useRef<any>(null);
  const sqliteRef = useRef<ReturnType<typeof getOPFSSQLite> | null>(null);
  const embeddingRef = useRef<ReturnType<typeof getEmbeddingProvider> | null>(null);

  const init = useCallback(async () => {
    try {
      // Dynamic import of WASM module (served from /public/wasm/)
      // @ts-ignore - Next.js serves from public/wasm/
      const wasmModule = await import("/wasm/whitemagic_rust.js") as unknown as WASMModule;

      // Initialize WASM
      await wasmModule.default("/wasm/whitemagic_rust_bg.wasm");

      // Create edge engine
      const engine = new wasmModule.EdgeEngine();
      engineRef.current = engine;

      // Get version
      const ver = wasmModule.wasm_version();
      setVersion(ver);

      setInitialized(true);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to initialize WASM");
    }
  }, []);

  useEffect(() => {
    init();
  }, [init]);

  // Initialize SQLite OPFS (user-specific)
  useEffect(() => {
    const sqlite = getOPFSSQLite(user?.id);
    sqliteRef.current = sqlite;
    sqlite.ready().then(() => {
      setSqliteReady(true);
    }).catch(err => {
      console.warn("[WASMProvider] SQLite OPFS init failed:", err);
    });
  }, [user?.id]);

  // Initialize ONNX Embedding
  useEffect(() => {
    const embedding = getEmbeddingProvider();
    embeddingRef.current = embedding;
    embedding.ready().then(() => {
      setEmbeddingReady(true);
    }).catch(err => {
      console.warn("[WASMProvider] ONNX Embedding init failed:", err);
    });
  }, []);

  const infer = useCallback((query: string) => {
    if (!engineRef.current) return { answer: "WASM not initialized", confidence: 0, method: "error" };
    const result = engineRef.current.infer(query);
    return {
      answer: result.answer(),
      confidence: result.confidence(),
      method: result.method(),
    };
  }, []);

  const cosineSimilarity = useCallback((a: number[], b: number[]) => {
    try {
      // @ts-ignore
      const wasmModule = require("/wasm/whitemagic_rust.js") as unknown as WASMModule;
      return wasmModule.cosine_similarity(JSON.stringify(a), JSON.stringify(b));
    } catch {
      return 0;
    }
  }, []);

  const batchSimilarity = useCallback((query: number[], candidates: number[][], topK: number) => {
    try {
      // @ts-ignore
      const wasmModule = require("/wasm/whitemagic_rust.js") as unknown as WASMModule;
      const result = wasmModule.batch_similarity(
        JSON.stringify(query),
        JSON.stringify(candidates),
        topK
      );
      return JSON.parse(result);
    } catch {
      return [];
    }
  }, []);

  const textSearch = useCallback((query: string, texts: string[]) => {
    try {
      // @ts-ignore
      const wasmModule = require("/wasm/whitemagic_rust.js") as unknown as WASMModule;
      const result = wasmModule.text_search(query, JSON.stringify(texts));
      return JSON.parse(result);
    } catch {
      return [];
    }
  }, []);

  const getStats = useCallback(() => {
    if (!engineRef.current) return "{}";
    return engineRef.current.get_stats();
  }, []);

  // SQLite OPFS functions
  const insertMemory = useCallback(async (memory: Partial<MemoryRecord>) => {
    if (!sqliteRef.current) throw new Error("SQLite not initialized");
    return sqliteRef.current.insertMemory(memory);
  }, []);

  const queryMemories = useCallback(async (options?: { garden?: string; type?: string; limit?: number; offset?: number; search?: string }) => {
    if (!sqliteRef.current) return { memories: [], total: 0 };
    return sqliteRef.current.queryMemories(options);
  }, []);

  const getMemory = useCallback(async (id: string) => {
    if (!sqliteRef.current) return null;
    return sqliteRef.current.getMemory(id);
  }, []);

  const updateMemory = useCallback(async (id: string, updates: Partial<MemoryRecord>) => {
    if (!sqliteRef.current) return;
    return sqliteRef.current.updateMemory(id, updates);
  }, []);

  const deleteMemory = useCallback(async (id: string) => {
    if (!sqliteRef.current) return;
    return sqliteRef.current.deleteMemory(id);
  }, []);

  const insertAssociation = useCallback(async (assoc: Partial<AssociationRecord>) => {
    if (!sqliteRef.current) throw new Error("SQLite not initialized");
    return sqliteRef.current.insertAssociation(assoc);
  }, []);

  const getAssociations = useCallback(async (memoryId: string) => {
    if (!sqliteRef.current) return [];
    return sqliteRef.current.getAssociations(memoryId);
  }, []);

  const getDBStats = useCallback(async () => {
    if (!sqliteRef.current) return { memoryCount: 0, associationCount: 0, unsyncedCount: 0, dbSizeBytes: 0 };
    return sqliteRef.current.getStats();
  }, []);

  const getGardenStats = useCallback(async () => {
    if (!sqliteRef.current) return {};
    return sqliteRef.current.getGardenStats();
  }, []);

  // ONNX Embedding functions
  const embed = useCallback(async (text: string) => {
    if (!embeddingRef.current) return { embedding: [], dim: 0, model: "error", latency: 0 };
    return embeddingRef.current.embed(text);
  }, []);

  const embedBatch = useCallback(async (texts: string[]) => {
    if (!embeddingRef.current) return [];
    return embeddingRef.current.embedBatch(texts);
  }, []);

  const createMemoryWithEmbedding = useCallback(async (content: string, garden: string, type = "memory") => {
    if (!sqliteRef.current || !embeddingRef.current) throw new Error("Storage or embedding not initialized");

    // Generate embedding
    const result = await embeddingRef.current.embed(content);

    // Insert memory with embedding
    return sqliteRef.current.insertMemory({
      content,
      garden,
      type,
      embedding: result.embedding,
      metadata: { embedding_model: result.model, embedding_latency: result.latency },
    });
  }, []);

  const searchBySimilarity = useCallback(async (query: string, topK = 10) => {
    if (!sqliteRef.current || !embeddingRef.current) return [];

    // Embed query
    const queryResult = await embeddingRef.current.embed(query);
    const queryEmbedding = queryResult.embedding;

    // Get all memories with embeddings
    const allMemories = await sqliteRef.current.queryMemories({ limit: 1000 });

    // Compute similarity scores
    const { ONNXEmbeddingProvider } = await import("@/lib/onnx-embedding");
    const scored = allMemories.memories
      .filter(m => m.embedding && m.embedding.length > 0)
      .map(m => ({
        memory: m,
        score: ONNXEmbeddingProvider.cosineSimilarity(queryEmbedding, m.embedding!),
      }))
      .sort((a, b) => b.score - a.score)
      .slice(0, topK);

    return scored;
  }, []);

  const value: WASMRuntime = {
    initialized,
    sqliteReady,
    embeddingReady,
    error,
    version,
    infer,
    cosineSimilarity,
    batchSimilarity,
    textSearch,
    getStats,
    insertMemory,
    queryMemories,
    getMemory,
    updateMemory,
    deleteMemory,
    insertAssociation,
    getAssociations,
    getDBStats,
    getGardenStats,
    embed,
    embedBatch,
    createMemoryWithEmbedding,
    searchBySimilarity,
  };

  return (
    <WASMContext.Provider value={value}>
      {children}
    </WASMContext.Provider>
  );
}
