/**
 * GET /api/manifest.json
 *
 * Machine-readable tool manifest for AI agents and MCP clients.
 * Introspected from the live WhiteMagic tool surface.
 *
 * For static generation, run:
 *   python core/scripts/generate_manifest_json.py
 */

export const runtime = "nodejs";
export const revalidate = 300;

export async function GET() {
  // Static manifest generated by core/scripts/generate_manifest_json.py
  // In production this could be dynamically introspected.
  const manifest = {
    schema_version: "1.0.0",
    generated_at: new Date().toISOString(),
    system: {
      name: "WhiteMagic",
      version: "22.2.4",
      url: "https://whitemagic.dev",
      repository: "https://whitemagic.dev",
      license: "MIT",
    },
    counts: {
      authored_tools: 180,
      callable_tools: 490,
      gana_tools: 28,
      dispatch_tools: 462,
      nested_unique_tools: 462,
      by_stability: {
        stable: 28,
        optional: 462,
        experimental: 0,
      },
    },
    endpoints: {
      mcp: { url: "https://whitemagic.dev/mcp", status: "planned" },
      a2a: { url: "https://whitemagic.dev/api/a2a", status: "planned" },
      librarian: { url: "https://whitemagic.dev/api/librarian/chat", status: "live" },
      prescience: { url: "https://whitemagic.dev/api/prescience", status: "planned" },
    },
    note: "Full tool definitions available at /api/manifest.json (static) or via MCP server.",
  };

  return Response.json(manifest, {
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": "public, max-age=300, s-maxage=300",
      "access-control-allow-origin": "*",
    },
  });
}
