//! DIRECTIVE DIR-09: THE RESURRECTED GEN1 ARSENAL
//!
//! Rehabilitates the 50 Essential Gen1 Gems across 6 cognitive clusters into
//! modular, Landlocked plugin packs under Gate 13 Landlock LSM process containment.
//! Eliminates legacy failure modes (unbounded async tasks, memory leaks, shared mutable state).

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum GemCluster {
    EpistemicAndCognitivePhysics,
    CodeIntelligenceAndDeepArchaeology,
    DivinationArchetypesAndNonLinearIntuition,
    SwarmIntelligenceAndConcurrencyPipelines,
    ResilienceGovernanceAndSecurity,
    ContinuousSelfImprovementAndMetaLearning,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Gen1Gem {
    pub id: u32,
    pub name: &'static str,
    pub slug: &'static str,
    pub cluster: GemCluster,
    pub description: &'static str,
    pub pack_id: &'static str,
    pub is_direct_revival: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct PluginPack {
    pub pack_id: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub gem_ids: &'static [u32],
    pub landlock_network_denied: bool,
    pub default_timeout_ms: u64,
    pub max_memory_mb: u64,
}

pub struct Gen1Arsenal;

impl Gen1Arsenal {
    /// Return all 50 Essential Gen1 Gems.
    pub fn all_gems() -> &'static [Gen1Gem] {
        &GEN1_50_GEMS
    }

    /// Return all 12 Landlocked Plugin Packs.
    pub fn all_plugin_packs() -> &'static [PluginPack] {
        &GEN1_PLUGIN_PACKS
    }

    /// Retrieve a gem by its 1-indexed ID (1..=50).
    pub fn get_gem(id: u32) -> Option<&'static Gen1Gem> {
        GEN1_50_GEMS.iter().find(|g| g.id == id)
    }

    /// Retrieve all gems assigned to a specific plugin pack.
    pub fn gems_for_pack(pack_id: &str) -> Vec<&'static Gen1Gem> {
        GEN1_50_GEMS.iter().filter(|g| g.pack_id == pack_id).collect()
    }
}

pub const GEN1_50_GEMS: [Gen1Gem; 50] = [
    // Cluster A: Epistemic & Cognitive Physics
    Gen1Gem {
        id: 1,
        name: "Dynamic Motif Spectrometer",
        slug: "dynamic_motif_spectrometer",
        cluster: GemCluster::EpistemicAndCognitivePhysics,
        description: "Spectral analysis and attractor mapping of recurring conversation motifs",
        pack_id: "pack_spectroscopy",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 2,
        name: "Attractor Basin Citta",
        slug: "attractor_basin_citta",
        cluster: GemCluster::EpistemicAndCognitivePhysics,
        description: "Energy-landscape attractor mapping for agent state convergence",
        pack_id: "pack_spectroscopy",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 3,
        name: "Bicameral Dialectic Arbitration",
        slug: "bicameral_dialectic_arbitration",
        cluster: GemCluster::EpistemicAndCognitivePhysics,
        description: "Dual-model thesis-antithesis synthesis with zero hallucinated consensus",
        pack_id: "pack_epistemic_prescience",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 4,
        name: "Conformal Diamonds",
        slug: "conformal_diamonds",
        cluster: GemCluster::EpistemicAndCognitivePhysics,
        description: "Mathematically rigorous conformal prediction intervals over tool outputs",
        pack_id: "pack_epistemic_prescience",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 5,
        name: "HRR Tensor Binding",
        slug: "hrr_tensor_binding",
        cluster: GemCluster::EpistemicAndCognitivePhysics,
        description: "Holographic Reduced Representations via circular convolution",
        pack_id: "pack_quantum_hrr",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 6,
        name: "qFHRR 8-Bit Filtering",
        slug: "qfhrr_8bit_filtering",
        cluster: GemCluster::EpistemicAndCognitivePhysics,
        description: "Quantized Fourier HRR with sub-microsecond SIMD Hamming search",
        pack_id: "pack_quantum_hrr",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 7,
        name: "Multi-Signal NeuroScore Decay",
        slug: "multisignal_neuroscore_decay",
        cluster: GemCluster::EpistemicAndCognitivePhysics,
        description: "Half-life temporal decay with reinforcement on human-intervened recalls",
        pack_id: "pack_mindful_metabolism",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 8,
        name: "Spreading Activation Field",
        slug: "spreading_activation_field",
        cluster: GemCluster::EpistemicAndCognitivePhysics,
        description: "Associative diffusion through high-dimensional conceptual graph edges",
        pack_id: "pack_living_graph",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 9,
        name: "Quantum Grover Search Amplification",
        slug: "quantum_grover_search",
        cluster: GemCluster::EpistemicAndCognitivePhysics,
        description: "Heuristic probability amplitude amplification for high-entropy retrieval",
        pack_id: "pack_quantum_hrr",
        is_direct_revival: false,
    },
    Gen1Gem {
        id: 10,
        name: "Pareto Parsimony Gate",
        slug: "pareto_parsimony_gate",
        cluster: GemCluster::EpistemicAndCognitivePhysics,
        description: "Information-theoretic pruning of overly complex tool argument payloads",
        pack_id: "pack_spectroscopy",
        is_direct_revival: true,
    },

    // Cluster B: Code Intelligence & Deep Archaeology
    Gen1Gem {
        id: 11,
        name: "STRATA Truth-Drift Detector",
        slug: "strata_truth_drift_detector",
        cluster: GemCluster::CodeIntelligenceAndDeepArchaeology,
        description: "Cross-checks codebase reality against architectural specifications to catch documentation drift",
        pack_id: "pack_code_archaeology",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 12,
        name: "Living Code Graph",
        slug: "living_code_graph",
        cluster: GemCluster::CodeIntelligenceAndDeepArchaeology,
        description: "Dynamic call-graph topology updated synchronously on file modifications",
        pack_id: "pack_code_archaeology",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 13,
        name: "Rabbit Hole Recursive Explorer",
        slug: "rabbit_hole_recursive_explorer",
        cluster: GemCluster::CodeIntelligenceAndDeepArchaeology,
        description: "Traverses unfamiliar code tokens down to substrate kernel interfaces",
        pack_id: "pack_research_rabbithole",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 14,
        name: "Action Skeleton Synthesizer",
        slug: "action_skeleton_synthesizer",
        cluster: GemCluster::CodeIntelligenceAndDeepArchaeology,
        description: "Compiles recurring tool call sequences into zero-overhead parametric recipes",
        pack_id: "pack_action_skeletons",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 15,
        name: "Friction-to-Regression Test Compiler",
        slug: "friction_to_regression_compiler",
        cluster: GemCluster::CodeIntelligenceAndDeepArchaeology,
        description: "Transforms user corrections and compiler panics into permanent Rust unit tests",
        pack_id: "pack_adversarial_redteam",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 16,
        name: "Code Genome AST Sequencer",
        slug: "code_genome_ast_sequencer",
        cluster: GemCluster::CodeIntelligenceAndDeepArchaeology,
        description: "Analyzes code structural ancestry and detects duplicated logic across crates",
        pack_id: "pack_code_archaeology",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 17,
        name: "Zero-Egress AST Guard",
        slug: "zero_egress_ast_guard",
        cluster: GemCluster::CodeIntelligenceAndDeepArchaeology,
        description: "Static inspection preventing network socket creation in unratified code blocks",
        pack_id: "pack_violet_security",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 18,
        name: "Hierarchical Sub-Clustering",
        slug: "hierarchical_sub_clustering",
        cluster: GemCluster::CodeIntelligenceAndDeepArchaeology,
        description: "Decomposes monolithic crates into modular decoupled sub-domains",
        pack_id: "pack_code_archaeology",
        is_direct_revival: true,
    },

    // Cluster C: Divination Archetypes & Non-Linear Intuition
    Gen1Gem {
        id: 19,
        name: "64 Hexagram Vector Field",
        slug: "64_hexagram_vector_field",
        cluster: GemCluster::DivinationArchetypesAndNonLinearIntuition,
        description: "Maps problem topologies to 64 archetypal change patterns for lateral insight",
        pack_id: "pack_divination_archetypes",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 20,
        name: "28 Lunar Mansion Xiu Biases",
        slug: "28_lunar_mansion_xiu_biases",
        cluster: GemCluster::DivinationArchetypesAndNonLinearIntuition,
        description: "28 archetypal perspectives assigned to subagents for cognitive diversity",
        pack_id: "pack_divination_archetypes",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 21,
        name: "Wu Xing Balancing",
        slug: "wu_xing_balancing",
        cluster: GemCluster::DivinationArchetypesAndNonLinearIntuition,
        description: "Five-element phase transitions (Wood, Fire, Earth, Metal, Water) for system metabolism",
        pack_id: "pack_divination_archetypes",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 22,
        name: "Zodiac Council 12-Archetype Debate",
        slug: "zodiac_council_12_archetype_debate",
        cluster: GemCluster::DivinationArchetypesAndNonLinearIntuition,
        description: "Multi-perspective dialetical deliberation framework across 12 cognitive archetypes",
        pack_id: "pack_divination_archetypes",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 23,
        name: "Tarot Transformation Operators",
        slug: "tarot_transformation_operators",
        cluster: GemCluster::DivinationArchetypesAndNonLinearIntuition,
        description: "Major arcana archetypes used for lateral unblocking during deadlocks",
        pack_id: "pack_divination_archetypes",
        is_direct_revival: false,
    },
    Gen1Gem {
        id: 24,
        name: "Yijing Dynamic Line Mutation",
        slug: "yijing_dynamic_line_mutation",
        cluster: GemCluster::DivinationArchetypesAndNonLinearIntuition,
        description: "Tracks changing lines to project systemic trajectory and unintended consequences",
        pack_id: "pack_divination_archetypes",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 25,
        name: "Precessional Great Year Modulation",
        slug: "precessional_great_year_modulation",
        cluster: GemCluster::DivinationArchetypesAndNonLinearIntuition,
        description: "Deep-time historical epoch framing for long-range software architecture",
        pack_id: "pack_divination_archetypes",
        is_direct_revival: false,
    },
    Gen1Gem {
        id: 26,
        name: "Alchemical Stage Quadrants",
        slug: "alchemical_stage_quadrants",
        cluster: GemCluster::DivinationArchetypesAndNonLinearIntuition,
        description: "Nigredo (decomposition), Albedo (purification), Citrinitas (transmutation), Rubedo (integration)",
        pack_id: "pack_divination_archetypes",
        is_direct_revival: true,
    },

    // Cluster D: Swarm Intelligence & Concurrency Pipelines
    Gen1Gem {
        id: 27,
        name: "Tokio Clone Army Scheduler",
        slug: "tokio_clone_army_scheduler",
        cluster: GemCluster::SwarmIntelligenceAndConcurrencyPipelines,
        description: "High-throughput asynchronous worker pool with deterministic pre-emption",
        pack_id: "pack_action_skeletons",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 28,
        name: "Vanguard Recon Pipeline",
        slug: "vanguard_recon_pipeline",
        cluster: GemCluster::SwarmIntelligenceAndConcurrencyPipelines,
        description: "Fast read-only subagents dispatched for rapid telemetry gathering",
        pack_id: "pack_research_rabbithole",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 29,
        name: "Sentry Integrity Auditor",
        slug: "sentry_integrity_auditor",
        cluster: GemCluster::SwarmIntelligenceAndConcurrencyPipelines,
        description: "Continuous runtime invariant and memory-safety validator",
        pack_id: "pack_violet_security",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 30,
        name: "Alchemist Knowledge Transmutation",
        slug: "alchemist_knowledge_transmutation",
        cluster: GemCluster::SwarmIntelligenceAndConcurrencyPipelines,
        description: "Distills thousands of log lines into concise causal graph edge weights",
        pack_id: "pack_narrative_continuity",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 31,
        name: "Cartographer Semantic Disperser",
        slug: "cartographer_semantic_disperser",
        cluster: GemCluster::SwarmIntelligenceAndConcurrencyPipelines,
        description: "Visualizes and balances memory partition topology across crates",
        pack_id: "pack_living_graph",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 32,
        name: "Decoupled Linda Tuple Space",
        slug: "decoupled_linda_tuple_space",
        cluster: GemCluster::SwarmIntelligenceAndConcurrencyPipelines,
        description: "Sub-microsecond associative coordination over POSIX /dev/shm",
        pack_id: "pack_action_skeletons",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 33,
        name: "Digital Stigmergy Pheromone Field",
        slug: "digital_stigmergy_pheromone_field",
        cluster: GemCluster::SwarmIntelligenceAndConcurrencyPipelines,
        description: "Exponentially decaying pheromones guiding autonomous swarm task selection",
        pack_id: "pack_spectroscopy",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 34,
        name: "Bicameral Consensus Tree Engine",
        slug: "bicameral_consensus_tree_engine",
        cluster: GemCluster::SwarmIntelligenceAndConcurrencyPipelines,
        description: "Branching decision tree verified against empirical unit test outcomes",
        pack_id: "pack_epistemic_prescience",
        is_direct_revival: true,
    },

    // Cluster E: Resilience, Governance & Security
    Gen1Gem {
        id: 35,
        name: "Violet Scope Tokens",
        slug: "violet_scope_tokens",
        cluster: GemCluster::ResilienceGovernanceAndSecurity,
        description: "Cryptographically signed capability tokens restricting subagent execution breadth",
        pack_id: "pack_violet_security",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 36,
        name: "Model Weights Signer",
        slug: "model_weights_signer",
        cluster: GemCluster::ResilienceGovernanceAndSecurity,
        description: "Ed25519 signature verification on all local safetensors checkpoints",
        pack_id: "pack_violet_security",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 37,
        name: "Homeostatic Ladder Reflex",
        slug: "homeostatic_ladder_reflex",
        cluster: GemCluster::ResilienceGovernanceAndSecurity,
        description: "Proactive resource back-pressure shedding before OOM killer activation",
        pack_id: "pack_mindful_metabolism",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 38,
        name: "Multi-Signal Circuit Breaker",
        slug: "multisignal_circuit_breaker",
        cluster: GemCluster::ResilienceGovernanceAndSecurity,
        description: "Trips fail-closed on repeated tool execution failures or memory leaks",
        pack_id: "pack_violet_security",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 39,
        name: "Pre-Execution Blast Radius Simulator",
        slug: "preexecution_blast_radius_simulator",
        cluster: GemCluster::ResilienceGovernanceAndSecurity,
        description: "Simulates filesystem mutations in ephemeral memory before applying to disk",
        pack_id: "pack_adversarial_redteam",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 40,
        name: "Yama Resource Governor",
        slug: "yama_resource_governor",
        cluster: GemCluster::ResilienceGovernanceAndSecurity,
        description: "Strict CPU and RSS memory limits enforced via setrlimit on child processes",
        pack_id: "pack_violet_security",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 41,
        name: "Cold Galaxy Archival Rotator",
        slug: "cold_galaxy_archival_rotator",
        cluster: GemCluster::ResilienceGovernanceAndSecurity,
        description: "Moves stagnant historical files to compressed SD card storage without NVMe footprint",
        pack_id: "pack_mindful_metabolism",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 42,
        name: "Nullifier Two-Phase Commit",
        slug: "nullifier_two_phase_commit",
        cluster: GemCluster::ResilienceGovernanceAndSecurity,
        description: "Cryptographic nullifiers preventing duplicate execution of causal tickets",
        pack_id: "pack_violet_security",
        is_direct_revival: true,
    },

    // Cluster F: Continuous Self-Improvement & Meta-Learning
    Gen1Gem {
        id: 43,
        name: "Outward Spiral RSI Engine",
        slug: "outward_spiral_rsi_engine",
        cluster: GemCluster::ContinuousSelfImprovementAndMetaLearning,
        description: "Expands agent autonomy strictly along verified constitutional closures",
        pack_id: "pack_adversarial_redteam",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 44,
        name: "Autonomous Dream Cycle Compactor",
        slug: "autonomous_dream_cycle_compactor",
        cluster: GemCluster::ContinuousSelfImprovementAndMetaLearning,
        description: "Nightly background compaction transforming raw logs into durable episodic attractors",
        pack_id: "pack_mindful_metabolism",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 45,
        name: "Brier-Murphy Calibration Ledger",
        slug: "brier_murphy_calibration_ledger",
        cluster: GemCluster::ContinuousSelfImprovementAndMetaLearning,
        description: "Scored track record of all agent predictions and architectural estimates",
        pack_id: "pack_epistemic_prescience",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 46,
        name: "Gana Co-Usage Drift Analyzer",
        slug: "gana_cousage_drift_analyzer",
        cluster: GemCluster::ContinuousSelfImprovementAndMetaLearning,
        description: "Identifies underutilized or overutilized cognitive roles to balance multi-agent swarms",
        pack_id: "pack_spectroscopy",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 47,
        name: "Proactive Energy-Depletion Dream Scheduler",
        slug: "proactive_dream_scheduler",
        cluster: GemCluster::ContinuousSelfImprovementAndMetaLearning,
        description: "Initiates sleep consolidation automatically after high-friction tasks",
        pack_id: "pack_mindful_metabolism",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 48,
        name: "Non-Loss Distillation Pipeline",
        slug: "non_loss_distillation_pipeline",
        cluster: GemCluster::ContinuousSelfImprovementAndMetaLearning,
        description: "Preserves critical direct quotes and breakthrough invariants during context compression",
        pack_id: "pack_narrative_continuity",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 49,
        name: "Salience-Aware Homeostasis Sync",
        slug: "salience_aware_homeostasis_sync",
        cluster: GemCluster::ContinuousSelfImprovementAndMetaLearning,
        description: "Balances exploration versus exploitation across all active agent sub-processes",
        pack_id: "pack_mindful_metabolism",
        is_direct_revival: true,
    },
    Gen1Gem {
        id: 50,
        name: "Universal Skill Recipe Compiler",
        slug: "universal_skill_recipe_compiler",
        cluster: GemCluster::ContinuousSelfImprovementAndMetaLearning,
        description: "Exports verified multi-step interaction workflows as portable markdown skills",
        pack_id: "pack_action_skeletons",
        is_direct_revival: true,
    },
];

pub const GEN1_PLUGIN_PACKS: [PluginPack; 12] = [
    PluginPack {
        pack_id: "pack_spectroscopy",
        name: "Dynamic Motif Spectroscopy Pack",
        description: "Spectral analysis, attractor basins, and stigmergy monitoring",
        gem_ids: &[1, 2, 10, 33, 46],
        landlock_network_denied: true,
        default_timeout_ms: 5000,
        max_memory_mb: 128,
    },
    PluginPack {
        pack_id: "pack_code_archaeology",
        name: "Living Code Archaeology Pack",
        description: "STRATA truth drift detection, AST genome sequencing, living code graph",
        gem_ids: &[11, 12, 16, 18],
        landlock_network_denied: true,
        default_timeout_ms: 10000,
        max_memory_mb: 256,
    },
    PluginPack {
        pack_id: "pack_divination_archetypes",
        name: "Divination Archetypes & Non-Linear Intuition Pack",
        description: "64 Hexagrams, 28 Xiu, Wu Xing, and 12-Archetype Dialectic Debate",
        gem_ids: &[19, 20, 21, 22, 23, 24, 25, 26],
        landlock_network_denied: true,
        default_timeout_ms: 3000,
        max_memory_mb: 64,
    },
    PluginPack {
        pack_id: "pack_action_skeletons",
        name: "Action Skeletons & Sub-Symbolic Concurrency Pack",
        description: "Parametric recipes, Linda tuple spaces, clone army scheduler",
        gem_ids: &[14, 27, 32, 50],
        landlock_network_denied: true,
        default_timeout_ms: 5000,
        max_memory_mb: 128,
    },
    PluginPack {
        pack_id: "pack_living_graph",
        name: "Living Graph & Semantic Dispersal Pack",
        description: "Spreading activation field and semantic cartography",
        gem_ids: &[8, 31],
        landlock_network_denied: true,
        default_timeout_ms: 5000,
        max_memory_mb: 128,
    },
    PluginPack {
        pack_id: "pack_violet_security",
        name: "Violet Scope & Sovereign Containment Pack",
        description: "Scope tokens, weight signing, circuit breakers, Yama governor, and two-phase nullifiers",
        gem_ids: &[17, 29, 35, 36, 38, 40, 42],
        landlock_network_denied: true,
        default_timeout_ms: 3000,
        max_memory_mb: 64,
    },
    PluginPack {
        pack_id: "pack_epistemic_prescience",
        name: "Epistemic Prescience & Calibration Pack",
        description: "Bicameral arbitration, conformal diamonds, and Brier-Murphy calibration ledger",
        gem_ids: &[3, 4, 34, 45],
        landlock_network_denied: true,
        default_timeout_ms: 5000,
        max_memory_mb: 128,
    },
    PluginPack {
        pack_id: "pack_quantum_hrr",
        name: "Quantum HRR & Holographic Binding Pack",
        description: "Circular convolution, qFHRR 8-bit quantization, and Grover search amplification",
        gem_ids: &[5, 6, 9],
        landlock_network_denied: true,
        default_timeout_ms: 5000,
        max_memory_mb: 128,
    },
    PluginPack {
        pack_id: "pack_adversarial_redteam",
        name: "Adversarial Red-Team & Blast Radius Pack",
        description: "Friction-to-regression tests, blast radius simulation, outward spiral RSI",
        gem_ids: &[15, 39, 43],
        landlock_network_denied: true,
        default_timeout_ms: 10000,
        max_memory_mb: 256,
    },
    PluginPack {
        pack_id: "pack_research_rabbithole",
        name: "Vanguard Recon & Rabbit Hole Explorer Pack",
        description: "Rapid telemetry gathering and recursive token exploration",
        gem_ids: &[13, 28],
        landlock_network_denied: true,
        default_timeout_ms: 8000,
        max_memory_mb: 128,
    },
    PluginPack {
        pack_id: "pack_mindful_metabolism",
        name: "Mindful Metabolism & Dream Consolidator Pack",
        description: "NeuroScore decay, homeostatic ladder reflex, cold galaxy archival, and sleep compactors",
        gem_ids: &[7, 37, 41, 44, 47, 49],
        landlock_network_denied: true,
        default_timeout_ms: 8000,
        max_memory_mb: 128,
    },
    PluginPack {
        pack_id: "pack_narrative_continuity",
        name: "Narrative Continuity & Non-Loss Distillation Pack",
        description: "Quote anchoring, knowledge transmutation, and lossless memory distillation",
        gem_ids: &[30, 48],
        landlock_network_denied: true,
        default_timeout_ms: 5000,
        max_memory_mb: 128,
    },
];
