"""Slice 4 — Diagnostic inventory of all direct UnifiedMemory.backend consumers.

This test file serves as a living inventory of every module that directly
accesses UnifiedMemory.backend (the raw SQLite backend). Each consumer
must be migrated to the MemoryBackend protocol facade in Phase 2.

The test validates the inventory is complete by checking that the known
set of consumers matches the actual set found by grepping the codebase.
"""
from __future__ import annotations

import importlib
from pathlib import Path

import pytest

# Known consumers of UnifiedMemory.backend — these are the modules that
# directly access .backend on a UnifiedMemory instance.
# This list was generated by grepping for `\.backend\b` in the whitemagic/ tree.
KNOWN_BACKEND_CONSUMERS: list[str] = [
    "whitemagic.core.memory.galactic_telepathy",
    "whitemagic.core.memory.miners",
    "whitemagic.core.memory.association_miner",
    "whitemagic.core.memory.galaxy_manager",
    "whitemagic.core.memory.galactic_map",
    "whitemagic.cli.holo_commands",
    "whitemagic.core.intelligence.phylogenetics.GenomeTracker",
    "whitemagic.core.intelligence.phylogenetics.genome_tracker",
    "whitemagic.core.memory.phylogenetics",
    "whitemagic.core.memory.unified",
    "whitemagic.cli.commands.diagnostics_commands",
    "whitemagic.core.dreaming.dream_cycle",
    "whitemagic.core.memory.consolidation",
    "whitemagic.core.memory.manager",
    "whitemagic.tools.spatial_navigator",
    "whitemagic.core.memory.causal_miner",
    "whitemagic.core.memory.constellations",
    "whitemagic.core.memory.graph_engine",
    "whitemagic.core.memory.lifecycle",
    "whitemagic.core.consciousness.possibility_explorer",
    "whitemagic.core.consciousness.lifecycle",
    "whitemagic.core.evolution.research_dag",
    "whitemagic.core.memory.akashic",
    "whitemagic.core.memory.core",
    "whitemagic.core.memory.galaxy_router",
    "whitemagic.core.memory.graph_walker",
    "whitemagic.core.memory.hybrid_fusion",
    "whitemagic.inference.router",
    "whitemagic.interfaces.chat",
    "whitemagic.oms.manager",
    "whitemagic.tools.gnosis",
    "whitemagic.tools.handlers.pattern_engines",
    "whitemagic.tools.middleware",
    "whitemagic.core.consciousness.simulation_orchestrator",
    "whitemagic.core.dreaming.narrative_compressor",
    "whitemagic.core.evolution.autoswarm",
    "whitemagic.core.governance.maturity_gates",
    "whitemagic.core.intelligence.entity_extractor",
    "whitemagic.core.intelligence.foresight_engine",
    "whitemagic.core.memory.backends.galaxy_router",
    "whitemagic.core.memory.bridge_synthesizer",
    "whitemagic.core.memory.entropy_scorer",
    "whitemagic.core.memory.graph",
    "whitemagic.core.memory.mindful_forgetting",
    "whitemagic.core.memory.umap_projection",
    "whitemagic.dharma",
    "whitemagic.harmony.homeostatic_loop",
    "whitemagic.inference.llama_cpp",
    "whitemagic.tools.dispatch_core",
    "whitemagic.tools.handlers.export_import",
    "whitemagic.tools.handlers.memory",
    "whitemagic.tools.handlers.misc",
    "whitemagic.tools.introspection",
    "whitemagic.tools.speculative_prefetch",
    "whitemagic.tools.strata.context",
    "whitemagic.core.memory.backends.protocol",
    "whitemagic.core.storage.polyglot_db",
    "whitemagic.interfaces.unified_tui",
    "whitemagic.ops.replay",
    "whitemagic.tools.handlers.llama_tools",
    "whitemagic.tools.handlers.wm_read",
    "whitemagic.core.consciousness.council",
    "whitemagic.core.memory.backends.duckdb_backend",
    "whitemagic.core.memory.backends.postgres_backend",
]


class TestBackendInventory:
    """Validate the inventory of direct .backend consumers is complete."""

    @pytest.fixture
    def actual_backend_consumers(self) -> set[str]:
        """Scan the codebase for files containing `.backend` references."""
        whitemagic_root = Path(__file__).parent.parent.parent.parent / "whitemagic"
        consumers: set[str] = set()
        for py_file in whitemagic_root.rglob("*.py"):
            try:
                content = py_file.read_text(encoding="utf-8")
            except (OSError, UnicodeDecodeError):
                continue
            if ".backend" in content:
                # Convert file path to module name
                rel = py_file.relative_to(whitemagic_root.parent)
                module = str(rel).replace("/", ".").replace("\\", ".")
                if module.endswith(".py"):
                    module = module[:-3]
                # Skip __init__ for cleaner grouping
                if module.endswith(".__init__"):
                    module = module[:-9]
                consumers.add(module)
        return consumers

    def test_known_consumers_match_actual(self, actual_backend_consumers):
        """The known list must cover all actual .backend consumers exactly."""
        known_set = set(KNOWN_BACKEND_CONSUMERS)
        missing = actual_backend_consumers - known_set
        # Print what's missing for debugging
        if missing:
            print("\nNew .backend consumers found not in KNOWN_BACKEND_CONSUMERS:")
            for m in sorted(missing):
                print(f"  - {m}")
        assert len(missing) == 0, (
            f"{len(missing)} new .backend consumers found that are not in the "
            f"known inventory. Add them to KNOWN_BACKEND_CONSUMERS."
        )

    def test_known_consumers_are_importable(self):
        """Every known consumer module must be importable."""
        failures = []
        for module_name in KNOWN_BACKEND_CONSUMERS:
            try:
                importlib.import_module(module_name)
            except (ImportError, ModuleNotFoundError) as e:
                failures.append(f"{module_name}: {e}")
        assert not failures, f"Failed to import known consumers: {failures}"

    def test_consumer_count_no_shrinkage(self):
        """The inventory must not shrink — consumers are only added, never removed."""
        BASELINE_COUNT = 64  # No-shrink baseline (2026-07-19)
        assert len(KNOWN_BACKEND_CONSUMERS) >= BASELINE_COUNT, (
            f"KNOWN_BACKEND_CONSUMERS shrank from baseline {BASELINE_COUNT} to "
            f"{len(KNOWN_BACKEND_CONSUMERS)}. If consumers were removed, update BASELINE_COUNT."
        )

    def test_inventory_documented(self):
        """The inventory list must be non-empty and contain real module paths."""
        assert len(KNOWN_BACKEND_CONSUMERS) > 0
        for name in KNOWN_BACKEND_CONSUMERS:
            assert name.startswith("whitemagic."), f"Invalid module name: {name}"
            # Allow top-level modules (e.g. whitemagic.dharma) — at least 2 segments
            parts = name.split(".")
            assert len(parts) >= 2, f"Module name too shallow: {name}"
