# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mesh_pb2 as mesh__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mesh_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MeshServiceStub:
    """── Existing Mesh Service ──────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BroadcastSignal = channel.unary_unary(
                '/whitemagic.MeshService/BroadcastSignal',
                request_serializer=mesh__pb2.SignalRequest.SerializeToString,
                response_deserializer=mesh__pb2.SignalResponse.FromString,
                _registered_method=True)
        self.BroadcastHologram = channel.unary_unary(
                '/whitemagic.MeshService/BroadcastHologram',
                request_serializer=mesh__pb2.HolographicSignal.SerializeToString,
                response_deserializer=mesh__pb2.SignalResponse.FromString,
                _registered_method=True)
        self.DiscoverPeers = channel.unary_unary(
                '/whitemagic.MeshService/DiscoverPeers',
                request_serializer=mesh__pb2.DiscoveryRequest.SerializeToString,
                response_deserializer=mesh__pb2.DiscoveryResponse.FromString,
                _registered_method=True)


class MeshServiceServicer:
    """── Existing Mesh Service ──────────────────────────────────────────

    """

    def BroadcastSignal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BroadcastHologram(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverPeers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeshServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BroadcastSignal': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastSignal,
                    request_deserializer=mesh__pb2.SignalRequest.FromString,
                    response_serializer=mesh__pb2.SignalResponse.SerializeToString,
            ),
            'BroadcastHologram': grpc.unary_unary_rpc_method_handler(
                    servicer.BroadcastHologram,
                    request_deserializer=mesh__pb2.HolographicSignal.FromString,
                    response_serializer=mesh__pb2.SignalResponse.SerializeToString,
            ),
            'DiscoverPeers': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverPeers,
                    request_deserializer=mesh__pb2.DiscoveryRequest.FromString,
                    response_serializer=mesh__pb2.DiscoveryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'whitemagic.MeshService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('whitemagic.MeshService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeshService:
    """── Existing Mesh Service ──────────────────────────────────────────

    """

    @staticmethod
    def BroadcastSignal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/whitemagic.MeshService/BroadcastSignal',
            mesh__pb2.SignalRequest.SerializeToString,
            mesh__pb2.SignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BroadcastHologram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/whitemagic.MeshService/BroadcastHologram',
            mesh__pb2.HolographicSignal.SerializeToString,
            mesh__pb2.SignalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscoverPeers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/whitemagic.MeshService/DiscoverPeers',
            mesh__pb2.DiscoveryRequest.SerializeToString,
            mesh__pb2.DiscoveryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CognitiveServiceStub:
    """── Cognitive Service (v24) ────────────────────────────────────────

    The CognitiveService extends the mesh node into a full cognitive
    gateway.  It exposes tool dispatch, citta streaming, session
    management, dream events, and telemetry to TUI / IDE / PWA clients
    over gRPC (Unix domain socket for local, TCP for remote).

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallTool = channel.unary_stream(
                '/whitemagic.CognitiveService/CallTool',
                request_serializer=mesh__pb2.ToolRequest.SerializeToString,
                response_deserializer=mesh__pb2.ToolEvent.FromString,
                _registered_method=True)
        self.CittaStream = channel.unary_stream(
                '/whitemagic.CognitiveService/CittaStream',
                request_serializer=mesh__pb2.CittaSubscribe.SerializeToString,
                response_deserializer=mesh__pb2.CittaMoment.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/whitemagic.CognitiveService/CreateSession',
                request_serializer=mesh__pb2.SessionRequest.SerializeToString,
                response_deserializer=mesh__pb2.SessionResponse.FromString,
                _registered_method=True)
        self.ResumeSession = channel.unary_stream(
                '/whitemagic.CognitiveService/ResumeSession',
                request_serializer=mesh__pb2.SessionResume.SerializeToString,
                response_deserializer=mesh__pb2.CittaMoment.FromString,
                _registered_method=True)
        self.DreamEvents = channel.unary_stream(
                '/whitemagic.CognitiveService/DreamEvents',
                request_serializer=mesh__pb2.DreamSubscribe.SerializeToString,
                response_deserializer=mesh__pb2.DreamEvent.FromString,
                _registered_method=True)
        self.Telemetry = channel.unary_stream(
                '/whitemagic.CognitiveService/Telemetry',
                request_serializer=mesh__pb2.TelemetryRequest.SerializeToString,
                response_deserializer=mesh__pb2.TelemetrySnapshot.FromString,
                _registered_method=True)
        self.DaemonStatus = channel.unary_unary(
                '/whitemagic.CognitiveService/DaemonStatus',
                request_serializer=mesh__pb2.StatusRequest.SerializeToString,
                response_deserializer=mesh__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.DaemonShutdown = channel.unary_unary(
                '/whitemagic.CognitiveService/DaemonShutdown',
                request_serializer=mesh__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=mesh__pb2.StatusResponse.FromString,
                _registered_method=True)


class CognitiveServiceServicer:
    """── Cognitive Service (v24) ────────────────────────────────────────

    The CognitiveService extends the mesh node into a full cognitive
    gateway.  It exposes tool dispatch, citta streaming, session
    management, dream events, and telemetry to TUI / IDE / PWA clients
    over gRPC (Unix domain socket for local, TCP for remote).

    """

    def CallTool(self, request, context):
        """Tool dispatch — stream results back to caller
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CittaStream(self, request, context):
        """Citta stream — continuous consciousness updates (subscribe)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Session management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DreamEvents(self, request, context):
        """Dream cycle events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Telemetry(self, request, context):
        """System telemetry — periodic snapshots
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DaemonStatus(self, request, context):
        """Daemon control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DaemonShutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CognitiveServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallTool': grpc.unary_stream_rpc_method_handler(
                    servicer.CallTool,
                    request_deserializer=mesh__pb2.ToolRequest.FromString,
                    response_serializer=mesh__pb2.ToolEvent.SerializeToString,
            ),
            'CittaStream': grpc.unary_stream_rpc_method_handler(
                    servicer.CittaStream,
                    request_deserializer=mesh__pb2.CittaSubscribe.FromString,
                    response_serializer=mesh__pb2.CittaMoment.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=mesh__pb2.SessionRequest.FromString,
                    response_serializer=mesh__pb2.SessionResponse.SerializeToString,
            ),
            'ResumeSession': grpc.unary_stream_rpc_method_handler(
                    servicer.ResumeSession,
                    request_deserializer=mesh__pb2.SessionResume.FromString,
                    response_serializer=mesh__pb2.CittaMoment.SerializeToString,
            ),
            'DreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.DreamEvents,
                    request_deserializer=mesh__pb2.DreamSubscribe.FromString,
                    response_serializer=mesh__pb2.DreamEvent.SerializeToString,
            ),
            'Telemetry': grpc.unary_stream_rpc_method_handler(
                    servicer.Telemetry,
                    request_deserializer=mesh__pb2.TelemetryRequest.FromString,
                    response_serializer=mesh__pb2.TelemetrySnapshot.SerializeToString,
            ),
            'DaemonStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.DaemonStatus,
                    request_deserializer=mesh__pb2.StatusRequest.FromString,
                    response_serializer=mesh__pb2.StatusResponse.SerializeToString,
            ),
            'DaemonShutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.DaemonShutdown,
                    request_deserializer=mesh__pb2.ShutdownRequest.FromString,
                    response_serializer=mesh__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'whitemagic.CognitiveService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('whitemagic.CognitiveService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CognitiveService:
    """── Cognitive Service (v24) ────────────────────────────────────────

    The CognitiveService extends the mesh node into a full cognitive
    gateway.  It exposes tool dispatch, citta streaming, session
    management, dream events, and telemetry to TUI / IDE / PWA clients
    over gRPC (Unix domain socket for local, TCP for remote).

    """

    @staticmethod
    def CallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/whitemagic.CognitiveService/CallTool',
            mesh__pb2.ToolRequest.SerializeToString,
            mesh__pb2.ToolEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CittaStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/whitemagic.CognitiveService/CittaStream',
            mesh__pb2.CittaSubscribe.SerializeToString,
            mesh__pb2.CittaMoment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/whitemagic.CognitiveService/CreateSession',
            mesh__pb2.SessionRequest.SerializeToString,
            mesh__pb2.SessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/whitemagic.CognitiveService/ResumeSession',
            mesh__pb2.SessionResume.SerializeToString,
            mesh__pb2.CittaMoment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/whitemagic.CognitiveService/DreamEvents',
            mesh__pb2.DreamSubscribe.SerializeToString,
            mesh__pb2.DreamEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Telemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/whitemagic.CognitiveService/Telemetry',
            mesh__pb2.TelemetryRequest.SerializeToString,
            mesh__pb2.TelemetrySnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DaemonStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/whitemagic.CognitiveService/DaemonStatus',
            mesh__pb2.StatusRequest.SerializeToString,
            mesh__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DaemonShutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/whitemagic.CognitiveService/DaemonShutdown',
            mesh__pb2.ShutdownRequest.SerializeToString,
            mesh__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
