"""Universal Token Tracker — P5 Integration.

Wraps the dispatch pipeline to track token usage and savings for ALL
tool calls, not just inference. Integrates with GreenScore telemetry
to provide a complete picture of token economics.

Tracks:
  - Input tokens: tokens in the tool call arguments
  - Output tokens: tokens in the tool result
  - Saved tokens: tokens avoided via local resolution, caching, compression
  - Locality: where the computation happened (edge/local/cloud)

This middleware runs AFTER the inference router and observability middleware,
recording the token flow for every tool call that passes through the pipeline.

Usage:
    # Automatically wired into dispatch pipeline via middleware
    # No manual calls needed — just check the report:
    from whitemagic.core.monitoring.green_score import get_green_score
    report = get_green_score().report()
"""

from __future__ import annotations

import logging
import time
from typing import Any

from whitemagic.core.monitoring.green_score import InferenceLocality, get_green_score

logger = logging.getLogger(__name__)

# Deferred import to avoid circular dependency (tools.middleware imports core modules)
DispatchContext = None
NextFn = None


def _ensure_types():
    global DispatchContext, NextFn
    if DispatchContext is None:
        from whitemagic.core.ports import get_dispatch_context, get_next_fn
        DispatchContext = get_dispatch_context()
        NextFn = get_next_fn()


def _estimate_tokens(text: Any) -> int:
    """Rough token estimate: ~4 chars per token for English text."""
    if isinstance(text, str):
        return max(1, len(text) // 4)
    if isinstance(text, dict):
        # Sum tokens for all string values
        total = 0
        for v in text.values():
            total += _estimate_tokens(v)
        return total
    if isinstance(text, (list, tuple)):
        return sum(_estimate_tokens(item) for item in text)
    return 0


def _determine_locality(ctx: DispatchContext, result: dict[str, Any] | None) -> str:
    """Determine where the computation happened based on context and result."""
    if result is None or not isinstance(result, dict):
        return InferenceLocality.EDGE

    if result.get("resolved_locally"):
        return InferenceLocality.EDGE

    tool_lower = ctx.tool_name.lower()
    if any(p in tool_lower for p in ("llama", "bitnet", "local")):
        return InferenceLocality.LOCAL_LLM
    if any(p in tool_lower for p in ("cloud", "openai", "anthropic", "api")):
        return InferenceLocality.CLOUD

    tier = ctx.meta.get("inference_tier", "")
    if tier == "edge":
        return InferenceLocality.EDGE
    if tier == "local":
        return InferenceLocality.LOCAL_LLM
    if tier == "cloud":
        return InferenceLocality.CLOUD

    # Default: edge for local tools, cloud for AI tools
    if ctx.meta.get("local_inference_attempted"):
        return InferenceLocality.LOCAL_LLM

    return InferenceLocality.EDGE


def mw_token_tracker(
    ctx: DispatchContext,
    next_fn: NextFn,
) -> dict[str, Any] | None:
    """Track token usage for every tool call in the dispatch pipeline.

    Records input tokens (from kwargs), output tokens (from result),
    and saved tokens (from local resolution) to GreenScore telemetry.
    """
    if ctx.meta.get("quiet_internal_benchmark"):
        return next_fn(ctx)

    start = time.time()

    # Estimate input tokens from kwargs
    input_tokens = _estimate_tokens(ctx.kwargs)

    result = next_fn(ctx)

    if result is None:
        return result

    # Estimate output tokens from result
    output_tokens = _estimate_tokens(result)

    # Determine locality
    locality = _determine_locality(ctx, result)

    # Calculate tokens saved (if resolved locally)
    tokens_saved = 0
    if isinstance(result, dict):
        tokens_saved = result.get("tokens_saved", 0)
    if isinstance(result, dict) and result.get("resolved_locally") and not tokens_saved:
        # Estimate: if we resolved locally, we saved the output tokens
        # that would have been generated by an LLM
        tokens_saved = output_tokens

    # Record to GreenScore
    duration_ms = (time.time() - start) * 1000
    try:
        gs = get_green_score()
        gs.record_inference(
            locality=locality,
            tokens_used=input_tokens + output_tokens,
            tokens_saved=tokens_saved,
            tool=ctx.tool_name,
            duration_ms=duration_ms,
        )
    except (RuntimeError, ValueError, TypeError, AttributeError) as e:
        logger.debug("Token tracker: GreenScore recording failed: %s", e)

    # Record to Token Economy (consciousness system)
    try:
        from whitemagic.core.consciousness.token_economy import get_token_tracker

        economy = get_token_tracker()
        total_tokens = input_tokens + output_tokens
        if locality == InferenceLocality.CLOUD:
            economy.record_api_call(ctx.tool_name, total_tokens)
        elif locality == InferenceLocality.LOCAL_LLM:
            economy.record_local_script(ctx.tool_name, duration_ms, bytes_out=0)
            economy.record_usage(total_tokens, source="local", operation=ctx.tool_name)
        else:
            # Edge/local compute — track as local operation
            economy.record_mcp_tool(ctx.tool_name, duration_ms)
    except (ImportError, RuntimeError, ValueError, TypeError, AttributeError) as e:
        logger.debug("Token tracker: token_economy recording failed: %s", e)

    # Inject token metadata into result
    if isinstance(result, dict):
        result.setdefault("metadata", {})
        result["metadata"]["token_tracking"] = {
            "input_tokens": input_tokens,
            "output_tokens": output_tokens,
            "tokens_saved": tokens_saved,
            "locality": locality,
            "duration_ms": round(duration_ms, 2),
        }

    return result
