/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_edgeengine_free: (a: number, b: number) => void;
export const __wbg_edgerule_free: (a: number, b: number) => void;
export const __wbg_inferenceresult_free: (a: number, b: number) => void;
export const batch_similarity: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const cosine_similarity: (a: number, b: number, c: number, d: number) => number;
export const edgeengine_add_rule: (a: number, b: number) => void;
export const edgeengine_get_stats: (a: number) => [number, number];
export const edgeengine_infer: (a: number, b: number, c: number) => number;
export const edgeengine_local_rate: (a: number) => number;
export const edgeengine_new: () => number;
export const edgeengine_reset_stats: (a: number) => void;
export const edgeengine_tokens_saved: (a: number) => number;
export const edgerule_confidence: (a: number) => number;
export const edgerule_id: (a: number) => [number, number];
export const edgerule_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => number;
export const edgerule_response: (a: number) => [number, number];
export const inferenceresult_answer: (a: number) => [number, number];
export const inferenceresult_confidence: (a: number) => number;
export const inferenceresult_method: (a: number) => [number, number];
export const inferenceresult_needs_cloud: (a: number) => number;
export const inferenceresult_tokens_saved: (a: number) => number;
export const quick_infer: (a: number, b: number) => [number, number];
export const text_search: (a: number, b: number, c: number, d: number) => [number, number];
export const wasm_ready: () => number;
export const wasm_version: () => [number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
