#!/usr/bin/env python3
"""
Apply generated bridge catalog entries + TS impls to the actual site files.

This is the second stage of the v22.3.0 catalog expansion:
1. generate_bridge_catalog.py -> writes content to tmp/catalog_gen/
2. apply_bridge_catalog.py     -> splices that content into lib/data/mcp-bridge.ts and lib/bridge/impl.ts

It updates:
  - lib/data/mcp-bridge.ts  (append 113 BRIDGE_MODULES entries)
  - lib/bridge/impl.ts      (insert 112 new impls + 113 dispatcher entries)
  - lib/facts.ts            (update callableTools / bridge fn count)

Run this from ~/Desktop/WHITEMAGIC-aux/site/whitemagic-site
"""
from __future__ import annotations
import json
import re
import subprocess
import sys
from pathlib import Path

SITE = Path("/home/lucas/Desktop/WHITEMAGIC-aux/site/whitemagic-site")
GEN = SITE / "tmp" / "catalog_gen"

CATALOG = SITE / "lib" / "data" / "mcp-bridge.ts"
IMPL = SITE / "lib" / "bridge" / "impl.ts"
FACTS = SITE / "lib" / "facts.ts"


def patch_catalog():
    new_entries = (GEN / "new_catalog_entries.ts").read_text()
    text = CATALOG.read_text()
    # Append before the closing `];`
    marker = "];\n\nexport const BRIDGE_SUMMARY"
    assert marker in text, "BRIDGE_SUMMARY marker not found in catalog"
    new_text = text.replace(marker, new_entries + "\n];\n\nexport const BRIDGE_SUMMARY")
    CATALOG.write_text(new_text)
    print(f"[OK] Catalog: {text.count('{') } -> {new_text.count('{')} entries")


def patch_impl():
    new_impls = (GEN / "new_impls.ts").read_text()
    new_dispatch = (GEN / "new_dispatcher.txt").read_text()
    text = IMPL.read_text()
    # Insert impls before "// ─── dispatcher"
    dispatcher_marker = "// ─── dispatcher"
    assert dispatcher_marker in text
    # Build the v22.3.0 section
    section = (
        "\n// ─── v22.3.0 catalog expansion (113 functions) ──────────────────────\n"
        "// Generated by scripts/generate_bridge_catalog.py +\n"
        "// scripts/apply_bridge_catalog.py. Each impl is a thin TS shim that\n"
        "// returns a shape-matching response; the canonical Python source lives\n"
        "// in core/whitemagic/core/bridge/*.py. When the Hetzner MCP server is\n"
        "// live, these will be replaced by a Python proxy.\n\n"
        f"{new_impls}"
        f"{dispatcher_marker}"
    )
    new_text = text.replace(dispatcher_marker, section)
    # Now add new dispatcher entries to the IMPLS object
    impls_open = "const IMPLS: Record<string, Impl> = {"
    assert impls_open in new_text
    # The current dispatcher has a `gana_dipper,` followed by `};`
    marker_in_dispatcher = "  gana_dipper,\n};"
    assert marker_in_dispatcher in new_text
    new_text = new_text.replace(
        marker_in_dispatcher,
        f"  gana_dipper,\n{new_dispatch}}};"
    )
    IMPL.write_text(new_text)
    print(f"[OK] Impl: {text.count('export function')} -> {new_text.count('export function')} functions")


def patch_facts():
    text = FACTS.read_text()
    # The current count is 30 BRIDGE_MODULES. Update to 143.
    # Also update "490 callable tools" -> 143 public functions (or keep 490 for full surface).
    # Per site AGENTS.md §4: facts.ts is canonical, update last.
    # We'll update functionsTotal: 30 -> 143
    new_text = re.sub(
        r"functionsTotal:\s*\d+",
        "functionsTotal: 143",
        text,
    )
    if new_text == text:
        print("[WARN] facts.ts: no functionsTotal field to update")
    else:
        FACTS.write_text(new_text)
        print("[OK] facts.ts: functionsTotal -> 143")


def main():
    if not GEN.exists():
        print("ERROR: tmp/catalog_gen not found. Run generate_bridge_catalog.py first.", file=sys.stderr)
        sys.exit(1)
    patch_catalog()
    patch_impl()
    patch_facts()
    # Quick TS validation
    print("\n=== Running tsc --noEmit to validate ===")
    result = subprocess.run(
        ["npx", "tsc", "--noEmit"],
        cwd=SITE,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print("TS ERRORS:")
        print(result.stdout)
        print(result.stderr)
        sys.exit(1)
    else:
        print("[OK] tsc --noEmit passed")


if __name__ == "__main__":
    main()
