#!/usr/bin/env bash
# sync_public.sh — Sanitize and push WHITEMAGIC main → public repo (lbailey94/whitemagic)
#
# Usage:
#   ./scripts/sync_public.sh          # sync + push
#   ./scripts/sync_public.sh --dry    # sync only, no push (preview)
#
# What it does:
#   1. Creates a temporary branch from main
#   2. Removes all paths listed in .publicignore
#   3. Commits the sanitized state
#   4. Force-pushes to the 'public' remote (lbailey94/whitemagic)
#   5. Cleans up the temporary branch
#
# The public repo gets a clean, sanitized snapshot of the project
# without internal strategy docs, deployment configs, conversation
# extracts, or auxiliary workspaces.

set -euo pipefail

REMOTE_NAME="public"
REMOTE_URL="https://github.com/lbailey94/whitemagic.git"
DRY_RUN=false
PUBLICIGNORE="$(git rev-parse --show-toplevel)/.publicignore"

if [[ "${1:-}" == "--dry" ]]; then
    DRY_RUN=true
fi

echo "=== sync_public.sh ==="
echo "Remote: $REMOTE_NAME ($REMOTE_URL)"
echo "Mode:   $(${DRY_RUN} && echo 'DRY RUN (no push)' || echo 'LIVE (will push)')"
echo ""

# --- Sanity checks ---
if [[ ! -f "$PUBLICIGNORE" ]]; then
    echo "ERROR: .publicignore not found at $PUBLICIGNORE"
    exit 1
fi

if ! git remote get-url "$REMOTE_NAME" >/dev/null 2>&1; then
    echo "ERROR: remote '$REMOTE_NAME' not configured"
    echo "Add it with: git remote add public $REMOTE_URL"
    exit 1
fi

# --- Ensure we're on main and up to date ---
CURRENT_BRANCH=$(git branch --show-current)
if [[ "$CURRENT_BRANCH" != "main" ]]; then
    echo "ERROR: not on main branch (currently on $CURRENT_BRANCH)"
    exit 1
fi

echo "Current HEAD: $(git rev-parse --short HEAD)"
echo ""

# --- Create temp branch ---
TEMP_BRANCH="sync-public-$(date +%Y%m%d-%H%M%S)"
echo "Creating temp branch: $TEMP_BRANCH"
git checkout -b "$TEMP_BRANCH"

# --- Remove sensitive paths ---
echo ""
echo "Removing sensitive paths from .publicignore:"
REMOVED=0
while IFS= read -r pattern; do
    # Skip comments and empty lines
    [[ -z "$pattern" || "$pattern" =~ ^# ]] && continue
    
    # Remove trailing slash for git rm
    clean_path="${pattern%/}"
    
    if git ls-files --error-unmatch "$clean_path" >/dev/null 2>&1 || \
       git ls-files "$clean_path" | grep -q .; then
        echo "  removing: $clean_path"
        git rm -r --cached --quiet "$clean_path" 2>/dev/null || true
        REMOVED=$((REMOVED + 1))
    else
        echo "  skip (not tracked): $clean_path"
    fi
done < "$PUBLICIGNORE"

echo ""
echo "Removed $REMOVED path(s) from index"

# --- Commit ---
git commit -m "chore: sanitize for public sync — remove internal paths

Generated by scripts/sync_public.sh
Source: $(git rev-parse --short main)
Excluded paths per .publicignore"

echo ""
echo "Sanitized commit: $(git rev-parse --short HEAD)"

# --- Show what would be pushed ---
echo ""
echo "=== Diff summary (public/main → sanitized) ==="
git diff --stat "public/main..$TEMP_BRANCH" 2>/dev/null | tail -10

if $DRY_RUN; then
    echo ""
    echo "DRY RUN — no push. To push for real:"
    echo "  ./scripts/sync_public.sh"
    echo ""
    echo "To inspect the sanitized branch:"
    echo "  git log --oneline $TEMP_BRANCH -3"
    echo "  git diff public/main..$TEMP_BRANCH --stat"
    echo ""
    echo "Cleaning up temp branch..."
    git checkout -f main
    git branch -D "$TEMP_BRANCH"
else
    # --- Push ---
    echo ""
    echo "Pushing to $REMOTE_NAME..."
    git push --force "$REMOTE_NAME" "$TEMP_BRANCH:main"
    
    # --- Cleanup ---
    git checkout -f main
    git branch -D "$TEMP_BRANCH"
    
    echo ""
    echo "=== DONE ==="
    echo "Public repo updated: $REMOTE_URL"
    echo "Sanitized from: $(git rev-parse --short main)"
fi
