# ruff: noqa: BLE001
"""Self-Initiation System — unified autonomous action generation and execution.

Merges three formerly separate modules:
  - self_directed_attention.py (7+1 action type taxonomy)
  - self_prompting.py (priority work queue with file persistence)
  - sentience.py:IntentionQueue (Dharma gating + karma logging)

The unified pipeline:
  1. generate_self_initiated_turn() → SelfInitiatedTurn (7+1 action types)
  2. submit_to_queue(turn) → Dharma gate → priority queue
  3. process_queue() → execute approved items by priority
  4. All executions karma-logged

Backward compat: queue_work(), process_queue(), get_self_directed_attention()
are re-exported for existing consumers.
"""

from __future__ import annotations

import json
import logging
import threading
import time
import uuid
from collections.abc import Callable
from dataclasses import asdict, dataclass, field
from datetime import datetime
from enum import IntEnum
from typing import Any

from whitemagic.config.paths import WM_ROOT
from whitemagic.core.consciousness import emotional_steering as es_mod
from whitemagic.core.consciousness import goal_graph as gg_mod

logger = logging.getLogger(__name__)

_AUTONOMOUS_DIR = WM_ROOT / "autonomous"
_AUTONOMOUS_DIR.mkdir(parents=True, exist_ok=True)


# ── Priority enum (from self_prompting) ──────────────────────────────


class Priority(IntEnum):
    """Work-item priority (lower number = higher priority)."""

    CRITICAL = 1
    HIGH = 3
    NORMAL = 5
    LOW = 7
    BACKGROUND = 9


# ── SelfInitiatedTurn (from self_directed_attention) ─────────────────


@dataclass
class SelfInitiatedTurn:
    """A turn generated by the system without external prompting.

    The 7+1 action types (from Phase 0b directive taxonomy):
    1. build    — "I should build X"
    2. plan     — "I should plan X"
    3. fix      — "I should fix X"
    4. research — "I should investigate X"
    5. improve  — "I should improve X"
    6. audit    — "I should review X"
    7. test     — "I should verify X"
    8. connect  — "I should reflect on X" (the 8th type)
    """
    action_type: str
    imperative: str
    reasoning: str
    emotional_signal: str | None = None
    intensity: float = 0.0
    timestamp: float = field(default_factory=time.time)
    acted_on: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "action_type": self.action_type,
            "imperative": self.imperative,
            "reasoning": self.reasoning,
            "emotional_signal": self.emotional_signal,
            "intensity": round(self.intensity, 3),
            "timestamp": self.timestamp,
            "acted_on": self.acted_on,
        }


# ── WorkItem (from self_prompting) ───────────────────────────────────


@dataclass
class WorkItem:
    """A self-queued task with priority and Dharma gating."""

    id: str = field(default_factory=lambda: uuid.uuid4().hex[:12])
    task: str = ""
    priority: int = Priority.NORMAL
    handler: str = ""
    params: dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    status: str = "pending"
    result: str = ""
    attempts: int = 0
    max_attempts: int = 3
    dharma_approved: bool = False
    action_type: str = ""
    emotional_signal: str | None = None
    intensity: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> WorkItem:
        return cls(**{k: v for k, v in data.items() if k in cls.__dataclass_fields__})


@dataclass
class HumanQuestion:
    """A question awaiting human input."""

    id: str = field(default_factory=lambda: uuid.uuid4().hex[:12])
    question: str = ""
    context: str = ""
    asked_at: str = field(default_factory=lambda: datetime.now().isoformat())
    answered: bool = False
    answer: str = ""


# ── File persistence (from self_prompting) ───────────────────────────


def _load_queue() -> list[WorkItem]:
    path = _AUTONOMOUS_DIR / "work_queue.json"
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text())
        return [WorkItem.from_dict(d) for d in data]
    except Exception as exc:
        logger.warning("Failed to load work queue: %s", exc)
        return []


def _save_queue(items: list[WorkItem]) -> None:
    path = _AUTONOMOUS_DIR / "work_queue.json"
    path.write_text(json.dumps([i.to_dict() for i in items], indent=2))


def _load_questions() -> list[HumanQuestion]:
    path = _AUTONOMOUS_DIR / "human_questions.json"
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text())
        return [HumanQuestion(**{k: v for k, v in d.items() if k in HumanQuestion.__dataclass_fields__}) for d in data]
    except Exception:
        return []


def _save_questions(qs: list[HumanQuestion]) -> None:
    path = _AUTONOMOUS_DIR / "human_questions.json"
    path.write_text(json.dumps([asdict(q) for q in qs], indent=2))


# ── Handler registry (from self_prompting) ───────────────────────────


_handlers: dict[str, Callable[..., Any]] = {}
_handlers_lock = threading.RLock()


def register_handler(name: str, fn: Callable[..., Any]) -> None:
    """Register a named handler for work items."""
    with _handlers_lock:
        _handlers[name] = fn


def _default_handler(item: WorkItem) -> str:
    logger.info("Self-initiation executing (no handler): %s", item.task)
    return f"executed: {item.task}"


# ── Dharma gating (from IntentionQueue) ──────────────────────────────


def _dharma_gate(item: WorkItem) -> bool:
    """Check if a work item passes Dharma ethical validation.

    Items without a handler are pure-thought and always allowed.
    Items with a handler are validated through the governor.
    """
    if not item.handler:
        item.dharma_approved = True
        return True

    try:
        from whitemagic.tools.unified_api import call_tool
        result = call_tool("governor.validate", tool=item.handler, params=item.params)
        approved = result.get("status") == "success"
        item.dharma_approved = approved
        return approved
    except Exception as e:
        logger.debug("Dharma gate failed for %s: %s", item.id, e)
        item.dharma_approved = False
        return False


def _karma_log(item: WorkItem, outcome: str) -> None:
    """Log a work item execution to the karma ledger."""
    try:
        from whitemagic.tools.unified_api import call_tool
        call_tool(
            "karma.record",
            action=f"self_initiation:{item.action_type or 'task'}",
            tool=item.handler or "thought",
            outcome=outcome,
            description=item.task[:200],
            dharma_approved=item.dharma_approved,
        )
    except Exception as e:
        logger.debug("Karma log failed for %s: %s", item.id, e)


# ── Self-directed attention (from self_directed_attention) ───────────


class SelfDirectedAttention:
    """Generates self-initiated turns based on system state.

    Observes:
    - Goal graph (active goals, blocked goals, proposed goals)
    - Emotional steering signals (frustration, curiosity, satisfaction)
    - System state (test results, error patterns, memory clusters)

    Generates:
    - Internal imperatives ("I should fix X", "I should explore Y")
    - Prioritized by emotional signal intensity
    """

    def __init__(self) -> None:
        self._generated_turns: list[SelfInitiatedTurn] = []
        self._last_observation: float = 0.0
        self._observation_interval = 60.0  # observe every 60s

    def observe_and_generate(self) -> list[SelfInitiatedTurn]:
        """Observe system state and generate self-initiated turns.

        Returns a list of turns that the system could act on.
        The caller decides whether to actually execute them.
        """
        now = time.time()
        if now - self._last_observation < self._observation_interval:
            return []
        self._last_observation = now

        turns: list[SelfInitiatedTurn] = []

        # 1. Check emotional steering for impulses
        steering = es_mod.get_emotional_steering()
        impulse = steering.get_impulse()

        if impulse:
            if impulse["signal"] == "frustration":
                turns.append(SelfInitiatedTurn(
                    action_type="fix",
                    imperative="I should try a different approach — the current one is failing",
                    reasoning=f"Frustration signal: {impulse['reason']}",
                    emotional_signal="frustration",
                    intensity=impulse["intensity"],
                ))
            elif impulse["signal"] == "curiosity":
                clusters = impulse.get("clusters", [])
                cluster_str = ", ".join(clusters[:3]) if clusters else "unexplored areas"
                turns.append(SelfInitiatedTurn(
                    action_type="research",
                    imperative=f"I should explore {cluster_str} — there are unexplored areas",
                    reasoning=f"Curiosity signal: {len(clusters)} unexplored clusters detected",
                    emotional_signal="curiosity",
                    intensity=impulse["intensity"],
                ))
            elif impulse["signal"] == "satisfaction":
                turns.append(SelfInitiatedTurn(
                    action_type="connect",
                    imperative="I should reflect on what worked well and reinforce it",
                    reasoning=f"Satisfaction signal: success rate {impulse.get('success_rate', 0)}",
                    emotional_signal="satisfaction",
                    intensity=impulse["intensity"],
                ))

        # 2. Check goal graph for blocked/proposed goals
        goal_graph = gg_mod.get_goal_graph()
        blocked = goal_graph.get_blocked_goals()
        for goal in blocked[:2]:
            turns.append(SelfInitiatedTurn(
                action_type="fix",
                imperative=f"I should unblock '{goal.title}' — it's been blocked",
                reasoning=f"Goal {goal.id} is blocked with {len(goal.dependencies)} dependencies",
            ))

        proposed = goal_graph.get_proposed_goals()
        for goal in proposed[:2]:
            turns.append(SelfInitiatedTurn(
                action_type="build",
                imperative=f"I should start working on '{goal.title}' — it's been proposed but not started",
                reasoning=f"Goal {goal.id} is proposed but not yet active",
            ))

        # 3. Generate curiosity-driven exploration if no active goals
        active = goal_graph.get_active_goals()
        if not active and not turns:
            turns.append(SelfInitiatedTurn(
                action_type="connect",
                imperative="I should reflect on what I should be working on — no active goals",
                reasoning="No active goals in the goal graph. The system should self-direct.",
                emotional_signal="curiosity",
                intensity=0.3,
            ))

        # 4. Sort by intensity (highest first)
        turns.sort(key=lambda t: t.intensity, reverse=True)

        # 5. Record generated turns
        self._generated_turns.extend(turns)

        return turns

    def get_generated_turns(self, limit: int = 20) -> list[SelfInitiatedTurn]:
        return self._generated_turns[-limit:]

    def mark_acted_on(self, index: int) -> None:
        if 0 <= index < len(self._generated_turns):
            self._generated_turns[index].acted_on = True

    def get_summary(self) -> dict[str, Any]:
        total = len(self._generated_turns)
        acted = sum(1 for t in self._generated_turns if t.acted_on)
        by_type: dict[str, int] = {}
        for t in self._generated_turns:
            by_type[t.action_type] = by_type.get(t.action_type, 0) + 1
        return {
            "total_generated": total,
            "acted_on": acted,
            "by_type": by_type,
            "last_observation": self._last_observation,
        }


# ── Unified queue API ────────────────────────────────────────────────


def submit_turn(turn: SelfInitiatedTurn, handler: str = "", params: dict[str, Any] | None = None) -> str:
    """Convert a SelfInitiatedTurn into a queued WorkItem with Dharma gating.

    Returns the work-item ID.
    """
    priority = Priority.HIGH if turn.intensity > 0.5 else Priority.NORMAL
    item = WorkItem(
        task=turn.imperative,
        priority=int(priority),
        handler=handler,
        params=params or {},
        action_type=turn.action_type,
        emotional_signal=turn.emotional_signal,
        intensity=turn.intensity,
    )
    items = _load_queue()
    items.append(item)
    _save_queue(items)
    logger.info("Self-initiation queued [%s] pri=%d: %s", item.id, item.priority, turn.imperative)
    return item.id


def queue_work(
    task: str,
    priority: int = Priority.NORMAL,
    handler: str = "",
    params: dict[str, Any] | None = None,
) -> str:
    """Queue work for later processing. Returns the work-item ID.

    Backward compat with self_prompting.queue_work.
    """
    item = WorkItem(
        task=task,
        priority=int(priority),
        handler=handler,
        params=params or {},
    )
    items = _load_queue()
    items.append(item)
    _save_queue(items)
    logger.info("Queued work [%s] pri=%d: %s", item.id, item.priority, task)
    return item.id


def process_queue(limit: int = 10) -> dict[str, Any]:
    """Process queued work items in priority order with Dharma gating.

    Unified pipeline: Dharma gate → execute → karma log.
    """
    items = _load_queue()
    pending = [i for i in items if i.status == "pending"]
    pending.sort(key=lambda i: i.priority)

    stats: dict[str, Any] = {
        "processed": 0, "failed": 0, "skipped": 0, "dharma_blocked": 0,
        "remaining": 0, "results": [],
    }

    for item in pending[:limit]:
        # Dharma gate
        if not item.dharma_approved:
            if not _dharma_gate(item):
                stats["dharma_blocked"] += 1
                continue

        item.attempts += 1
        item.status = "running"
        with _handlers_lock:
            handler_fn = _handlers.get(item.handler, _default_handler)
        try:
            result = handler_fn(item)
            item.status = "done"
            item.result = str(result) if result else "ok"
            stats["processed"] += 1
            stats["results"].append({"id": item.id, "task": item.task, "result": item.result})
            _karma_log(item, "success")
        except Exception as exc:
            if item.attempts >= item.max_attempts:
                item.status = "failed"
                stats["failed"] += 1
                _karma_log(item, "error")
            else:
                item.status = "pending"
                stats["skipped"] += 1
            item.result = f"error: {exc}"
            logger.warning("Work item %s failed (attempt %d): %s", item.id, item.attempts, exc)

    stats["remaining"] = sum(1 for i in items if i.status == "pending")
    _save_queue(items)
    return stats


def ask_human(question: str, context: str = "") -> str:
    """Record a question for the human operator."""
    q = HumanQuestion(question=question, context=context)
    qs = _load_questions()
    qs.append(q)
    _save_questions(qs)
    logger.info("Question queued [%s]: %s", q.id, question)
    return q.id


def answer_question(question_id: str, answer: str) -> bool:
    """Provide an answer to a pending question."""
    qs = _load_questions()
    for q in qs:
        if q.id == question_id and not q.answered:
            q.answered = True
            q.answer = answer
            _save_questions(qs)
            return True
    return False


def get_pending_questions() -> list[dict[str, Any]]:
    """Return all unanswered questions."""
    qs = _load_questions()
    return [asdict(q) for q in qs if not q.answered]


def get_queue_status() -> dict[str, Any]:
    """Return a summary of the work queue."""
    items = _load_queue()
    by_status: dict[str, int] = {}
    for item in items:
        by_status[item.status] = by_status.get(item.status, 0) + 1
    return {
        "total": len(items),
        "by_status": by_status,
        "pending_questions": len([q for q in _load_questions() if not q.answered]),
    }


def clear_completed() -> int:
    """Remove done/failed items from the queue. Returns count removed."""
    items = _load_queue()
    before = len(items)
    items = [i for i in items if i.status not in ("done", "failed")]
    _save_queue(items)
    removed = before - len(items)
    logger.info("Cleared %d completed work items", removed)
    return removed


# ── SelfInitiationQueue (unified class for OOP access) ───────────────


class SelfInitiationQueue:
    """Unified self-initiation queue: generate → Dharma gate → execute → karma log.

    Combines the 7+1 action type taxonomy from SelfDirectedAttention,
    the priority queue from self_prompting, and Dharma gating + karma
    logging from IntentionQueue.
    """

    def __init__(self, max_size: int = 100) -> None:
        self._max_size = max_size
        self._attention = SelfDirectedAttention()
        self._lock = threading.RLock()

    def observe_and_generate(self) -> list[SelfInitiatedTurn]:
        """Observe system state and generate self-initiated turns."""
        return self._attention.observe_and_generate()

    def submit(self, description: str, tool: str | None = None,
               args: dict[str, Any] | None = None,
               source_phase: str = "",
               priority: int = 0) -> str:
        """Submit a new intention for Dharma gating.

        Returns the work-item ID.
        """
        return queue_work(
            task=description,
            priority=Priority.HIGH if priority > 0 else Priority.NORMAL,
            handler=tool or "",
            params=args or {},
        )

    def process(self, limit: int = 10) -> dict[str, Any]:
        """Process queued items through Dharma gate → execute → karma log."""
        return process_queue(limit=limit)

    def status(self) -> dict[str, Any]:
        """Get queue status."""
        return get_queue_status()

    @property
    def attention(self) -> SelfDirectedAttention:
        """Access the underlying SelfDirectedAttention instance."""
        return self._attention


# ── Singleton Access ─────────────────────────────────────────────────

_self_directed: SelfDirectedAttention | None = None
_initiation_queue: SelfInitiationQueue | None = None
_lock = threading.RLock()


def get_self_directed_attention() -> SelfDirectedAttention:
    """Get the global self-directed attention instance."""
    global _self_directed
    if _self_directed is None:
        with _lock:
            if _self_directed is None:
                _self_directed = SelfDirectedAttention()
    return _self_directed


def get_self_initiation_queue() -> SelfInitiationQueue:
    """Get the global self-initiation queue instance."""
    global _initiation_queue
    if _initiation_queue is None:
        with _lock:
            if _initiation_queue is None:
                _initiation_queue = SelfInitiationQueue()
    return _initiation_queue
