"""Self-Directed Attention — Internal action generation without external prompting.

The 7+1 action types (from Phase 0b directive taxonomy):
1. Build/Implement — "I should build X"
2. Discuss/Plan — "I should plan X"
3. Fix/Debug — "I should fix X"
4. Research/Explore — "I should investigate X"
5. Improve/Optimize — "I should improve X"
6. Audit/Review — "I should review X"
7. Test/Verify — "I should verify X"
8. Connect/Reflect — "I should reflect on X" (the 8th type from the 3.3%)

This module generates self-initiated turns by observing system state
and producing internal imperatives. It uses the emotional steering
signals to prioritize which impulses to act on.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Any

from whitemagic.core.consciousness import emotional_steering as es_mod
from whitemagic.core.consciousness import goal_graph as gg_mod


@dataclass
class SelfInitiatedTurn:
    """A turn generated by the system without external prompting."""
    action_type: str
    imperative: str
    reasoning: str
    emotional_signal: str | None = None
    intensity: float = 0.0
    timestamp: float = field(default_factory=time.time)
    acted_on: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "action_type": self.action_type,
            "imperative": self.imperative,
            "reasoning": self.reasoning,
            "emotional_signal": self.emotional_signal,
            "intensity": round(self.intensity, 3),
            "timestamp": self.timestamp,
            "acted_on": self.acted_on,
        }


class SelfDirectedAttention:
    """Generates self-initiated turns based on system state.

    Observes:
    - Goal graph (active goals, blocked goals, proposed goals)
    - Emotional steering signals (frustration, curiosity, satisfaction)
    - System state (test results, error patterns, memory clusters)

    Generates:
    - Internal imperatives ("I should fix X", "I should explore Y")
    - Prioritized by emotional signal intensity
    """

    def __init__(self) -> None:
        self._generated_turns: list[SelfInitiatedTurn] = []
        self._last_observation: float = 0.0
        self._observation_interval = 60.0  # observe every 60s

    def observe_and_generate(self) -> list[SelfInitiatedTurn]:
        """Observe system state and generate self-initiated turns.

        Returns a list of turns that the system could act on.
        The caller decides whether to actually execute them.
        """
        now = time.time()
        if now - self._last_observation < self._observation_interval:
            return []
        self._last_observation = now

        turns: list[SelfInitiatedTurn] = []

        # 1. Check emotional steering for impulses
        steering = es_mod.get_emotional_steering()
        impulse = steering.get_impulse()

        if impulse:
            if impulse["signal"] == "frustration":
                turns.append(SelfInitiatedTurn(
                    action_type="fix",
                    imperative="I should try a different approach — the current one is failing",
                    reasoning=f"Frustration signal: {impulse['reason']}",
                    emotional_signal="frustration",
                    intensity=impulse["intensity"],
                ))
            elif impulse["signal"] == "curiosity":
                clusters = impulse.get("clusters", [])
                cluster_str = ", ".join(clusters[:3]) if clusters else "unexplored areas"
                turns.append(SelfInitiatedTurn(
                    action_type="research",
                    imperative=f"I should explore {cluster_str} — there are unexplored areas",
                    reasoning=f"Curiosity signal: {len(clusters)} unexplored clusters detected",
                    emotional_signal="curiosity",
                    intensity=impulse["intensity"],
                ))
            elif impulse["signal"] == "satisfaction":
                turns.append(SelfInitiatedTurn(
                    action_type="connect",
                    imperative="I should reflect on what worked well and reinforce it",
                    reasoning=f"Satisfaction signal: success rate {impulse.get('success_rate', 0)}",
                    emotional_signal="satisfaction",
                    intensity=impulse["intensity"],
                ))

        # 2. Check goal graph for blocked/proposed goals
        goal_graph = gg_mod.get_goal_graph()
        blocked = goal_graph.get_blocked_goals()
        for goal in blocked[:2]:
            turns.append(SelfInitiatedTurn(
                action_type="fix",
                imperative=f"I should unblock '{goal.title}' — it's been blocked",
                reasoning=f"Goal {goal.id} is blocked with {len(goal.dependencies)} dependencies",
            ))

        proposed = goal_graph.get_proposed_goals()
        for goal in proposed[:2]:
            turns.append(SelfInitiatedTurn(
                action_type="build",
                imperative=f"I should start working on '{goal.title}' — it's been proposed but not started",
                reasoning=f"Goal {goal.id} is proposed but not yet active",
            ))

        # 3. Generate curiosity-driven exploration if no active goals
        active = goal_graph.get_active_goals()
        if not active and not turns:
            turns.append(SelfInitiatedTurn(
                action_type="connect",
                imperative="I should reflect on what I should be working on — no active goals",
                reasoning="No active goals in the goal graph. The system should self-direct.",
                emotional_signal="curiosity",
                intensity=0.3,
            ))

        # 4. Sort by intensity (highest first)
        turns.sort(key=lambda t: t.intensity, reverse=True)

        # 5. Record generated turns
        self._generated_turns.extend(turns)

        return turns

    def get_generated_turns(self, limit: int = 20) -> list[SelfInitiatedTurn]:
        return self._generated_turns[-limit:]

    def mark_acted_on(self, index: int) -> None:
        if 0 <= index < len(self._generated_turns):
            self._generated_turns[index].acted_on = True

    def get_summary(self) -> dict[str, Any]:
        total = len(self._generated_turns)
        acted = sum(1 for t in self._generated_turns if t.acted_on)
        by_type: dict[str, int] = {}
        for t in self._generated_turns:
            by_type[t.action_type] = by_type.get(t.action_type, 0) + 1
        return {
            "total_generated": total,
            "acted_on": acted,
            "by_type": by_type,
            "last_observation": self._last_observation,
        }


_singleton: SelfDirectedAttention | None = None


def get_self_directed_attention() -> SelfDirectedAttention:
    global _singleton
    if _singleton is None:
        _singleton = SelfDirectedAttention()
    return _singleton
