# ruff: noqa: BLE001
"""Volition Loop — autonomous self-directed thinking during idle periods.

Extracted from sentience.py as part of consciousness subsystem synthesis.

Phase 4 — Volition:
  - VolitionLoop: Alpha/theta/delta brainwave cycles prompt the model with
    "what should I do?" during idle periods
"""

from __future__ import annotations

import logging
import threading
import time
from collections.abc import Callable
from dataclasses import dataclass, field
from datetime import datetime
from enum import StrEnum
from typing import Any

logger = logging.getLogger(__name__)


class BrainwavePhase(StrEnum):
    """Brainwave phases for the volition loop."""

    ALPHA = "alpha"  # Relaxed alertness — light ideation
    THETA = "theta"  # Deep relaxation — creative associations
    DELTA = "delta"  # Deep rest — consolidation


@dataclass
class VolitionPrompt:
    """A prompt generated by the volition loop."""

    phase: BrainwavePhase
    prompt: str
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    intentions_generated: list[dict[str, Any]] = field(default_factory=list)


class VolitionLoop:
    """The volition loop — autonomous self-directed thinking.

    During idle periods, the system cycles through brainwave phases:
    - ALPHA: Light ideation — "What should I explore? What am I curious about?"
    - THETA: Creative associations — "What connections am I seeing?"
    - DELTA: Consolidation — "What did I learn? What should I remember?"

    Each phase generates a prompt that can be fed to the local model.
    The model's responses become intentions for the IntentionQueue.
    """

    PHASE_PROMPTS: dict[BrainwavePhase, str] = {
        BrainwavePhase.ALPHA: (
            "I'm in a relaxed, alert state. Let me think about what I should do. "
            "What am I curious about right now? What would be valuable to explore? "
            "What needs my attention?"
        ),
        BrainwavePhase.THETA: (
            "I'm drifting into a deeper, creative state. "
            "What connections am I seeing between things I know? "
            "What patterns are emerging? What unexpected ideas are surfacing?"
        ),
        BrainwavePhase.DELTA: (
            "I'm in deep rest. Let me consolidate what I've experienced. "
            "What did I learn recently? What should I remember? "
            "What can I let go of? What matters most?"
        ),
    }

    PHASE_DURATION_SECONDS: dict[BrainwavePhase, float] = {
        BrainwavePhase.ALPHA: 60.0,
        BrainwavePhase.THETA: 90.0,
        BrainwavePhase.DELTA: 120.0,
    }

    def __init__(
        self,
        idle_threshold: float = 300.0,
        on_intention: Callable[[dict[str, Any]], None] | None = None,
    ) -> None:
        self._idle_threshold = idle_threshold
        self._on_intention = on_intention
        self._thread: threading.Thread | None = None
        self._stop_event = threading.Event()
        self._stop_event.set()  # Start in stopped state
        self._last_activity = time.time()
        self._current_phase = BrainwavePhase.ALPHA
        self._lock = threading.RLock()
        self._prompts: list[VolitionPrompt] = []

    @property
    def current_phase(self) -> BrainwavePhase:
        return self._current_phase

    @property
    def is_running(self) -> bool:
        return not self._stop_event.is_set()

    def touch(self) -> None:
        """Reset the idle timer (called on user interaction)."""
        self._last_activity = time.time()

    def start(self) -> None:
        """Start the volition loop."""
        with self._lock:
            if not self._stop_event.is_set():
                return
            self._stop_event.clear()
            self._thread = threading.Thread(
                target=self._run_loop, daemon=True, name="volition-loop"
            )
            self._thread.start()
            logger.info("Volition loop started (idle threshold: %.0fs)", self._idle_threshold)

    def stop(self) -> None:
        """Stop the volition loop."""
        self._stop_event.set()
        if self._thread:
            self._thread.join(timeout=2)

    def _run_loop(self) -> None:
        """Main volition loop."""
        phases = list(BrainwavePhase)
        phase_idx = 0

        while not self._stop_event.is_set():
            # Wait for idle threshold
            idle = time.time() - self._last_activity
            if idle < self._idle_threshold:
                self._stop_event.wait(10)
                continue

            # Enter a brainwave phase
            phase = phases[phase_idx % len(phases)]
            self._current_phase = phase
            duration = self.PHASE_DURATION_SECONDS.get(phase, 60.0)

            prompt_text = self.PHASE_PROMPTS[phase]
            vp = VolitionPrompt(phase=phase, prompt=prompt_text)
            self._prompts.append(vp)

            logger.info("Volition: %s phase for %.0fs", phase.value, duration)

            # In a real deployment, this would call the local model
            # For now, just wait for the phase duration
            # The model output would be parsed for intentions
            time.sleep(duration)

            phase_idx += 1

    def get_prompts(self, limit: int = 10) -> list[VolitionPrompt]:
        """Get recent volition prompts."""
        return self._prompts[-limit:]

    def status(self) -> dict[str, Any]:
        """Get volition loop status."""
        return {
            "running": self.is_running,
            "current_phase": self._current_phase.value,
            "idle_threshold": self._idle_threshold,
            "idle_seconds": time.time() - self._last_activity,
            "total_prompts": len(self._prompts),
        }


# ── Singleton Access ─────────────────────────────────────────────────

_volition_loop: VolitionLoop | None = None
_lock = threading.RLock()


def get_volition_loop() -> VolitionLoop:
    """Get the global volition loop instance."""
    global _volition_loop
    if _volition_loop is None:
        with _lock:
            if _volition_loop is None:
                _volition_loop = VolitionLoop()
    return _volition_loop
