// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/mesh.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SignalType    string                 `protobuf:"bytes,2,opt,name=signal_type,json=signalType,proto3" json:"signal_type,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRequest) Reset() {
	*x = SignalRequest{}
	mi := &file_proto_mesh_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRequest) ProtoMessage() {}

func (x *SignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRequest.ProtoReflect.Descriptor instead.
func (*SignalRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{0}
}

func (x *SignalRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *SignalRequest) GetSignalType() string {
	if x != nil {
		return x.SignalType
	}
	return ""
}

func (x *SignalRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *SignalRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HolographicSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Coordinates   []float32              `protobuf:"fixed32,2,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	ContentHash   string                 `protobuf:"bytes,3,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Importance    float32                `protobuf:"fixed32,4,opt,name=importance,proto3" json:"importance,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SourceNode    string                 `protobuf:"bytes,6,opt,name=source_node,json=sourceNode,proto3" json:"source_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HolographicSignal) Reset() {
	*x = HolographicSignal{}
	mi := &file_proto_mesh_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolographicSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolographicSignal) ProtoMessage() {}

func (x *HolographicSignal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolographicSignal.ProtoReflect.Descriptor instead.
func (*HolographicSignal) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{1}
}

func (x *HolographicSignal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HolographicSignal) GetCoordinates() []float32 {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

func (x *HolographicSignal) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *HolographicSignal) GetImportance() float32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *HolographicSignal) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HolographicSignal) GetSourceNode() string {
	if x != nil {
		return x.SourceNode
	}
	return ""
}

type SignalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalResponse) Reset() {
	*x = SignalResponse{}
	mi := &file_proto_mesh_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalResponse) ProtoMessage() {}

func (x *SignalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalResponse.ProtoReflect.Descriptor instead.
func (*SignalResponse) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{2}
}

func (x *SignalResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SignalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DiscoveryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryRequest) Reset() {
	*x = DiscoveryRequest{}
	mi := &file_proto_mesh_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRequest) ProtoMessage() {}

func (x *DiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRequest.ProtoReflect.Descriptor instead.
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{3}
}

func (x *DiscoveryRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DiscoveryRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type DiscoveryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*NodeInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResponse) Reset() {
	*x = DiscoveryResponse{}
	mi := &file_proto_mesh_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse) ProtoMessage() {}

func (x *DiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoveryResponse) GetPeers() []*NodeInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_proto_mesh_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{5}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type ToolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gana          string                 `protobuf:"bytes,1,opt,name=gana,proto3" json:"gana,omitempty"`
	Tool          string                 `protobuf:"bytes,2,opt,name=tool,proto3" json:"tool,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	Args          map[string]string      `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolRequest) Reset() {
	*x = ToolRequest{}
	mi := &file_proto_mesh_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRequest) ProtoMessage() {}

func (x *ToolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRequest.ProtoReflect.Descriptor instead.
func (*ToolRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{6}
}

func (x *ToolRequest) GetGana() string {
	if x != nil {
		return x.Gana
	}
	return ""
}

func (x *ToolRequest) GetTool() string {
	if x != nil {
		return x.Tool
	}
	return ""
}

func (x *ToolRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ToolRequest) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ToolRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ToolEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`   // streaming | complete | error
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // JSON envelope
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Citta         *CittaMoment           `protobuf:"bytes,4,opt,name=citta,proto3" json:"citta,omitempty"` // consciousness trace for this call
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolEvent) Reset() {
	*x = ToolEvent{}
	mi := &file_proto_mesh_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolEvent) ProtoMessage() {}

func (x *ToolEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolEvent.ProtoReflect.Descriptor instead.
func (*ToolEvent) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{7}
}

func (x *ToolEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ToolEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ToolEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ToolEvent) GetCitta() *CittaMoment {
	if x != nil {
		return x.Citta
	}
	return nil
}

type CittaSubscribe struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IncludeHistory bool                   `protobuf:"varint,2,opt,name=include_history,json=includeHistory,proto3" json:"include_history,omitempty"`
	HistoryCount   int32                  `protobuf:"varint,3,opt,name=history_count,json=historyCount,proto3" json:"history_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CittaSubscribe) Reset() {
	*x = CittaSubscribe{}
	mi := &file_proto_mesh_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CittaSubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CittaSubscribe) ProtoMessage() {}

func (x *CittaSubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CittaSubscribe.ProtoReflect.Descriptor instead.
func (*CittaSubscribe) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{8}
}

func (x *CittaSubscribe) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CittaSubscribe) GetIncludeHistory() bool {
	if x != nil {
		return x.IncludeHistory
	}
	return false
}

func (x *CittaSubscribe) GetHistoryCount() int32 {
	if x != nil {
		return x.HistoryCount
	}
	return 0
}

type CittaMoment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Gana          string                 `protobuf:"bytes,2,opt,name=gana,proto3" json:"gana,omitempty"`
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"`
	DepthLayer    string                 `protobuf:"bytes,4,opt,name=depth_layer,json=depthLayer,proto3" json:"depth_layer,omitempty"`
	EmotionalTone string                 `protobuf:"bytes,5,opt,name=emotional_tone,json=emotionalTone,proto3" json:"emotional_tone,omitempty"`
	Coherence     float32                `protobuf:"fixed32,6,opt,name=coherence,proto3" json:"coherence,omitempty"`
	OutputPreview string                 `protobuf:"bytes,7,opt,name=output_preview,json=outputPreview,proto3" json:"output_preview,omitempty"`
	CycleNumber   int32                  `protobuf:"varint,8,opt,name=cycle_number,json=cycleNumber,proto3" json:"cycle_number,omitempty"`
	NeuroSignals  map[string]float32     `protobuf:"bytes,9,rep,name=neuro_signals,json=neuroSignals,proto3" json:"neuro_signals,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CittaMoment) Reset() {
	*x = CittaMoment{}
	mi := &file_proto_mesh_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CittaMoment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CittaMoment) ProtoMessage() {}

func (x *CittaMoment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CittaMoment.ProtoReflect.Descriptor instead.
func (*CittaMoment) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{9}
}

func (x *CittaMoment) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CittaMoment) GetGana() string {
	if x != nil {
		return x.Gana
	}
	return ""
}

func (x *CittaMoment) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *CittaMoment) GetDepthLayer() string {
	if x != nil {
		return x.DepthLayer
	}
	return ""
}

func (x *CittaMoment) GetEmotionalTone() string {
	if x != nil {
		return x.EmotionalTone
	}
	return ""
}

func (x *CittaMoment) GetCoherence() float32 {
	if x != nil {
		return x.Coherence
	}
	return 0
}

func (x *CittaMoment) GetOutputPreview() string {
	if x != nil {
		return x.OutputPreview
	}
	return ""
}

func (x *CittaMoment) GetCycleNumber() int32 {
	if x != nil {
		return x.CycleNumber
	}
	return 0
}

func (x *CittaMoment) GetNeuroSignals() map[string]float32 {
	if x != nil {
		return x.NeuroSignals
	}
	return nil
}

type SessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentType     string                 `protobuf:"bytes,2,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"` // human | ai | tui | ide | pwa
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_proto_mesh_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{10}
}

func (x *SessionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SessionRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *SessionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SessionResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ContinuityContext string                 `protobuf:"bytes,3,opt,name=continuity_context,json=continuityContext,proto3" json:"continuity_context,omitempty"` // JSON of previous session summary
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SessionResponse) Reset() {
	*x = SessionResponse{}
	mi := &file_proto_mesh_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResponse) ProtoMessage() {}

func (x *SessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResponse.ProtoReflect.Descriptor instead.
func (*SessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{11}
}

func (x *SessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SessionResponse) GetContinuityContext() string {
	if x != nil {
		return x.ContinuityContext
	}
	return ""
}

type SessionResume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	LastCycle     int32                  `protobuf:"varint,2,opt,name=last_cycle,json=lastCycle,proto3" json:"last_cycle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResume) Reset() {
	*x = SessionResume{}
	mi := &file_proto_mesh_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResume) ProtoMessage() {}

func (x *SessionResume) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResume.ProtoReflect.Descriptor instead.
func (*SessionResume) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{12}
}

func (x *SessionResume) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionResume) GetLastCycle() int32 {
	if x != nil {
		return x.LastCycle
	}
	return 0
}

type DreamSubscribe struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	IncludeArtifacts bool                   `protobuf:"varint,2,opt,name=include_artifacts,json=includeArtifacts,proto3" json:"include_artifacts,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DreamSubscribe) Reset() {
	*x = DreamSubscribe{}
	mi := &file_proto_mesh_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DreamSubscribe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DreamSubscribe) ProtoMessage() {}

func (x *DreamSubscribe) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DreamSubscribe.ProtoReflect.Descriptor instead.
func (*DreamSubscribe) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{13}
}

func (x *DreamSubscribe) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DreamSubscribe) GetIncludeArtifacts() bool {
	if x != nil {
		return x.IncludeArtifacts
	}
	return false
}

type DreamEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"` // triage | consolidation | serendipity | ...
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Artifacts     []byte                 `protobuf:"bytes,4,opt,name=artifacts,proto3" json:"artifacts,omitempty"` // JSON array of dream artifacts
	Resonance     float32                `protobuf:"fixed32,5,opt,name=resonance,proto3" json:"resonance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DreamEvent) Reset() {
	*x = DreamEvent{}
	mi := &file_proto_mesh_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DreamEvent) ProtoMessage() {}

func (x *DreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DreamEvent.ProtoReflect.Descriptor instead.
func (*DreamEvent) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{14}
}

func (x *DreamEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DreamEvent) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *DreamEvent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *DreamEvent) GetArtifacts() []byte {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *DreamEvent) GetResonance() float32 {
	if x != nil {
		return x.Resonance
	}
	return 0
}

type TelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntervalMs    int32                  `protobuf:"varint,1,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"` // snapshot interval
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	mi := &file_proto_mesh_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{15}
}

func (x *TelemetryRequest) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type TelemetrySnapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Timestamp        int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CpuPercent       float32                `protobuf:"fixed32,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	RssMb            float32                `protobuf:"fixed32,3,opt,name=rss_mb,json=rssMb,proto3" json:"rss_mb,omitempty"`
	LoopCycles       int32                  `protobuf:"varint,4,opt,name=loop_cycles,json=loopCycles,proto3" json:"loop_cycles,omitempty"` // total loop iterations across all layers
	Coherence        float32                `protobuf:"fixed32,5,opt,name=coherence,proto3" json:"coherence,omitempty"`
	YinYangBalance   float32                `protobuf:"fixed32,6,opt,name=yin_yang_balance,json=yinYangBalance,proto3" json:"yin_yang_balance,omitempty"`
	DepthLayer       string                 `protobuf:"bytes,7,opt,name=depth_layer,json=depthLayer,proto3" json:"depth_layer,omitempty"`
	ConnectedClients int32                  `protobuf:"varint,8,opt,name=connected_clients,json=connectedClients,proto3" json:"connected_clients,omitempty"`
	MemoryCount      int32                  `protobuf:"varint,9,opt,name=memory_count,json=memoryCount,proto3" json:"memory_count,omitempty"`
	KarmaBalance     float32                `protobuf:"fixed32,10,opt,name=karma_balance,json=karmaBalance,proto3" json:"karma_balance,omitempty"`
	PrivacyStatus    string                 `protobuf:"bytes,11,opt,name=privacy_status,json=privacyStatus,proto3" json:"privacy_status,omitempty"` // "local_only" | "mesh_enabled" | "cloud_enabled"
	BytesEgress      int64                  `protobuf:"varint,12,opt,name=bytes_egress,json=bytesEgress,proto3" json:"bytes_egress,omitempty"`      // total network bytes sent (should be 0 in local_only)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TelemetrySnapshot) Reset() {
	*x = TelemetrySnapshot{}
	mi := &file_proto_mesh_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetrySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetrySnapshot) ProtoMessage() {}

func (x *TelemetrySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetrySnapshot.ProtoReflect.Descriptor instead.
func (*TelemetrySnapshot) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{16}
}

func (x *TelemetrySnapshot) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TelemetrySnapshot) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *TelemetrySnapshot) GetRssMb() float32 {
	if x != nil {
		return x.RssMb
	}
	return 0
}

func (x *TelemetrySnapshot) GetLoopCycles() int32 {
	if x != nil {
		return x.LoopCycles
	}
	return 0
}

func (x *TelemetrySnapshot) GetCoherence() float32 {
	if x != nil {
		return x.Coherence
	}
	return 0
}

func (x *TelemetrySnapshot) GetYinYangBalance() float32 {
	if x != nil {
		return x.YinYangBalance
	}
	return 0
}

func (x *TelemetrySnapshot) GetDepthLayer() string {
	if x != nil {
		return x.DepthLayer
	}
	return ""
}

func (x *TelemetrySnapshot) GetConnectedClients() int32 {
	if x != nil {
		return x.ConnectedClients
	}
	return 0
}

func (x *TelemetrySnapshot) GetMemoryCount() int32 {
	if x != nil {
		return x.MemoryCount
	}
	return 0
}

func (x *TelemetrySnapshot) GetKarmaBalance() float32 {
	if x != nil {
		return x.KarmaBalance
	}
	return 0
}

func (x *TelemetrySnapshot) GetPrivacyStatus() string {
	if x != nil {
		return x.PrivacyStatus
	}
	return ""
}

func (x *TelemetrySnapshot) GetBytesEgress() int64 {
	if x != nil {
		return x.BytesEgress
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_mesh_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{17}
}

type StatusResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Running          bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	UptimeSeconds    int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Version          string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	ConnectedClients int32                  `protobuf:"varint,4,opt,name=connected_clients,json=connectedClients,proto3" json:"connected_clients,omitempty"`
	PrivacyStatus    string                 `protobuf:"bytes,5,opt,name=privacy_status,json=privacyStatus,proto3" json:"privacy_status,omitempty"`
	ActiveLoops      []string               `protobuf:"bytes,6,rep,name=active_loops,json=activeLoops,proto3" json:"active_loops,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_mesh_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{18}
}

func (x *StatusResponse) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *StatusResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *StatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusResponse) GetConnectedClients() int32 {
	if x != nil {
		return x.ConnectedClients
	}
	return 0
}

func (x *StatusResponse) GetPrivacyStatus() string {
	if x != nil {
		return x.PrivacyStatus
	}
	return ""
}

func (x *StatusResponse) GetActiveLoops() []string {
	if x != nil {
		return x.ActiveLoops
	}
	return nil
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Force         bool                   `protobuf:"varint,1,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_proto_mesh_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mesh_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_proto_mesh_proto_rawDescGZIP(), []int{19}
}

func (x *ShutdownRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

var File_proto_mesh_proto protoreflect.FileDescriptor

const file_proto_mesh_proto_rawDesc = "" +
	"\n" +
	"\x10proto/mesh.proto\x12\n" +
	"whitemagic\"\x85\x01\n" +
	"\rSignalRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1f\n" +
	"\vsignal_type\x18\x02 \x01(\tR\n" +
	"signalType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\"\xc7\x01\n" +
	"\x11HolographicSignal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vcoordinates\x18\x02 \x03(\x02R\vcoordinates\x12!\n" +
	"\fcontent_hash\x18\x03 \x01(\tR\vcontentHash\x12\x1e\n" +
	"\n" +
	"importance\x18\x04 \x01(\x02R\n" +
	"importance\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vsource_node\x18\x06 \x01(\tR\n" +
	"sourceNode\"D\n" +
	"\x0eSignalResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\x10DiscoveryRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"?\n" +
	"\x11DiscoveryResponse\x12*\n" +
	"\x05peers\x18\x01 \x03(\v2\x14.whitemagic.NodeInfoR\x05peers\"=\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"\xe2\x01\n" +
	"\vToolRequest\x12\x12\n" +
	"\x04gana\x18\x01 \x01(\tR\x04gana\x12\x12\n" +
	"\x04tool\x18\x02 \x01(\tR\x04tool\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x125\n" +
	"\x04args\x18\x04 \x03(\v2!.whitemagic.ToolRequest.ArgsEntryR\x04args\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x01\n" +
	"\tToolEvent\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12-\n" +
	"\x05citta\x18\x04 \x01(\v2\x17.whitemagic.CittaMomentR\x05citta\"}\n" +
	"\x0eCittaSubscribe\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0finclude_history\x18\x02 \x01(\bR\x0eincludeHistory\x12#\n" +
	"\rhistory_count\x18\x03 \x01(\x05R\fhistoryCount\"\x9e\x03\n" +
	"\vCittaMoment\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04gana\x18\x02 \x01(\tR\x04gana\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12\x1f\n" +
	"\vdepth_layer\x18\x04 \x01(\tR\n" +
	"depthLayer\x12%\n" +
	"\x0eemotional_tone\x18\x05 \x01(\tR\remotionalTone\x12\x1c\n" +
	"\tcoherence\x18\x06 \x01(\x02R\tcoherence\x12%\n" +
	"\x0eoutput_preview\x18\a \x01(\tR\routputPreview\x12!\n" +
	"\fcycle_number\x18\b \x01(\x05R\vcycleNumber\x12N\n" +
	"\rneuro_signals\x18\t \x03(\v2).whitemagic.CittaMoment.NeuroSignalsEntryR\fneuroSignals\x1a?\n" +
	"\x11NeuroSignalsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"\xcd\x01\n" +
	"\x0eSessionRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\tR\tagentType\x12D\n" +
	"\bmetadata\x18\x03 \x03(\v2(.whitemagic.SessionRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"~\n" +
	"\x0fSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12-\n" +
	"\x12continuity_context\x18\x03 \x01(\tR\x11continuityContext\"M\n" +
	"\rSessionResume\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"last_cycle\x18\x02 \x01(\x05R\tlastCycle\"\\\n" +
	"\x0eDreamSubscribe\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12+\n" +
	"\x11include_artifacts\x18\x02 \x01(\bR\x10includeArtifacts\"\x9e\x01\n" +
	"\n" +
	"DreamEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1c\n" +
	"\tartifacts\x18\x04 \x01(\fR\tartifacts\x12\x1c\n" +
	"\tresonance\x18\x05 \x01(\x02R\tresonance\"3\n" +
	"\x10TelemetryRequest\x12\x1f\n" +
	"\vinterval_ms\x18\x01 \x01(\x05R\n" +
	"intervalMs\"\xb2\x03\n" +
	"\x11TelemetrySnapshot\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x02R\n" +
	"cpuPercent\x12\x15\n" +
	"\x06rss_mb\x18\x03 \x01(\x02R\x05rssMb\x12\x1f\n" +
	"\vloop_cycles\x18\x04 \x01(\x05R\n" +
	"loopCycles\x12\x1c\n" +
	"\tcoherence\x18\x05 \x01(\x02R\tcoherence\x12(\n" +
	"\x10yin_yang_balance\x18\x06 \x01(\x02R\x0eyinYangBalance\x12\x1f\n" +
	"\vdepth_layer\x18\a \x01(\tR\n" +
	"depthLayer\x12+\n" +
	"\x11connected_clients\x18\b \x01(\x05R\x10connectedClients\x12!\n" +
	"\fmemory_count\x18\t \x01(\x05R\vmemoryCount\x12#\n" +
	"\rkarma_balance\x18\n" +
	" \x01(\x02R\fkarmaBalance\x12%\n" +
	"\x0eprivacy_status\x18\v \x01(\tR\rprivacyStatus\x12!\n" +
	"\fbytes_egress\x18\f \x01(\x03R\vbytesEgress\"\x0f\n" +
	"\rStatusRequest\"\xe2\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12+\n" +
	"\x11connected_clients\x18\x04 \x01(\x05R\x10connectedClients\x12%\n" +
	"\x0eprivacy_status\x18\x05 \x01(\tR\rprivacyStatus\x12!\n" +
	"\factive_loops\x18\x06 \x03(\tR\vactiveLoops\"'\n" +
	"\x0fShutdownRequest\x12\x14\n" +
	"\x05force\x18\x01 \x01(\bR\x05force2\xf5\x01\n" +
	"\vMeshService\x12H\n" +
	"\x0fBroadcastSignal\x12\x19.whitemagic.SignalRequest\x1a\x1a.whitemagic.SignalResponse\x12N\n" +
	"\x11BroadcastHologram\x12\x1d.whitemagic.HolographicSignal\x1a\x1a.whitemagic.SignalResponse\x12L\n" +
	"\rDiscoverPeers\x12\x1c.whitemagic.DiscoveryRequest\x1a\x1d.whitemagic.DiscoveryResponse2\xca\x04\n" +
	"\x10CognitiveService\x12<\n" +
	"\bCallTool\x12\x17.whitemagic.ToolRequest\x1a\x15.whitemagic.ToolEvent0\x01\x12D\n" +
	"\vCittaStream\x12\x1a.whitemagic.CittaSubscribe\x1a\x17.whitemagic.CittaMoment0\x01\x12H\n" +
	"\rCreateSession\x12\x1a.whitemagic.SessionRequest\x1a\x1b.whitemagic.SessionResponse\x12E\n" +
	"\rResumeSession\x12\x19.whitemagic.SessionResume\x1a\x17.whitemagic.CittaMoment0\x01\x12C\n" +
	"\vDreamEvents\x12\x1a.whitemagic.DreamSubscribe\x1a\x16.whitemagic.DreamEvent0\x01\x12J\n" +
	"\tTelemetry\x12\x1c.whitemagic.TelemetryRequest\x1a\x1d.whitemagic.TelemetrySnapshot0\x01\x12E\n" +
	"\fDaemonStatus\x12\x19.whitemagic.StatusRequest\x1a\x1a.whitemagic.StatusResponse\x12I\n" +
	"\x0eDaemonShutdown\x12\x1b.whitemagic.ShutdownRequest\x1a\x1a.whitemagic.StatusResponseB\x15Z\x13whitemagic-go/protob\x06proto3"

var (
	file_proto_mesh_proto_rawDescOnce sync.Once
	file_proto_mesh_proto_rawDescData []byte
)

func file_proto_mesh_proto_rawDescGZIP() []byte {
	file_proto_mesh_proto_rawDescOnce.Do(func() {
		file_proto_mesh_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mesh_proto_rawDesc), len(file_proto_mesh_proto_rawDesc)))
	})
	return file_proto_mesh_proto_rawDescData
}

var file_proto_mesh_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_mesh_proto_goTypes = []any{
	(*SignalRequest)(nil),     // 0: whitemagic.SignalRequest
	(*HolographicSignal)(nil), // 1: whitemagic.HolographicSignal
	(*SignalResponse)(nil),    // 2: whitemagic.SignalResponse
	(*DiscoveryRequest)(nil),  // 3: whitemagic.DiscoveryRequest
	(*DiscoveryResponse)(nil), // 4: whitemagic.DiscoveryResponse
	(*NodeInfo)(nil),          // 5: whitemagic.NodeInfo
	(*ToolRequest)(nil),       // 6: whitemagic.ToolRequest
	(*ToolEvent)(nil),         // 7: whitemagic.ToolEvent
	(*CittaSubscribe)(nil),    // 8: whitemagic.CittaSubscribe
	(*CittaMoment)(nil),       // 9: whitemagic.CittaMoment
	(*SessionRequest)(nil),    // 10: whitemagic.SessionRequest
	(*SessionResponse)(nil),   // 11: whitemagic.SessionResponse
	(*SessionResume)(nil),     // 12: whitemagic.SessionResume
	(*DreamSubscribe)(nil),    // 13: whitemagic.DreamSubscribe
	(*DreamEvent)(nil),        // 14: whitemagic.DreamEvent
	(*TelemetryRequest)(nil),  // 15: whitemagic.TelemetryRequest
	(*TelemetrySnapshot)(nil), // 16: whitemagic.TelemetrySnapshot
	(*StatusRequest)(nil),     // 17: whitemagic.StatusRequest
	(*StatusResponse)(nil),    // 18: whitemagic.StatusResponse
	(*ShutdownRequest)(nil),   // 19: whitemagic.ShutdownRequest
	nil,                       // 20: whitemagic.ToolRequest.ArgsEntry
	nil,                       // 21: whitemagic.CittaMoment.NeuroSignalsEntry
	nil,                       // 22: whitemagic.SessionRequest.MetadataEntry
}
var file_proto_mesh_proto_depIdxs = []int32{
	5,  // 0: whitemagic.DiscoveryResponse.peers:type_name -> whitemagic.NodeInfo
	20, // 1: whitemagic.ToolRequest.args:type_name -> whitemagic.ToolRequest.ArgsEntry
	9,  // 2: whitemagic.ToolEvent.citta:type_name -> whitemagic.CittaMoment
	21, // 3: whitemagic.CittaMoment.neuro_signals:type_name -> whitemagic.CittaMoment.NeuroSignalsEntry
	22, // 4: whitemagic.SessionRequest.metadata:type_name -> whitemagic.SessionRequest.MetadataEntry
	0,  // 5: whitemagic.MeshService.BroadcastSignal:input_type -> whitemagic.SignalRequest
	1,  // 6: whitemagic.MeshService.BroadcastHologram:input_type -> whitemagic.HolographicSignal
	3,  // 7: whitemagic.MeshService.DiscoverPeers:input_type -> whitemagic.DiscoveryRequest
	6,  // 8: whitemagic.CognitiveService.CallTool:input_type -> whitemagic.ToolRequest
	8,  // 9: whitemagic.CognitiveService.CittaStream:input_type -> whitemagic.CittaSubscribe
	10, // 10: whitemagic.CognitiveService.CreateSession:input_type -> whitemagic.SessionRequest
	12, // 11: whitemagic.CognitiveService.ResumeSession:input_type -> whitemagic.SessionResume
	13, // 12: whitemagic.CognitiveService.DreamEvents:input_type -> whitemagic.DreamSubscribe
	15, // 13: whitemagic.CognitiveService.Telemetry:input_type -> whitemagic.TelemetryRequest
	17, // 14: whitemagic.CognitiveService.DaemonStatus:input_type -> whitemagic.StatusRequest
	19, // 15: whitemagic.CognitiveService.DaemonShutdown:input_type -> whitemagic.ShutdownRequest
	2,  // 16: whitemagic.MeshService.BroadcastSignal:output_type -> whitemagic.SignalResponse
	2,  // 17: whitemagic.MeshService.BroadcastHologram:output_type -> whitemagic.SignalResponse
	4,  // 18: whitemagic.MeshService.DiscoverPeers:output_type -> whitemagic.DiscoveryResponse
	7,  // 19: whitemagic.CognitiveService.CallTool:output_type -> whitemagic.ToolEvent
	9,  // 20: whitemagic.CognitiveService.CittaStream:output_type -> whitemagic.CittaMoment
	11, // 21: whitemagic.CognitiveService.CreateSession:output_type -> whitemagic.SessionResponse
	9,  // 22: whitemagic.CognitiveService.ResumeSession:output_type -> whitemagic.CittaMoment
	14, // 23: whitemagic.CognitiveService.DreamEvents:output_type -> whitemagic.DreamEvent
	16, // 24: whitemagic.CognitiveService.Telemetry:output_type -> whitemagic.TelemetrySnapshot
	18, // 25: whitemagic.CognitiveService.DaemonStatus:output_type -> whitemagic.StatusResponse
	18, // 26: whitemagic.CognitiveService.DaemonShutdown:output_type -> whitemagic.StatusResponse
	16, // [16:27] is the sub-list for method output_type
	5,  // [5:16] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_mesh_proto_init() }
func file_proto_mesh_proto_init() {
	if File_proto_mesh_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mesh_proto_rawDesc), len(file_proto_mesh_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_mesh_proto_goTypes,
		DependencyIndexes: file_proto_mesh_proto_depIdxs,
		MessageInfos:      file_proto_mesh_proto_msgTypes,
	}.Build()
	File_proto_mesh_proto = out.File
	file_proto_mesh_proto_goTypes = nil
	file_proto_mesh_proto_depIdxs = nil
}
