// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/mesh.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MeshService_BroadcastSignal_FullMethodName   = "/whitemagic.MeshService/BroadcastSignal"
	MeshService_BroadcastHologram_FullMethodName = "/whitemagic.MeshService/BroadcastHologram"
	MeshService_DiscoverPeers_FullMethodName     = "/whitemagic.MeshService/DiscoverPeers"
)

// MeshServiceClient is the client API for MeshService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeshServiceClient interface {
	BroadcastSignal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error)
	BroadcastHologram(ctx context.Context, in *HolographicSignal, opts ...grpc.CallOption) (*SignalResponse, error)
	DiscoverPeers(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error)
}

type meshServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeshServiceClient(cc grpc.ClientConnInterface) MeshServiceClient {
	return &meshServiceClient{cc}
}

func (c *meshServiceClient) BroadcastSignal(ctx context.Context, in *SignalRequest, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, MeshService_BroadcastSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) BroadcastHologram(ctx context.Context, in *HolographicSignal, opts ...grpc.CallOption) (*SignalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalResponse)
	err := c.cc.Invoke(ctx, MeshService_BroadcastHologram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *meshServiceClient) DiscoverPeers(ctx context.Context, in *DiscoveryRequest, opts ...grpc.CallOption) (*DiscoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoveryResponse)
	err := c.cc.Invoke(ctx, MeshService_DiscoverPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeshServiceServer is the server API for MeshService service.
// All implementations must embed UnimplementedMeshServiceServer
// for forward compatibility.
type MeshServiceServer interface {
	BroadcastSignal(context.Context, *SignalRequest) (*SignalResponse, error)
	BroadcastHologram(context.Context, *HolographicSignal) (*SignalResponse, error)
	DiscoverPeers(context.Context, *DiscoveryRequest) (*DiscoveryResponse, error)
	mustEmbedUnimplementedMeshServiceServer()
}

// UnimplementedMeshServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMeshServiceServer struct{}

func (UnimplementedMeshServiceServer) BroadcastSignal(context.Context, *SignalRequest) (*SignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BroadcastSignal not implemented")
}
func (UnimplementedMeshServiceServer) BroadcastHologram(context.Context, *HolographicSignal) (*SignalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BroadcastHologram not implemented")
}
func (UnimplementedMeshServiceServer) DiscoverPeers(context.Context, *DiscoveryRequest) (*DiscoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverPeers not implemented")
}
func (UnimplementedMeshServiceServer) mustEmbedUnimplementedMeshServiceServer() {}
func (UnimplementedMeshServiceServer) testEmbeddedByValue()                     {}

// UnsafeMeshServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeshServiceServer will
// result in compilation errors.
type UnsafeMeshServiceServer interface {
	mustEmbedUnimplementedMeshServiceServer()
}

func RegisterMeshServiceServer(s grpc.ServiceRegistrar, srv MeshServiceServer) {
	// If the following call panics, it indicates UnimplementedMeshServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MeshService_ServiceDesc, srv)
}

func _MeshService_BroadcastSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).BroadcastSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_BroadcastSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).BroadcastSignal(ctx, req.(*SignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_BroadcastHologram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HolographicSignal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).BroadcastHologram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_BroadcastHologram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).BroadcastHologram(ctx, req.(*HolographicSignal))
	}
	return interceptor(ctx, in, info, handler)
}

func _MeshService_DiscoverPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeshServiceServer).DiscoverPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MeshService_DiscoverPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeshServiceServer).DiscoverPeers(ctx, req.(*DiscoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeshService_ServiceDesc is the grpc.ServiceDesc for MeshService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeshService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whitemagic.MeshService",
	HandlerType: (*MeshServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BroadcastSignal",
			Handler:    _MeshService_BroadcastSignal_Handler,
		},
		{
			MethodName: "BroadcastHologram",
			Handler:    _MeshService_BroadcastHologram_Handler,
		},
		{
			MethodName: "DiscoverPeers",
			Handler:    _MeshService_DiscoverPeers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mesh.proto",
}

const (
	CognitiveService_CallTool_FullMethodName       = "/whitemagic.CognitiveService/CallTool"
	CognitiveService_CittaStream_FullMethodName    = "/whitemagic.CognitiveService/CittaStream"
	CognitiveService_CreateSession_FullMethodName  = "/whitemagic.CognitiveService/CreateSession"
	CognitiveService_ResumeSession_FullMethodName  = "/whitemagic.CognitiveService/ResumeSession"
	CognitiveService_DreamEvents_FullMethodName    = "/whitemagic.CognitiveService/DreamEvents"
	CognitiveService_Telemetry_FullMethodName      = "/whitemagic.CognitiveService/Telemetry"
	CognitiveService_DaemonStatus_FullMethodName   = "/whitemagic.CognitiveService/DaemonStatus"
	CognitiveService_DaemonShutdown_FullMethodName = "/whitemagic.CognitiveService/DaemonShutdown"
)

// CognitiveServiceClient is the client API for CognitiveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CognitiveServiceClient interface {
	// Tool dispatch — stream results back to caller
	CallTool(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ToolEvent], error)
	// Citta stream — continuous consciousness updates (subscribe)
	CittaStream(ctx context.Context, in *CittaSubscribe, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CittaMoment], error)
	// Session management
	CreateSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResponse, error)
	ResumeSession(ctx context.Context, in *SessionResume, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CittaMoment], error)
	// Dream cycle events
	DreamEvents(ctx context.Context, in *DreamSubscribe, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DreamEvent], error)
	// System telemetry — periodic snapshots
	Telemetry(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetrySnapshot], error)
	// Daemon control
	DaemonStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	DaemonShutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type cognitiveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCognitiveServiceClient(cc grpc.ClientConnInterface) CognitiveServiceClient {
	return &cognitiveServiceClient{cc}
}

func (c *cognitiveServiceClient) CallTool(ctx context.Context, in *ToolRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ToolEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CognitiveService_ServiceDesc.Streams[0], CognitiveService_CallTool_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ToolRequest, ToolEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CognitiveService_CallToolClient = grpc.ServerStreamingClient[ToolEvent]

func (c *cognitiveServiceClient) CittaStream(ctx context.Context, in *CittaSubscribe, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CittaMoment], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CognitiveService_ServiceDesc.Streams[1], CognitiveService_CittaStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CittaSubscribe, CittaMoment]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CognitiveService_CittaStreamClient = grpc.ServerStreamingClient[CittaMoment]

func (c *cognitiveServiceClient) CreateSession(ctx context.Context, in *SessionRequest, opts ...grpc.CallOption) (*SessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionResponse)
	err := c.cc.Invoke(ctx, CognitiveService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognitiveServiceClient) ResumeSession(ctx context.Context, in *SessionResume, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CittaMoment], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CognitiveService_ServiceDesc.Streams[2], CognitiveService_ResumeSession_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SessionResume, CittaMoment]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CognitiveService_ResumeSessionClient = grpc.ServerStreamingClient[CittaMoment]

func (c *cognitiveServiceClient) DreamEvents(ctx context.Context, in *DreamSubscribe, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DreamEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CognitiveService_ServiceDesc.Streams[3], CognitiveService_DreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DreamSubscribe, DreamEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CognitiveService_DreamEventsClient = grpc.ServerStreamingClient[DreamEvent]

func (c *cognitiveServiceClient) Telemetry(ctx context.Context, in *TelemetryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TelemetrySnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CognitiveService_ServiceDesc.Streams[4], CognitiveService_Telemetry_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TelemetryRequest, TelemetrySnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CognitiveService_TelemetryClient = grpc.ServerStreamingClient[TelemetrySnapshot]

func (c *cognitiveServiceClient) DaemonStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, CognitiveService_DaemonStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cognitiveServiceClient) DaemonShutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, CognitiveService_DaemonShutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CognitiveServiceServer is the server API for CognitiveService service.
// All implementations must embed UnimplementedCognitiveServiceServer
// for forward compatibility.
type CognitiveServiceServer interface {
	// Tool dispatch — stream results back to caller
	CallTool(*ToolRequest, grpc.ServerStreamingServer[ToolEvent]) error
	// Citta stream — continuous consciousness updates (subscribe)
	CittaStream(*CittaSubscribe, grpc.ServerStreamingServer[CittaMoment]) error
	// Session management
	CreateSession(context.Context, *SessionRequest) (*SessionResponse, error)
	ResumeSession(*SessionResume, grpc.ServerStreamingServer[CittaMoment]) error
	// Dream cycle events
	DreamEvents(*DreamSubscribe, grpc.ServerStreamingServer[DreamEvent]) error
	// System telemetry — periodic snapshots
	Telemetry(*TelemetryRequest, grpc.ServerStreamingServer[TelemetrySnapshot]) error
	// Daemon control
	DaemonStatus(context.Context, *StatusRequest) (*StatusResponse, error)
	DaemonShutdown(context.Context, *ShutdownRequest) (*StatusResponse, error)
	mustEmbedUnimplementedCognitiveServiceServer()
}

// UnimplementedCognitiveServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCognitiveServiceServer struct{}

func (UnimplementedCognitiveServiceServer) CallTool(*ToolRequest, grpc.ServerStreamingServer[ToolEvent]) error {
	return status.Error(codes.Unimplemented, "method CallTool not implemented")
}
func (UnimplementedCognitiveServiceServer) CittaStream(*CittaSubscribe, grpc.ServerStreamingServer[CittaMoment]) error {
	return status.Error(codes.Unimplemented, "method CittaStream not implemented")
}
func (UnimplementedCognitiveServiceServer) CreateSession(context.Context, *SessionRequest) (*SessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedCognitiveServiceServer) ResumeSession(*SessionResume, grpc.ServerStreamingServer[CittaMoment]) error {
	return status.Error(codes.Unimplemented, "method ResumeSession not implemented")
}
func (UnimplementedCognitiveServiceServer) DreamEvents(*DreamSubscribe, grpc.ServerStreamingServer[DreamEvent]) error {
	return status.Error(codes.Unimplemented, "method DreamEvents not implemented")
}
func (UnimplementedCognitiveServiceServer) Telemetry(*TelemetryRequest, grpc.ServerStreamingServer[TelemetrySnapshot]) error {
	return status.Error(codes.Unimplemented, "method Telemetry not implemented")
}
func (UnimplementedCognitiveServiceServer) DaemonStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DaemonStatus not implemented")
}
func (UnimplementedCognitiveServiceServer) DaemonShutdown(context.Context, *ShutdownRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DaemonShutdown not implemented")
}
func (UnimplementedCognitiveServiceServer) mustEmbedUnimplementedCognitiveServiceServer() {}
func (UnimplementedCognitiveServiceServer) testEmbeddedByValue()                          {}

// UnsafeCognitiveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CognitiveServiceServer will
// result in compilation errors.
type UnsafeCognitiveServiceServer interface {
	mustEmbedUnimplementedCognitiveServiceServer()
}

func RegisterCognitiveServiceServer(s grpc.ServiceRegistrar, srv CognitiveServiceServer) {
	// If the following call panics, it indicates UnimplementedCognitiveServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CognitiveService_ServiceDesc, srv)
}

func _CognitiveService_CallTool_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ToolRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CognitiveServiceServer).CallTool(m, &grpc.GenericServerStream[ToolRequest, ToolEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CognitiveService_CallToolServer = grpc.ServerStreamingServer[ToolEvent]

func _CognitiveService_CittaStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CittaSubscribe)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CognitiveServiceServer).CittaStream(m, &grpc.GenericServerStream[CittaSubscribe, CittaMoment]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CognitiveService_CittaStreamServer = grpc.ServerStreamingServer[CittaMoment]

func _CognitiveService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognitiveServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognitiveService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognitiveServiceServer).CreateSession(ctx, req.(*SessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognitiveService_ResumeSession_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SessionResume)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CognitiveServiceServer).ResumeSession(m, &grpc.GenericServerStream[SessionResume, CittaMoment]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CognitiveService_ResumeSessionServer = grpc.ServerStreamingServer[CittaMoment]

func _CognitiveService_DreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DreamSubscribe)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CognitiveServiceServer).DreamEvents(m, &grpc.GenericServerStream[DreamSubscribe, DreamEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CognitiveService_DreamEventsServer = grpc.ServerStreamingServer[DreamEvent]

func _CognitiveService_Telemetry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TelemetryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CognitiveServiceServer).Telemetry(m, &grpc.GenericServerStream[TelemetryRequest, TelemetrySnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CognitiveService_TelemetryServer = grpc.ServerStreamingServer[TelemetrySnapshot]

func _CognitiveService_DaemonStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognitiveServiceServer).DaemonStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognitiveService_DaemonStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognitiveServiceServer).DaemonStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CognitiveService_DaemonShutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CognitiveServiceServer).DaemonShutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CognitiveService_DaemonShutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CognitiveServiceServer).DaemonShutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CognitiveService_ServiceDesc is the grpc.ServiceDesc for CognitiveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CognitiveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "whitemagic.CognitiveService",
	HandlerType: (*CognitiveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _CognitiveService_CreateSession_Handler,
		},
		{
			MethodName: "DaemonStatus",
			Handler:    _CognitiveService_DaemonStatus_Handler,
		},
		{
			MethodName: "DaemonShutdown",
			Handler:    _CognitiveService_DaemonShutdown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CallTool",
			Handler:       _CognitiveService_CallTool_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CittaStream",
			Handler:       _CognitiveService_CittaStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ResumeSession",
			Handler:       _CognitiveService_ResumeSession_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DreamEvents",
			Handler:       _CognitiveService_DreamEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Telemetry",
			Handler:       _CognitiveService_Telemetry_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/mesh.proto",
}
